@startjson
{
  "@type": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all",
  "ceVlanIdPreservation": "PRESERVE",
  "cTagPcpPreservation": "ENABLED",
  "cTagDeiPreservation": "ENABLED",
  "maximumFrameSize": 1526,
  "ovcL2cpAddressSet": "CTA",
  "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "listOfClassOfServiceNames": ["low"],
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeDuration": "<<skipped>>",
      "startTime": "<<skipped>>"
    }
  ],
  "enniEp": {
    "identifier": "SP1_ENNI-EP1",
    "maintenanceIntermediatePoint": "6",
    "ovcEgressMap": "<<skipped>>",
    "ovcEndPointMap": "<<skipped>>",
    "colorMap": "<<skipped>>",
    "ingressClassOfServiceMap": "<<skipped>>",
    "maintenanceEndPointList": "<<skipped>>"
  },
  "uniEp": {
    "identifier": "NewYork_UNI-EP1",
    "maintenanceIntermediatePoint": "6",
    "ovcEgressMap": "<<skipped>>",
    "ingressBandwidthProfilePerClassOfServiceName": "<<skipped>>",
    "ovcEndPointMap": "<<skipped>>",
    "colorMap": "<<skipped>>",
    "ingressClassOfServiceMap": "<<skipped>>",
    "maintenanceEndPointList": "<<skipped>>"
  }
}
@endjson