@startjson
{
  "identifier": "SP2_ENNI-EP1",
  "maintenanceIntermediatePoint": "6",
  "ovcEgressMap": [
    {
      "mapType": "CN_PCP",
      "cnPcpEntries": [
        {
          "cosName": "low",
          "pcpValue": "1"
        },
        {
          "cosName": "high",
          "pcpValue": "5"
        }
      ]
    }
  ],
  "ovcEndPointMap": {
    "mapType": "FORM_E",
    "ovcEndPointMapFormE": [13]
  },
  "colorMap": {
    "mapType": "DEI"
  },
  "ingressClassOfServiceMap": {
    "mapType": "S_TAG_PCP",
    "map_M": [
      {
        "pcpVal": "0",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "1",
        "pcpCosName": "low"
      },
      {
        "pcpVal": "2",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "3",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "4",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "5",
        "pcpCosName": "high"
      },
      {
        "pcpVal": "6",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "7",
        "pcpCosName": "DISCARD"
      }
    ],
    "l2cp_P": {
      "l2cpIdentifier": {
        "l2cpProtocolType": "LLC",
        "llcAddressOrEtherType": 66
      },
      "l2cpCosName": "low"
      }
  },
  "maintenanceEndPointList": [
    {
      "level": 7,
      "mepDirection": "UP"
    }
  ]
}
@endjson