@startjson
{
  "identifier": "NewYork_UNI-EP1",
  "maintenanceIntermediatePoint": "6",
  "ovcEgressMap": [
    {
      "mapType": "CN_PCP",
      "cnPcpEntries": [
        {
          "cosName": "low",
          "pcpValue": "1"
        }
      ]
    }
  ],
  "ingressBandwidthProfilePerClassOfServiceName": [
    {
      "classOfServiceName": "low",
      "bwpFlow": {
        "eirMax": {
          "irValue": 70,
          "irUnits": "MBPS"
        },
        "envelopeRank": 1,
        "cirMax": {
          "irValue": 0,
          "irUnits": "MBPS"
        },
        "cbs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "couplingFlag": true,
        "envelopeId": "env1",
        "tokenRequestOffset": 0,
        "ebs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "colorMode": "COLOR_BLIND",
        "cir": {
          "irValue": 0,
          "irUnits": "MBPS"
        },
        "eir": {
          "irValue": 70,
          "irUnits": "MBPS"
        }
      }
    }
  ],
  "ovcEndPointMap": {
    "mapType": "FORM_U",
    "ovcEndPointMapFormU": [1, 2]
  },
  "colorMap": {
    "mapType": "DEI"
  },
  "ingressClassOfServiceMap": {
    "mapType": "ENDPOINT",
    "map_M": "low",
    "l2cp_P": {
      "l2cpIdentifier": {
        "l2cpProtocolType": "LLC",
        "llcAddressOrEtherType": "66"
      },
      "l2cpCosName": "low"
      }
  },
  "maintenanceEndPointList": [
    {
      "level": 7,
      "mepDirection": "UP"
    }
  ]
}
@endjson