@startjson
{
  "instantSyncQualification": true,
  "externalId": "BuyerPoq-00002",
  "provideAlternative": false,
  "projectId": "BuyerProjectX",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@example.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all",
          "ceVlanIdPreservation": "PRESERVE",
          "cTagPcpPreservation": "ENABLED",
          "cTagDeiPreservation": "ENABLED",
          "maximumFrameSize": 1526,
          "ovcL2cpAddressSet": "CTA",
          "frameDisposition": {
            "broadcast": "DELIVER_UNCONDITIONALLY",
            "unicast": "DELIVER_CONDITIONALLY",
            "multicast": "DELIVER_UNCONDITIONALLY"
          },
          "listOfClassOfServiceNames": ["low", "high"],
          "availableMegLevel": "6",
          "carrierEthernetSls": [
            {
              "slsCosNameEntry": [
                {
                  "cosName": "low",
                  "oneWayFrameDelayPmMetric": [
                    {
                      "oneWayFdObjective": {
                        "timeDurationValue": 100,
                        "timeDurationUnits": "MS"
                      },
                      "oneWayFdPercentile": 99.5,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
                          "fromCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1",
                          "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
                        }
                      ]
                    }
                  ],
                  "oneWayFrameLossRatioPmMetric": [
                    {
                      "oneWayFlrObjective": 0.001,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
                          "fromCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1",
                          "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
                        }
                      ]
                    }
                  ]
                },
                {
                  "cosName": "high",
                  "oneWayFrameDelayPmMetric": [
                    {
                      "oneWayFdObjective": {
                        "timeDurationValue": 20,
                        "timeDurationUnits": "MS"
                      },
                      "oneWayFdPercentile": 99.7,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
                          "fromCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1",
                          "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
                        }
                      ]
                    }
                  ],
                  "oneWayFrameLossRatioPmMetric": [
                    {
                      "oneWayFlrObjective": 0.0001,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
                          "fromCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1",
                          "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
                        }
                      ]
                    }
                  ],
                  "oneWayFrameDelayRangePmMetric": [
                    {
                      "oneWayFdrObjective": {
                        "timeDurationValue": 10,
                        "timeDurationUnits": "MS"
                      },
                      "oneWayFdrPercentile": 99.7,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
                          "fromCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "SP2_ENNI-EP1",
                          "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
                        }
                      ]
                    }
                  ]
                }
              ],
              "timeDuration": {
                "timeDurationUnits": "MONTH",
                "timeDurationValue": 1
              },
              "startTime": "2021-09-01T00:00:00Z"
            }
          ],
          "enniEp": {
            "identifier": "SP2_ENNI-EP1",
            "maintenanceIntermediatePoint": "6",
            "ovcEgressMap": [
              {
                "mapType": "CN_PCP",
                "cnPcpEntries": [
                  {
                    "cosName": "low",
                    "pcpValue": "1"
                  },
                  {
                    "cosName": "high",
                    "pcpValue": "5"
                  }
                ]
              }
            ],
            "ovcEndPointMap": {
              "mapType": "FORM_E",
              "ovcEndPointMapFormE": [13]
            },
            "colorMap": {
              "mapType": "DEI"
            },
            "ingressClassOfServiceMap": {
              "mapType": "S_TAG_PCP",
              "map_M": [
                {
                  "pcpVal": "0",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "1",
                  "pcpCosName": "low"
                },
                {
                  "pcpVal": "2",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "3",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "4",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "5",
                  "pcpCosName": "high"
                },
                {
                  "pcpVal": "6",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "7",
                  "pcpCosName": "DISCARD"
                }
              ],
              "l2cp_P": {}
            },
            "maintenanceEndPointList": [
              {
                "level": 7,
                "mepDirection": "UP"
              }
            ]
          },
          "uniEp": {
            "identifier": "NewYork_UNI-EP2",
            "maintenanceIntermediatePoint": "6",
            "ovcEgressMap": [
              {
                "mapType": "CN_PCP",
                "cnPcpEntries": [
                  {
                    "cosName": "low",
                    "pcpValue": "1"
                  },
                  {
                    "cosName": "high",
                    "pcpValue": "5"
                  }
                ]
              }
            ],
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeUnits": "KBYTES",
                    "dataSizeValue": 40
                  },
                  "couplingFlag": true,
                  "envelopeId": "env2", 
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeUnits": "KBYTES",
                    "dataSizeValue": 40
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 40,
                    "irUnits": "MBPS"
                  }
                }
              },
              {
                "classOfServiceName": "high",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 50,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 2,
                  "cirMax": {
                    "irValue": 50,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeUnits": "KBYTES",
                    "dataSizeValue": 40
                  },
                  "couplingFlag": true,
                  "envelopeId": "env2",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeUnits": "KBYTES",
                    "dataSizeValue": 40
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 50,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 50,
                    "irUnits": "MBPS"
                  }
                }
              }
            ],
            "ovcEndPointMap": {
              "mapType": "FORM_U",
              "ovcEndPointMapFormU": [3]
            },
            "colorMap": {
              "mapType": "DEI"
            },
            "ingressClassOfServiceMap": {
              "mapType": "C_TAG_PCP",
              "map_M": [
                {
                  "pcpVal": "0",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "1",
                  "pcpCosName": "low"
                },
                {
                  "pcpVal": "2",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "3",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "4",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "5",
                  "pcpCosName": "high"
                },
                {
                  "pcpVal": "6",
                  "pcpCosName": "DISCARD"
                },
                {
                  "pcpVal": "7",
                  "pcpCosName": "DISCARD"
                }
              ],
              "l2cp_P": {
                "l2cpIdentifier": {
                  "l2cpProtocolType": "LLC",
                  "llcAddressOrEtherType": "66"
                },
                "l2cpCosName": "high"
              }
            },
            "maintenanceEndPointList": [
              {
                "level": 7,
                "mepDirection": "UP"
              }
            ]
          }
        },
        "productRelationship": [
          {
            "relationshipType": "CONNECTS_TO_ENNI",
            "id": "SP2_ENNI"
          },
          {
            "relationshipType": "CONNECTS_TO_UNI",
            "id": "NewYork_UNI"
          }
        ]
      }
    }
  ]
}

@endjson