@startjson
{
  "provideAlternative": "false", 
  "bestMatchGeographicAddress": {
    "@type": "FieldedAddress",
    "id": "NewYorkAddress-id-1",
    "href": "{{baseUrl}}/geographicAddress/NewYorkAddress-id-1",
    "allowsNewSite": "true",
    "hasPublicSite": "true",
    "streetNr": "20",
    "streetName": "Example",
    "streetType": "st.",
    "city": "New York",
    "stateOrProvince": "New York",
    "postcode": "10279",
    "country": "United States"
  },
  "submittedGeographicAddress": { 
    "@type": "FieldedAddress",
    "streetNr": "20",
    "streetNrSuffix": "14",
    "streetName": "Example",
    "city": "New York",
    "postcode": "10279",
    "country": "United States"
  }
}
@endjson