@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/geographicAddressValidation_Create

Seller -> Seller : validate Request

alt success
    Buyer <-- Seller : 200 GeographicAddressValidation
else validation or internal problem
    Buyer <-- Seller: 4xx/5xx : error response
end
@enduml