@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Error400 {

    code*: string 
}
Error <|-- Error400



class Error401 {

    code*: string 
}
Error <|-- Error401



class Error403 {

    code*: string 
}
Error <|-- Error403



class Error404 {

    code*: string 
}
Error <|-- Error404


class Error409 {

    code*: string
}
Error <|-- Error409



class Error422 {

    code*: string 
    propertyPath: string 
}
Error <|-- Error422



class Error500 {

    code*: string 
}
Error <|-- Error500


class Error {

    message: string 
    reason*: string 
    referenceError: uri 
}


@enduml
