@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class AttachmentValue {

    attachmentId: string
    author: string
    creationDate: date-time
    content: string
    description: string
    mimeType: string
    name: string
    url: string
    source: MEFBuyerSellerType
}

AttachmentValue *--> MEFByteSize : size


enum DataSizeUnit {

    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}


class EventSubscription {

    id*: string
    callback*: string
    query: string
}



class EventSubscriptionInput {

    callback*: string
    query: string
}



class FieldedAddress {

    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    streetName*: string
    streetNr: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetNrSuffix: string
    streetSuffix: string
    streetType: string
}

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class GeographicSubAddress {

    buildingName: string
    id: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFByteSize {

    amount: float
    units: DataSizeUnit
}



class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class Note {

    id*: string
    author*: string
    date*: date-time
    source*: MEFBuyerSellerType
    text*: string
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddress : postalAddress


class RelatedEntity {

    id*: string
    href: string
    role*: string
    @referredType*: string
}



class TroubleTicket {

    id*: string
    href: string
    creationDate*: date-time
    expectedResolutionDate: date-time
    lastUpdate: date-time
    resolutionDate: date-time
    sellerPriority*: TroubleTicketPriorityType
    sellerSeverity*: TroubleTicketSeverityType
    status*: TroubleTicketStatusType
}
TroubleTicket_Common <|-- TroubleTicket

TroubleTicket *-->"*" TroubleTicketStatusChange : statusChange


class TroubleTicketRelationship {

    id: string
    href: string
    creationDate: date-time
    description: string
    relationshipType: string
    source: MEFBuyerSellerType
}



enum MEFBuyerSellerType {

    buyer
    seller
}
class Reason {

    reason*: string
}



enum TroubleTicketSeverityType {

    minor
    moderate
    significant
    extensive
}
class TroubleTicketStatusChange {

    changeDate: date-time
    changeReason: string
    status: TroubleTicketStatusType
}



enum TroubleTicketStatusType {

    acknowledged
    assessingCancellation
    cancelled
    closed
    inProgress
    pending
    resolved
    reopened
}
enum TroubleTicketType {

    assistance
    degraded
    down
    failure
    installation
    maintenance
}
enum TroubleTicketPriorityType {

    low
    medium
    high
    critical
}
class TroubleTicket_Create {

}
TroubleTicket_Common <|-- TroubleTicket_Create



class TroubleTicket_Common {

    description*: string
    externalId: string
    issueStartDate: date-time
    priority*: TroubleTicketPriorityType
    severity*: TroubleTicketSeverityType
    ticketType*: TroubleTicketType
}

TroubleTicket_Common *-->"*" AttachmentValue : attachment
TroubleTicket_Common *-->"*" Note : note
TroubleTicket_Common *-->"1..*" RelatedEntity : relatedEntity
TroubleTicket_Common *-->"1..*" RelatedContactInformation : relatedContactInformation
TroubleTicket_Common *-->"*" TroubleTicketRelationship : troubleTicketRelationship


class TroubleTicket_Find {

    id*: string
    creationDate*: date-time
    description*: string
    expectedResolutionDate*: date-time
    externalId*: string
    priority*: TroubleTicketPriorityType
    resolutionDate*: date-time
    sellerPriority*: TroubleTicketPriorityType
    sellerSeverity*: TroubleTicketSeverityType
    severity*: TroubleTicketSeverityType
    ticketType*: TroubleTicketType
    status*: TroubleTicketStatusType
}

TroubleTicket_Find *-->"1..*" RelatedEntity : relatedEntity


class TroubleTicket_Update {

    externalId: string
    issueStartDate: date-time
    priority: TroubleTicketPriorityType
    severity: TroubleTicketSeverityType
}

TroubleTicket_Update *-->"*" AttachmentValue : attachment
TroubleTicket_Update *-->"*" Note : note
TroubleTicket_Update *-->"*" RelatedContactInformation : relatedContactInformation
TroubleTicket_Update *-->"*" TroubleTicketRelationship : troubleTicketRelationship


@enduml
