@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}
class AttachmentValue {

    attachmentId: string
    author*: string
    content: string
    creationDate*: date-time
    description: string
    mimeType: string
    name*: string
    source*: MEFBuyerSellerType
    url: string
}

AttachmentValue *--> MEFByteSize : size


class Error400 {

    code*: Error400Code
}
Error <|-- Error400



class Error401 {

    code*: Error401Code
}
Error <|-- Error401



class Error403 {

    code*: Error403Code
}
Error <|-- Error403



class EventSubscription {

    callback*: string
    id*: string
    query: string
}



class FieldedAddress {

    country*: string
    streetType: string
    postcodeExtension: string
    city*: string
    streetNr: string
    locality: string
    postcode: string
    streetNrLast: string
    streetNrSuffix: string
    streetName*: string
    stateOrProvince: string
    streetNrLastSuffix: string
    streetSuffix: string
}

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class Incident_Find {

    closedDate: date-time
    creationDate*: date-time
    description*: string
    expectedClosedDate: date-time
    href: string
    id*: string
    incidentType*: IncidentType
    situationStartDate: date-time
    priority*: TroubleTicketPriorityType
    severity*: TroubleTicketSeverityType
    status*: IncidentStatusType
}

Incident_Find *-->"1..*" RelatedEntity : relatedEntity


class Reason {

    reason*: string
}



enum Error400Code {

    missingQueryParameter
    missingQueryValue
    invalidQuery
    invalidBody
}
class Error409 {

    code*: string
}
Error <|-- Error409



class Error422 {

    code*: Error422Code
    propertyPath: string
}
Error <|-- Error422



class Error500 {

    code*: string
}
Error <|-- Error500



class Error501 {

    code*: string
}
Error <|-- Error501



class IncidentStatusChange {

    changeDate: date-time
    changeReason: string
    status: IncidentStatusType
}



class IssueRelationship {

    @referredType*: string
    creationDate*: date-time
    description*: string
    href: string
    id*: string
    relationshipType*: string
    source*: MEFBuyerSellerType
}



enum Error422Code {

    missingProperty
    invalidValue
    invalidFormat
    referenceNotFound
    unexpectedProperty
    tooManyRecords
    otherIssue
}
enum TroubleTicketSeverityType {

    minor
    moderate
    significant
    extensive
}
class TroubleTicketStatusChange {

    changeDate: date-time
    changeReason: string
    status: TroubleTicketStatusType
}



class TroubleTicket_Update {

    externalId: string
    issueStartDate: date-time
    priority: TroubleTicketPriorityType
    severity: TroubleTicketSeverityType
}

TroubleTicket_Update *-->"*" AttachmentValue : attachment
TroubleTicket_Update *-->"*" Note : note
TroubleTicket_Update *-->"*" RelatedContactInformation : relatedContactInformation
TroubleTicket_Update *-->"*" IssueRelationship : relatedIssue


enum Error401Code {

    missingCredentials
    invalidCredentials
}
class Error404 {

    code*: string
}
Error <|-- Error404



class Error {

    message: string
    reason*: string
    referenceError: uri
}



class EventSubscriptionInput {

    callback*: string
    query: string
}



class GeographicSubAddress {

    buildingName: string
    id: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class Incident {

    closedDate: date-time
    creationDate*: date-time
    description*: string
    expectedClosedDate: date-time
    href: string
    id*: string
    incidentType*: IncidentType
    priority*: TroubleTicketPriorityType
    severity*: TroubleTicketSeverityType
    situationStartDate*: date-time
    status*: IncidentStatusType
}

Incident *-->"*" AttachmentValue : attachment
Incident *-->"*" Note : note
Incident *-->"1..*" RelatedContactInformation : relatedContactInformation
Incident *-->"1..*" RelatedEntity : relatedEntity
Incident *-->"*" IssueRelationship : relatedIssue
Incident *-->"*" IncidentStatusChange : statusChange


enum IncidentStatusType {

    closed
    created
    inProgress
}
class MEFByteSize {

    amount: float
    units: DataSizeUnit
}



enum IncidentType {

    degraded
    down
    intermittent
    maintenance
}
enum Error403Code {

    accessDenied
    forbiddenRequester
    tooManyUsers
}
enum MEFObservedImpactType {

    degraded
    intermittent
    down
}
enum DataSizeUnit {

    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}
class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddress : postalAddress


class RelatedEntity {

    @referredType*: string
    href: string
    id*: string
    role*: string
}



class TroubleTicket {

    creationDate*: date-time
    expectedResolutionDate: date-time
    href: string
    id*: string
    resolutionDate: date-time
    sellerPriority*: TroubleTicketPriorityType
    sellerSeverity*: TroubleTicketSeverityType
    status*: TroubleTicketStatusType
}
TroubleTicket_Common <|-- TroubleTicket

TroubleTicket *-->"*" TroubleTicketStatusChange : statusChange
TroubleTicket *-->"*" WorkOrderRef : workOrder


enum TroubleTicketType {

    assistance
    information
    installation
    maintenance
}
class WorkOrderRef {

    href: string
    id*: string
}



enum TroubleTicketStatusType {

    acknowledged
    assessingCancellation
    cancelled
    closed
    inProgress
    pending
    resolved
    reopened
}
enum TroubleTicketPriorityType {

    low
    medium
    high
    critical
}
class TroubleTicket_Create {

}
TroubleTicket_Common <|-- TroubleTicket_Create



enum MEFBuyerSellerType {

    buyer
    seller
}
class TroubleTicket_Common {

    description*: string
    externalId: string
    issueStartDate: date-time
    observedImpact*: MEFObservedImpactType
    priority*: TroubleTicketPriorityType
    severity*: TroubleTicketSeverityType
    ticketType*: TroubleTicketType
}

TroubleTicket_Common *-->"*" AttachmentValue : attachment
TroubleTicket_Common *-->"*" Note : note
TroubleTicket_Common *-->"1..*" RelatedContactInformation : relatedContactInformation
TroubleTicket_Common *-->"1..*" RelatedEntity : relatedEntity
TroubleTicket_Common *-->"*" IssueRelationship : relatedIssue


class TroubleTicket_Find {

    creationDate*: date-time
    description*: string
    expectedResolutionDate*: date-time
    externalId*: string
    id*: string
    priority*: TroubleTicketPriorityType
    observedImpact*: MEFObservedImpactType
    resolutionDate*: date-time
    sellerPriority*: TroubleTicketPriorityType
    sellerSeverity*: TroubleTicketSeverityType
    severity*: TroubleTicketSeverityType
    status*: TroubleTicketStatusType
    ticketType*: TroubleTicketType
}

TroubleTicket_Find *-->"1..*" RelatedEntity : relatedEntity


@enduml
