@startuml



class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class IncidentAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- IncidentAttributeValueChangeEvent

IncidentAttributeValueChangeEvent *-->"1" IncidentEventPayload : event


class IncidentCreateEvent {

    eventType*: string
}
Event <|-- IncidentCreateEvent

IncidentCreateEvent *-->"1" IncidentEventPayload : event


class IncidentEventPayload {

    id*: string
    href: string
}



class IncidentStatusChangeEvent {

    eventType*: string
}
Event <|-- IncidentStatusChangeEvent

IncidentStatusChangeEvent *-->"1" IncidentStatusChangeEventPayload : event


class IncidentStatusChangeEventPayload {

    id*: string
    href: string
    status*: IncidentStatusType
}



enum IncidentStatusType {

    closed
    created
    inProgress
}
class TroubleTicketAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- TroubleTicketAttributeValueChangeEvent

TroubleTicketAttributeValueChangeEvent *-->"1" TroubleTicketEventPayload : event


class TroubleTicketEventPayload {

    id*: string
    href: string
}



class TroubleTicketInformationRequiredEvent {

    eventType*: string
}
Event <|-- TroubleTicketInformationRequiredEvent

TroubleTicketInformationRequiredEvent *-->"1" TroubleTicketEventPayload : event


class TroubleTicketResolvedEvent {

    eventType*: string
}
Event <|-- TroubleTicketResolvedEvent

TroubleTicketResolvedEvent *-->"1" TroubleTicketEventPayload : event


class TroubleTicketStatusChangeEvent {

    eventType*: string
}
Event <|-- TroubleTicketStatusChangeEvent

TroubleTicketStatusChangeEvent *-->"1" TroubleTicketStatusChangeEventPayload : event


class TroubleTicketStatusChangeEventPayload {

    id*: string
    href: string
    status*: TroubleTicketStatusType
}



enum TroubleTicketStatusType {

    acknowledged
    assessingCancellation
    cancelled
    closed
    inProgress
    pending
    resolved
    reopened
}
@enduml
