@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class RelatedEntity {

    id*: string
    href: string
    role*: string
    @referredType*: string
}



class TroubleTicket_Find {

    creationDate*: date-time
    description*: string
    expectedResolutionDate*: date-time
    externalId*: string
    id*: string
    priority*: TroubleTicketPriorityType
    observedImpact*: MEFObservedImpactType
    resolutionDate*: date-time
    sellerPriority*: TroubleTicketPriorityType
    sellerSeverity*: TroubleTicketSeverityType
    severity*: TroubleTicketSeverityType
    status*: TroubleTicketStatusType
    ticketType*: TroubleTicketType
}

TroubleTicket_Find *-->"1..*" RelatedEntity : relatedEntity
enum TroubleTicketType {

    assistance
    information
    installation
    maintenance
}

enum TroubleTicketSeverityType {

    minor
    moderate
    significant
    extensive
}
enum MEFObservedImpactType {

    degraded
    intermittent
    down
}

enum TroubleTicketStatusType {

    acknowledged
    assessingCancellation
    cancelled
    closed
    inProgress
    pending
    resolved
    reopened
}
enum TroubleTicketPriorityType {

    low
    medium
    high
    critical
}

@enduml
