@startuml

class Incident {

    closedDate: date-time
    creationDate*: date-time
    description*: string
    expectedClosedDate: date-time
    href: string
    id*: string
    impact*: MEFObservedImpactType
    incidentType*: IncidentType
    situationStartDate: date-time
    priority*: TroubleTicketPriorityType
    severity*: TroubleTicketSeverityType
    status*: IncidentStatusType
}

Incident *-->"*" AttachmentValue : attachment
Incident *-->"*" Note : note
Incident *-->"1..*" RelatedContactInformation : relatedContactInformation
Incident *-->"1..*" RelatedEntity : relatedEntity
Incident *-->"*" IssueRelationship : relatedIssue
Incident *-->"1..*" IncidentStatusChange : statusChange


class IssueRelationship {

    @referredType*: string
    creationDate*: date-time
    description*: string
    href: string
    id*: string
    relationshipType*: string
    source*: MEFBuyerSellerType
}



class IncidentStatusChange {

    changeDate: date-time
    changeReason: string
    status: IncidentStatusType
}



class RelatedEntity {

    @referredType*: string
    href: string
    id*: string
    role*: string
}


class IssueRelationship {

    @referredType*: string
    creationDate*: date-time
    description*: string
    href: string
    id*: string
    relationshipType*: string
    source*: MEFBuyerSellerType
}




class AttachmentValue {

    author*: string
    creationDate*: date-time
    description: string
    mimeType: string
    name*: string
    source*: MEFBuyerSellerType
    url*: string
}


AttachmentValue *--> MEFByteSize : size

class MEFByteSize {

    amount*: float
    units*: DataSizeUnit
}

class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}

enum MEFBuyerSellerType {

    buyer
    seller
}


enum DataSizeUnit {

    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}

enum IncidentType {

    installation
    maintenance
    repair
}

enum TroubleTicketPriorityType {

    low
    medium
    high
    critical
}
enum TroubleTicketSeverityType {

    minor
    moderate
    significant
    extensive
}
enum IncidentStatusType {

    closed
    created
    inProgress
}

class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress



class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit



class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}


@enduml
