@startuml

left to right direction
actor Seller
actor Buyer

skinparam usecase {
BackgroundColor<<not implemented>> LightGrey
BorderColor<<not implemented>> Black
}

rectangle {
(1. Create Ticket Request)
(2. Retrieve Ticket List)
(3. Retrieve Ticket by Ticket Identifier)
(4. Patch Ticket by Ticket Identifier)
(5. Cancel Ticket by Ticket Identifier)
(6. Respond to Ticket Clearance Notification)
(7.	Search Appointment Timeslot)<<not implemented>>
(8.	Create Appointment)<<not implemented>> 
(9.	Patch Appointment)<<not implemented>> 
(10. Cancel Appointment)<<not implemented>> 
(11. Retrieve Incident List)<<not implemented>> 
(12. Retrieve Incident by Incident Identifier)<<not implemented>> 
(13. Register for Event Notifications)
(14. Send Ticket Notification)
(15. Send Incident Notification)<<not implemented>> 


Buyer --> (1. Create Ticket Request)
Buyer --> (2. Retrieve Ticket List)
Buyer --> (3. Retrieve Ticket by Ticket Identifier)
Buyer --> (4. Patch Ticket by Ticket Identifier)
Buyer --> (5. Cancel Ticket by Ticket Identifier)
Buyer --> (6. Respond to Ticket Clearance Notification)
Buyer --> (7.	Search Appointment Timeslot)
Buyer --> (8.	Create Appointment)
Buyer --> (9.	Patch Appointment)
Buyer --> (10. Cancel Appointment)
Buyer --> (11. Retrieve Incident List)
Buyer --> (12. Retrieve Incident by Incident Identifier)
Buyer --> (13. Register for Event Notifications)
(14. Send Ticket Notification) <-- Seller
(15. Send Incident Notification) <-- Seller

@enduml
