@startuml

left to right direction
actor Seller
actor Buyer

skinparam usecase {
BackgroundColor<<not implemented>> LightGrey
BorderColor<<not implemented>> Black
}

rectangle {
(1. Create Ticket)
(2. Retrieve Ticket List)
(3. Retrieve Ticket by Ticket Identifier)
(4. Patch Ticket by Ticket Identifier)
(5. Cancel Ticket by Ticket Identifier)
(6. Respond to Ticket Clearance Notification)
(7.	Search Appointment Timeslot)<<not implemented>>
(8.	Create Appointment)<<not implemented>> 
(9.	Retrieve Appointment by Appointment Identifier)<<not implemented>> 
(10. Patch Appointment by Appointment Identifier)<<not implemented>> 
(11. Cancel Appointment)<<not implemented>> 
(12. Retrieve Workorder by Workorder Identifier)
(13. Retrieve Incident List)
(14. Retrieve Incident by Incident Identifier)
(15. Register for Event Notifications)
(16. Send Ticket Notification)
(17. Send Incident Notification)
(18. Register for Appointment Notifications)<<not implemented>> 
(19. Send Appointment Notification)<<not implemented>> 

Buyer --> (1. Create Ticket)
Buyer --> (2. Retrieve Ticket List)
Buyer --> (3. Retrieve Ticket by Ticket Identifier)
Buyer --> (4. Patch Ticket by Ticket Identifier)
Buyer --> (5. Cancel Ticket by Ticket Identifier)
Buyer --> (6. Respond to Ticket Clearance Notification)
Buyer --> (7.	Search Appointment Timeslot)
Buyer --> (8.	Create Appointment)
Buyer --> (9.	Retrieve Appointment by Appointment Identifier)
Buyer --> (10. Patch Appointment by Appointment Identifier)
Buyer --> (11. Cancel Appointment)
Buyer --> (12. Retrieve Workorder by Workorder Identifier)
Buyer --> (13. Retrieve Incident List)
Buyer --> (14. Retrieve Incident by Incident Identifier)
Buyer --> (15. Register for Event Notifications)
Buyer --> (18. Register for Appointment Notifications)

(16. Send Ticket Notification) <-- Seller
(17. Send Incident Notification)  <-- Seller
(19. Send Appointment Notification) <-- Seller


@enduml
