@startuml

hide footbox

participant Buyer
participant Seller


entity "Trouble Ticket" as TT
activate TT

autonumber

note over TT: Trouble Tickect in `inProgress` status

...

Seller -> TT: (resolves the Issue)
TT -> TT: status: resolved

TT -> Buyer: POST troubleTicketStatusChangeEvent
TT -> Buyer: POST troubleTicketResolvedEvent

alt Buyer accepts
  Buyer -> Seller : POST /troubleTicket/{{id}}/close
  Seller -> TT: (closes the Ticket)
  TT -> TT: status: closed
else Buyer rejects
  Buyer -> Seller : POST /troubleTicket/{{id}}/reopen
  Seller -> TT: (reopens the Ticket)
  TT -> TT: status: reopened
end

TT -> Buyer: POST troubleTicketStatusChangeEvent



@enduml