@startuml

class AttachmentValue {

    author*: string
    creationDate*: date-time
    description: string
    mimeType: string
    name*: string
    source*: MEFBuyerSellerType
    url*: string
}

AttachmentValue *--> MEFByteSize : size



class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit



class MEFByteSize {

    amount: float
    units: DataSizeUnit
}




class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}




class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}
class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress

class IssueRelationship {

    @referredType*: string
    creationDate*: date-time
    description*: string
    href: string
    id*: string
    relationshipType*: string
    source*: MEFBuyerSellerType
}



class TroubleTicket_Update {

    externalId: string
    issueStartDate: date-time
    observedImpact*: MEFObservedImpactType
    priority: TroubleTicketPriorityType
    severity: TroubleTicketSeverityType
}

TroubleTicket_Update *-->"*" AttachmentValue : attachment
TroubleTicket_Update *-->"*" Note : note
TroubleTicket_Update *-->"*" RelatedContactInformation : relatedContactInformation
TroubleTicket_Update *-->"*" IssueRelationship : relatedIssue



@enduml
