@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class IncidentEvent {

    eventType*: IncidentEventType
}
Event <|-- IncidentEvent

IncidentEvent *-->"1" IncidentEventPayload : event



class Event {

    eventId*: string
    eventTime*: date-time
}



class IncidentEventPayload {

    sellerId: string
    id*: string
    href: string
    buyerId: string
}



class TroubleTicketEventPayload {

    sellerId: string
    id*: string
    href: string
    buyerId: string
}



enum IncidentEventType {

    incidentCreatedEvent
    incidentAttributeValueChangeEvent
    incidentClosedEvent
    incidentStatusChangeEvent
}
class TroubleTicketEvent {

    eventType*: TroubleTicketEventType
}
Event <|-- TroubleTicketEvent

TroubleTicketEvent *-->"1" TroubleTicketEventPayload : event


enum TroubleTicketEventType {

    troubleTicketAttributeValueChangeEvent
    troubleTicketInformationRequiredEvent
    troubleTicketResolvedEvent
    troubleTicketStatusChangeEvent
}
@enduml
