@startjson
{
  "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
  "listOfCosNames": ["low"],
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeDuration": "<<skipped>>",
      "startTime": "<<skipped>>"
    }
  ],
  "maximumFrameSize": 1522,
  "evcEndPointA": {
    "identifier": "NewYork_UNI-EP1",
    "other": "<<skipped>>"
  },
  "evcEndPointZ": {
    "identifier": "Washington_UNI-EP1",
    "other": "<<skipped>>"
  }
}
@endjson