@startjson
#highlight "productOfferingQualificationItem" / "0"/ "action"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "id"
#highlight "productOfferingQualificationItem" / "1"/ "action"
#highlight "productOfferingQualificationItem" / "1"/ "product" / "id"

#highlight "productOfferingQualificationItem" / "1"/ "qualificationItemRelationship"
#highlight "productOfferingQualificationItem" / "1"/ "qualificationItemRelationship" / "0"
#highlight "productOfferingQualificationItem" / "1"/ "qualificationItemRelationship" / "0" / "relationshipType"
#highlight "productOfferingQualificationItem" / "1"/ "qualificationItemRelationship" / "0" / "id"
#highlight "productOfferingQualificationItem" / "1"/ "product" / "productRelationship"
#highlight "productOfferingQualificationItem" / "1"/ "product" / "productRelationship" / "0" 
#highlight "productOfferingQualificationItem" / "1"/ "product" / "productRelationship" / "0" / "relationshipType"
#highlight "productOfferingQualificationItem" / "1"/ "product" / "productRelationship" / "0" / "id"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "place" / "0"/ "@type"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "place" / "0"/ "id"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "place" / "0"/ "role"

{
  "instantSyncQualification": false,
  "externalId": "BuyerPoq-00007",
  "provideAlternative": false,
  "requestedPOQCompletionDate": "2023-10-12T00:00:00Z",
  "projectId": "BuyerProject7",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "PhiladelphiaAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      },
      "relatedContactInformation": [
        {
          "number": "+12-345-678-90",
          "emailAddress": "LocationContact@example.com",
          "role": "locationContact",
          "name": "Location Contact"
        }
      ]
    },
    {
      "id": "item-002",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-001"
        }
      ],
      "product": {
        "productRelationship": [
          {
            "relationshipType": "ENDPOINT_OF_EVC",
            "id": "EVP-LAN"
          }
        ],
        "productOffering": {
          "id": "000375"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evplan-evc-endpoint:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }  
    }
  ]
}

@endjson