@startjson

#highlight "evcEndPointA" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "evcEndPointMap" / "0" / "vlanId" 
#highlight "evcEndPointA" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "evcEndPointMap" / "0" / "vlanId" / "2"
#highlight "evcEndPointZ" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "evcEndPointMap" / "0" / "vlanId"
#highlight "evcEndPointZ" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "evcEndPointMap" / "0" / "vlanId" / "2"


{
    "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
    "cTagPcpPreservation": "TRUE",
    "cTagDeiPreservation": "FALSE",
    "frameDisposition": {
      "broadcast": "DELIVER_UNCONDITIONALLY",
      "unicast": "DELIVER_CONDITIONALLY",
      "multicast": "DELIVER_UNCONDITIONALLY"
      },
    "listOfCosNames": ["low"],
    "availableMegLevel": "6",
    "carrierEthernetSls": [
      {
        "slsCosNameEntry": "<<skipped>>",
        "timeInterval": {
          "longDurationUnits": "MONTH",
          "longDurationValue": 1
        },
        "startTime": "2021-09-01T00:00:00Z"
      }
    ],
    "maximumFrameSize": 1522,
    "evcEndPointA": {
    "identifier": "NewYork_UNI-EP1",
    "subscriberMegMip": "ENABLED",
    "egressMap": [
              {
                "evcEgressMapEntries": [
                  {
                    "cosName": "low",
                    "pcpYellow": 3,
                    "deiYellow": 1,
                    "deiGreen": 0,
                    "pcpGreen": 3
                  }
                ]
              }
            ],
            "colorMap": {
              "mapType": "DEI"
            },
            "ingressClassOfServiceMap": {
              "mapType": "ENDPOINT",
              "map_M": "low",
              "l2cp_P": []
            },
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeValue": 0,
                    "dataSizeUnits": "KBYTES"
                  },
                  "couplingFlag": true,
                  "envelopeId": "env1",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeValue": 40,
                    "dataSizeUnits": "KBYTES"
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "evcEndPointMap": [
              {
                "vlanId": [1, 2, 3],
                "vlanType": "LIST"
              }
            ],
            "sourceAddressMacLimit": [],
            "egressBandwidthProfilePerClassofServiceName": []
                }
              }
            ]
          },
          "evcEndPointZ": {
            "identifier": "Washington_UNI-EP1",
            "subscriberMegMip": "ENABLED",
            "egressMap": [
              {
                "evcEgressMapEntries": [
                  {
                    "cosName": "low",
                    "pcpYellow": 3,
                    "deiYellow": 1,
                    "deiGreen": 0,
                    "pcpGreen": 3
                  }
                ]
              }
            ],
            "colorMap": {
              "mapType": "DEI"
            },
            "ingressClassOfServiceMap": {
              "mapType": "ENDPOINT",
              "map_M": "low",
              "l2cp_P": []
            },
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeValue": 0,
                    "dataSizeUnits": "KBYTES"
                  },
                  "couplingFlag": true,
                  "envelopeId": "env1",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeValue": 40,
                    "dataSizeUnits": "KBYTES"
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "evcEndPointMap": [
                    {
                      "vlanType": "LIST",
                      "vlanId": [1, 2, 3]
                    }
            ],
            "sourceAddressMacLimit": [],
            "egressBandwidthProfilePerClassofServiceName": []
                }
              }
            ]
          }
}
@endjson