@startjson
#highlight "productOrderItem" / "0"/"productOrderItemRelationship"/"0"/"relationshipType"
#highlight "productOrderItem" / "0"/"productOrderItemRelationship"/"0"/"id"
#highlight "productOrderItem" / "0"/"productOrderItemRelationship"/"1"/"relationshipType"
#highlight "productOrderItem" / "0"/"productOrderItemRelationship"/"1"/"id"

#highlight "productOrderItem" / "0"/"product"/"productConfiguration"/"@type"
#highlight "productOrderItem" / "1"/"product"/"productConfiguration"/"@type"
#highlight "productOrderItem" / "2"/"product"/"productConfiguration"/"@type"

{
  "externalId": "BuyerOrder-00005",
  "projectId": "BuyerProject5",
  "requestedCompletionDate": "2023-11-04T23:00:00Z",
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "productOrderContact",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "productOrderItem": [
    {
      "action": "add",
      "expediteIndicator": false,
      "id": "item-001",
      "productOrderItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI_A",
          "id": "item-002"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI_Z",
          "id": "item-003"
        }
      ],
      "requestedItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "yearly subscription"
      },
      "relatedContactInformation": "<<skipped>>",
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001",
        "billingContact": {
          "number": "+12-345-678-90",
          "emailAddress": "bill@mef.com",
          "role": "billingContact",
          "organization": "MEF",
          "name": "Bill Contact",
          "numberExtension": "string"
        }
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "requestedCompletionDate": "2021-11-04T23:00:00Z",
      "product": {
        "productOffering": {
          "id": "000173"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-002",
      "action": "add",
      "requestedItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "yearly subscription"
      },
      "expediteIndicator": false,
      "requestedCompletionDate": "2021-11-25T23:00:00Z",
      "relatedContactInformation": "<<skipped>>",
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001",
        "billingContact": {
          "number": "+12-345-678-90",
          "emailAddress": "bill@mef.com",
          "role": "billingContact",
          "organization": "MEF",
          "name": "Bill Contact",
          "numberExtension": "string"
        }
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "NewYorkAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-003",
      "action": "add",
      "requestedItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "yearly subscription"
      },
      "expediteIndicator": false,
      "requestedCompletionDate": "2021-11-25T23:00:00Z",
      "relatedContactInformation": "<<skipped>>",
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001",
        "billingContact": {
          "number": "+12-345-678-90",
          "emailAddress": "bill@mef.com",
          "role": "billingContact",
          "organization": "MEF",
          "name": "Bill Contact",
          "numberExtension": "string"
        }
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "WashingtonAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    }
  ]
}


@endjson