@startjson
#highlight "cTagPcpPreservation"
#highlight "cTagDeiPreservation"

{
  "@type": "urn:mef:lso:spec:cantata-sonata:evplan-evc:v1.0.0:all",
  "cTagPcpPreservation": "ENABLED",
  "cTagDeiPreservation": "DISABLED",
  "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "listOfCosNames": ["low"],
  "availableMegLevel": "6",
  "carrierEthernetSls": "<<skipeed>>",
  "maximumFrameSize": 1522
}
@endjson