@startjson

#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" 
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" 
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "relationshipType" 
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "id" 

#highlight "productOfferingQualificationItem" / "0" / "product" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productRelationship" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productRelationship" / "0" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productRelationship" / "0" / "relationshipType"
#highlight "productOfferingQualificationItem" / "0" / "product" / "productRelationship" / "0" / "id"



{
  "instantSyncQualification": false,
  "externalId": "BuyerPoq-00003b",
  "provideAlternative": false,
  "requestedPOQCompletionDate": "2023-10-12T00:00:00Z",
  "projectId": "BuyerProject3b",
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI_Z",
          "id": "item-002"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000173"
        },
        "productRelationship": [
          {
            "relationshipType": "CONNECTS_TO_UNI_A",
            "id": "NewYork_UNI"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evpl-evc:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-002",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "SanFranciscoAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    }
  ]
}

@endjson