@startjson

#highlight "productOfferingQualificationItem" / "5" / "qualificationItemRelationship" 
#highlight "productOfferingQualificationItem" / "5" / "qualificationItemRelationship" / "0" / "relationshipType" 
#highlight "productOfferingQualificationItem" / "6" / "qualificationItemRelationship" 
#highlight "productOfferingQualificationItem" / "6" / "qualificationItemRelationship" / "0" / "relationshipType" 
#highlight "productOfferingQualificationItem" / "7" / "qualificationItemRelationship" 
#highlight "productOfferingQualificationItem" / "7" / "qualificationItemRelationship" / "0" / "relationshipType" 
#highlight "productOfferingQualificationItem" / "8" / "qualificationItemRelationship" 
#highlight "productOfferingQualificationItem" / "8" / "qualificationItemRelationship" / "0" / "relationshipType" 

{
  "instantSyncQualification": false,
  "externalId": "BuyerPoq-00002e",
  "provideAlternative": false,
  "requestedPOQCompletionDate": "2023-10-12T00:00:00Z",
  "projectId": "BuyerProject2e",
  "relatedContactInformation": "<<skipped>>",
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000273"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:eptree-evc:v1.0.0:all",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-002",
      "action": "add",
      "relatedContactInformation": "<<skipped>>",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "DenverAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-003",
      "action": "add",
      "relatedContactInformation": "<<skipped>>",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "OklahomaAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-004",
      "action": "add",
      "relatedContactInformation": "<<skipped>>",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "HoustonAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-005",
      "action": "add",
      "relatedContactInformation": "<<skipped>>",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "MiamiAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-006",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "ROOT_ENDPOINT_OF_EVC",
          "id": "item-001"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-002"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000275"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:eptree-evc-endpoint:v1.0.0:all",
          "identifier": "Denver_UNI-EP1_R",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-007",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "LEAF_ENDPOINT_OF_EVC",
          "id": "item-001"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-003"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000275"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:eptree-evc-endpoint:v1.0.0:all",
          "identifier": "Oklahoma_UNI-EP1_L",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-008",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "LEAF_ENDPOINT_OF_EVC",
          "id": "item-001"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-004"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000275"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:eptree-evc-endpoint:v1.0.0:all",
          "identifier": "Houston_UNI-EP1_L",
          "others": "<<skipped>>"
        }
      }
    },
    {
      "id": "item-009",
      "action": "add",
      "qualificationItemRelationship": [
        {
          "relationshipType": "LEAF_ENDPOINT_OF_EVC",
          "id": "item-001"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-005"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000275"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:eptree-evc-endpoint:v1.0.0:all",
          "identifier": "Miami_UNI-EP1_L",
          "others": "<<skipped>>"
        }
      }
    }
  ]
}

@endjson