@startjson

#highlight "quoteItem" / "0"/"quoteItemRelationship"/"0"/"relationshipType"
#highlight "quoteItem" / "0"/"quoteItemRelationship"/"0"/"id"
#highlight "quoteItem" / "0"/"quoteItemRelationship"/"1"/"relationshipType"
#highlight "quoteItem" / "0"/"quoteItemRelationship"/"1"/"id"

#highlight "quoteItem" / "0"/"product"/"productConfiguration"/"@type"
#highlight "quoteItem" / "1"/"product"/"productConfiguration"/"@type"
#highlight "quoteItem" / "2"/"product"/"productConfiguration"/"@type"

{
  "requestedQuoteCompletionDate": "2023-10-28T22:00:00Z",
  "externalId": "BuyerQuote-00004",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProject4",
  "instantSyncQuote": false,
  "quoteItem": [
    {
      "id": "item-001",
      "action": "add",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "quoteItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI_A",
          "id": "item-002"
        },
        {
          "relationshipType": "CONNECTS_TO_UNI_Z",
          "id": "item-003"
        }
      ],
      "product": {
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
          "other": "<<skipped>>"
        }
      },
      "other": "<<skipped>>"
    },
    {
      "action": "add",
      "id": "item-002",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "NewYorkAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      },
      "other": "<<skipped>>"
    },
    {
      "action": "add",
      "id": "item-003",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "WashingtonAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      },
      "other": "<<skipped>>"
    }
  ],
  "other": "<<skipped>>"
}


@endjson