@startjson
#highlight "evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"
#highlight "evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"

#highlight "evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"
#highlight "evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"
#highlight "evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"
#highlight "evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"

#highlight "evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"/"irValue"
#highlight "evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"/"irValue"
#highlight "evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"/"irValue"
#highlight "evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"/"irValue"

{
  "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
  "listOfCosNames": ["low"],
  "availableMegLevel": "6",
  "carrierEthernetSls": "<<skipped>>",
  "maximumFrameSize": 1522,
  "evcEndPointA": {
    "identifier": "NewYork_UNI-EP1",
    "subscriberMegMip": "ENABLED",
    "egressMap": [
      {
        "evcEgressMapEntries": [
          {
            "cosName": "low",
            "pcpYellow": 3,
            "deiYellow": 1,
            "deiGreen": 0,
            "pcpGreen": 3
          }
        ]
      }
    ],
    "colorMap": {
      "mapType": "DEI"
    },
    "ingressClassOfServiceMap": {
      "mapType": "ENDPOINT",
      "map_M": "low",
      "l2cp_P": []
    },
    "ingressBandwidthProfilePerClassOfServiceName": [
      {
        "classOfServiceName": "low",
        "bwpFlow": {
          "cir": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "cirMax": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "eir": {
            "irValue": 100,
            "irUnits": "MBPS"
          },
          "eirMax": {
            "irValue": 100,
            "irUnits": "MBPS"
          },
          "envelopeRank": 1,
          "cbs": {
            "dataSizeValue": 0,
            "dataSizeUnits": "KBYTES"
          },
          "couplingFlag": true,
          "envelopeId": "env1",
          "tokenRequestOffset": 0,
          "ebs": {
            "dataSizeValue": 40,
            "dataSizeUnits": "KBYTES"
          },
          "colorMode": "COLOR_BLIND"
        }
      }
    ]
  },
  "evcEndPointZ": {
    "identifier": "Washington_UNI-EP1",
    "subscriberMegMip": "ENABLED",
    "egressMap": [
      {
        "evcEgressMapEntries": [
          {
            "cosName": "low",
            "pcpYellow": 3,
            "deiYellow": 1,
            "deiGreen": 0,
            "pcpGreen": 3
          }
        ]
      }
    ],
    "colorMap": {
      "mapType": "DEI"
    },
    "ingressClassOfServiceMap": {
      "mapType": "ENDPOINT",
      "map_M": "low",
      "l2cp_P": []
    },
    "ingressBandwidthProfilePerClassOfServiceName": [
      {
        "classOfServiceName": "low",
        "bwpFlow": {
          "cir": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "cirMax": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "eir": {
            "irValue": 100,
            "irUnits": "MBPS"
          },
          "eirMax": {
            "irValue": 100,
            "irUnits": "MBPS"
          },
          "cbs": {
            "dataSizeValue": 0,
            "dataSizeUnits": "KBYTES"
          },
          "couplingFlag": true,
          "envelopeId": "env1",
          "tokenRequestOffset": 0,
          "ebs": {
            "dataSizeValue": 40,
            "dataSizeUnits": "KBYTES"
          },
          "colorMode": "COLOR_BLIND"
        }
      }
    ]
  }
}

@endjson