@startjson
{
  "@type": "urn:mef:lso:spec:cantata-sonata:eplan-evc:v1.0.0:all",
  "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "listOfCosNames": ["low"],
  "availableMegLevel": "6",
  "carrierEthernetSls": "<<skipped>>",
  "maximumFrameSize": 1522
}
@endjson