---
"$schema": http://json-schema.org/draft-07/schema#
title: 
    MEF LSO Sonata - Carrier Ethernet ENNI Service Attributes
    # MEF Forum - Date: 20210615  Edit-level: 221
    # File: carrierEthernet/carrierEthernetEnniSpSo/inventory/carrierEthernetEnniServiceAttributes.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # © MEF Forum 2021. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
definitions:
    EnniService:
        type: object
        description:  >-
            For each instance of an ENNI, there are multiple sets of ENNI
            Service Attributes. The value for each ENNI Service Attribute in
            a set for an Operator CEN is specific to a SP/SO that is using
            the ENNI per Section 8.11 of MEF 26.2. Each such value is agreed
            to by the SP/SO and the Operator.
        properties:
            sVlanIdControl:
                description:  >-
                    MEF 26.2 sec. 13.2 - The value of the S-VLAN ID Control Service
                    Attribute is FULL or PARTIAL. When the value is FULL, the Operator
                    can support only a single SP/SO at the ENNI. In other words, S-VLAN
                    IDs at the ENNI can only be mapped to OVC End Points for a single
                    SP/SO. When the value is PARTIAL, there can be multiple SP/SOs
                    using the ENNI and different S-VLAN IDs can be mapped to OVC End
                    Points for different SP/SOs.
                type: string
                enum:
                    - "FULL"
                    - "PARTIAL"
            maximumNumberOfOvcs:
                description:  >-
                    MEF 26.2 sec. 13.3 - The value of the Maximum Number of OVCs
                    Service Attribute is a strictly positive integer. It provides an
                    upper bound on the number of OVCs that the Operator will support
                    at the ENNI for the SP/SO.
                type: integer
                minimum: 1
            maximumNumberOfOvcEndPointsPerOvc:
                description:  >-
                    MEF 26.2 sec. 13.4 - Usually each OVC has a single End Point
                    at the ENNI but with hairpin switching an OVC can have multiple.
                    This Service Attribute sets the limit on the number of End Points
                    an OVC can have at the ENNI.
                type: integer
                minimum: 1
            tokenShare:
                description:  >-
                    MEF 26.2 sec. 13.5 - An attribute that indicates whether Bandwidth
                    Profile Envelopes containing more than one Bandwidth Profile Flow
                    are supported by the Service Provider at the ENNI.
                # See additional validation notes in the Schema Guide
                $ref: "../../common/utilityClassesAndTypes.yaml#/definitions/EnabledDisabled"
            envelopes:
                description:  >-
                    MEF 26.2 sec. 13.6 - The Envelopes and Envelope Coupling Flag
                    values to which Bandwidth Profile Flows can be mapped. Value is
                    list of {envelopeID, couplingFlagForIndexZero}. Note: Envelopes
                    for the ENNI can also be specified at the OVC End Points associated
                    with the ENNI.
                type: array 
                minItems: 0
                uniqueItems: TRUE
                items:
                    $ref: "../../common/carrierEthernetBandwidthProfile.yaml#/definitions/Envelope"
        required:
            - sVlanIdControl
            - maximumNumberOfOvcs
            - maximumNumberOfOvcEndPointsPerOvc
            - tokenShare
            - envelopes

