---
"$schema": http://json-schema.org/draft-07/schema#
"$id": urn:mef:lso:spec:sonata:carrier-ethernet-enni-sp-so:v2.0.0:inventory
title: 
    MEF LSO Sonata - Carrier Ethernet ENNI SP SO (Inventory) Product Specification
    # MEF Forum - Date: 20210615  Edit-level: 221
    # File: carrierEthernet/carrierEthernetEnniSpSo/inventory/carrierEthernetEnniSpSo.yaml
    #
    # ---------------------
    # Disclaimer
    # 
    # © MEF Forum 2021. All Rights Reserved.
    # 
    # The information in this publication is freely available for reproduction
    # and use by any recipient and is believed to be accurate as of its
    # publication date. Such information is subject to change without notice
    # and MEF Forum (MEF) is not responsible for any errors. MEF does not
    # assume responsibility to update or correct any information in this
    # publication. No representation or warranty, expressed or implied, is
    # made by MEF concerning the completeness, accuracy, or applicability of
    # any information contained herein and no liability of any kind shall be
    # assumed by MEF as a result of reliance upon such information.
    # 
    # The information contained herein is intended to be used without
    # modification by the recipient or user of this document. MEF is not
    # responsible or liable for any modifications to this document made by any
    # other party.
    # 
    # The receipt or any use of this document or its contents
    # does not in any way create, by implication or otherwise:
    # 
    # a) any express or implied license or right to or under any patent,
    # copyright, trademark or trade secret rights held or claimed by any MEF
    # member which are or may be associated with the ideas, techniques,
    # concepts or expressions contained herein; nor
    # 
    # b) any warranty or representation that any MEF members will announce
    # any product(s) and/or service(s) related thereto, or if such
    # announcements are made, that such announced product(s) and/or service(s)
    # embody any or all of the ideas, technologies, or concepts contained
    # herein; nor
    # 
    # c) any form of relationship between any MEF member and the recipient
    # or user of this document.
    # 
    # Implementation or use of specific MEF standards, specifications, or
    # recommendations will be voluntary, and no Member shall be obliged to
    # implement them by virtue of participation in MEF Forum. MEF is a
    # non-profit international organization to enable the development and
    # worldwide adoption of agile, assured and orchestrated network services.
    # MEF does not, expressly or otherwise, endorse or promote any specific
    # products or services.
    # ---------------------
    #
description:  >-
    This class is the composition of the ENNI Service Attributes,
    ENNI Common Attributes, and Operator Multilateral Attributes. The
    ENNI Common Attributes and Operator Multilateral Attributes are
    all optional since it is only required to share these if the SVLAN
    Control Service Attribute has the value FULL.
allOf:
    # The value for each ENNI Service Attribute is specific to a SP/SO that is using the ENNI
    - $ref: "carrierEthernetEnniServiceAttributes.yaml#/definitions/EnniService"
    # Technical details that need to be agreed to by the Network Operators connected by the ENNI
    - $ref: "carrierEthernetEnniCommon.yaml#/definitions/EnniCommon"
    # Operator Multilateral Attributes have the same value for all SP/SOs using that ENNI
    - $ref: "operatorMultilateralAttributes.yaml#/definitions/OperatorMultilateral"

