//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 * 
 * <p>Java class for AlternateProductProposal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlternateProductProposal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceabilityDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productSpecificationRef" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}ProductSpecificationRef" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlternateProductProposal", propOrder = {
    "type",
    "serviceabilityDate",
    "productSpecificationRef"
})
public class AlternateProductProposalEntity
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String type;
    protected String serviceabilityDate;
    protected ProductSpecificationRefEntity productSpecificationRef;


    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the serviceabilityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceabilityDate() {
        return serviceabilityDate;
    }

    /**
     * Sets the value of the serviceabilityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceabilityDate(String value) {
        this.serviceabilityDate = value;
    }

    /**
     * Gets the value of the productSpecificationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSpecificationRefEntity }
     *     
     */
    public ProductSpecificationRefEntity getProductSpecificationRef() {
        return productSpecificationRef;
    }

    /**
     * Sets the value of the productSpecificationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSpecificationRefEntity }
     *     
     */
    public void setProductSpecificationRef(ProductSpecificationRefEntity value) {
        this.productSpecificationRef = value;
    }



}
