//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 * 
 * <p>Java class for GeographicLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographicLocation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="geographicPoint" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}GeographicPoint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicLocation", propOrder = {
    "geographicPoint"
})
public class GeographicLocationEntity
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected GeographicPointEntity geographicPoint;


    /**
     * Gets the value of the geographicPoint property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicPointEntity }
     *     
     */
    public GeographicPointEntity getGeographicPoint() {
        return geographicPoint;
    }

    /**
     * Sets the value of the geographicPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicPointEntity }
     *     
     */
    public void setGeographicPoint(GeographicPointEntity value) {
        this.geographicPoint = value;
    }


}
