//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productSpecificationRef" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}ProductSpecificationRef"/&gt;
 *         &lt;element name="productRelationship" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}ProductRelationship" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="relatedParty" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}RelatedParty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="geographicAddress" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}GeographicAddress" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="geographicLocation" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}GeographicLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="site" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}Site" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "id",
    "type",
    "productSpecificationRef",
    "productRelationship",
    "relatedParty",
    "geographicAddress",
    "geographicLocation",
    "site"
})
public class ProductEntity
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String id;
    protected String type;
    @JsonIgnore
    protected String productSpecificationRef;
    protected List<ProductRelationshipEntity> productRelationship;
    protected List<RelatedPartyEntity> relatedParty;
    protected List<GeographicAddressEntity> geographicAddress;
    protected List<GeographicLocationEntity> geographicLocation;
    protected List<SiteEntity> site;


    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the productSpecificationRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSpecificationRefEntity }
     *     
     */
    public String getProductSpecificationRef() {
        return productSpecificationRef;
    }

    /**
     * Sets the value of the productSpecificationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSpecificationRefEntity }
     *     
     */
    public void setProductSpecificationRef(String value) {
        this.productSpecificationRef = value;
    }

    /**
     * Gets the value of the productRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductRelationshipEntity }
     * 
     * 
     */
    public List<ProductRelationshipEntity> getProductRelationship() {
        if (productRelationship == null) {
            productRelationship = new ArrayList<ProductRelationshipEntity>();
        }
        return this.productRelationship;
    }

    /**
     * 
     * 
     */
    public void setProductRelationship(List<ProductRelationshipEntity> productRelationship) {
        this.productRelationship = productRelationship;
    }

    /**
     * Gets the value of the relatedParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPartyEntity }
     * 
     * 
     */
    public List<RelatedPartyEntity> getRelatedParty() {
        if (relatedParty == null) {
            relatedParty = new ArrayList<RelatedPartyEntity>();
        }
        return this.relatedParty;
    }

    /**
     * 
     * 
     */
    public void setRelatedParty(List<RelatedPartyEntity> relatedParty) {
        this.relatedParty = relatedParty;
    }

    /**
     * Gets the value of the geographicAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geographicAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeographicAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeographicAddressEntity }
     * 
     * 
     */
    public List<GeographicAddressEntity> getGeographicAddress() {
        if (geographicAddress == null) {
            geographicAddress = new ArrayList<GeographicAddressEntity>();
        }
        return this.geographicAddress;
    }

    /**
     * 
     * 
     */
    public void setGeographicAddress(List<GeographicAddressEntity> geographicAddress) {
        this.geographicAddress = geographicAddress;
    }

    /**
     * Gets the value of the geographicLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geographicLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeographicLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeographicLocationEntity }
     * 
     * 
     */
    public List<GeographicLocationEntity> getGeographicLocation() {
        if (geographicLocation == null) {
            geographicLocation = new ArrayList<GeographicLocationEntity>();
        }
        return this.geographicLocation;
    }

    /**
     * 
     * 
     */
    public void setGeographicLocation(List<GeographicLocationEntity> geographicLocation) {
        this.geographicLocation = geographicLocation;
    }

    /**
     * Gets the value of the site property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the site property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SiteEntity }
     * 
     * 
     */
    public List<SiteEntity> getSite() {
        if (site == null) {
            site = new ArrayList<SiteEntity>();
        }
        return this.site;
    }

    /**
     * 
     * 
     */
    public void setSite(List<SiteEntity> site) {
        this.site = site;
    }



}
