@startuml

class InternetAccessServiceAccessInterfaceType {

    resiliency*: InternetAccessResiliency
}
InternetAccessServiceAccessInterfaceType *-->"1..*" InternetAccessPhysicalInterface : physicalInterface

class InternetAccessPhysicalInterface {

    physicalLayer*: SaiEthernetPhysicalLayer
    connectorType*: ConnectorType
}


enum InternetAccessResiliency {

    NONE
    ALL_ACTIVE
    2_LINK_ACTIVE_STANDBY
    OTHER
}
enum ConnectorType {

    RJ45
    SC
    LC
    OTHER
}

enum SaiEthernetPhysicalLayer {

    10BASE-CX4
    10BASE-ER/EW
    10BASE-FL
    10BASE-LR/LW
    10BASE-LX4
    10BASE-SR/SW
    10BASE-T
    10GBASE-CX4
    10GBASE-ER/EW
    10GBASE-LR/LW
    10GBASE-LX4
    10GBASE-SR/SW
    10GBASE-T
    1000BASE-BX10
    1000BASE-LX
    1000BASE-LX10
    1000BASE-SX
    1000BASE-T
    100BASE-BX10
    100BASE-FX
    100BASE-LX10
    100BASE-SR10
    100BASE-SX
    100BASE-TX
    100GBASE-CR1
    100GBASE-CR10
    100GBASE-CR2
    100GBASE-CR4
    100GBASE-DR
    100GBASE-ER4
    100GBASE-FR1
    100GBASE-LR1
    100GBASE-LR4
    100GBASE-SR2
    100GBASE-SR4
    100GBASE-ZR
    200GBASE-CR2
    200GBASE-CR4
    200GBASE-DR4
    200GBASE-ER4
    200GBASE-FR4
    200GBASE-LR4
    200GBASE-SR4
    25GBASE-CR
    25GBASE-ER
    25GBASE-LR
    25GBASE-SR
    25GBASE-T
    2.5GBASE-T
    40GBASE-CR4
    40GBASE-ER4
    40GBASE-FR
    40GBASE-LR4
    40GBASE-SR4
    40GBASE-T
    400GBASE-DR4
    400GBASE-ER8
    400GBASE-FR4
    400GBASE-FR8
    400GBASE-LR4-6
    400GBASE-LR8
    400GBASE-SR16
    400GBASE-SR4
    400GBASE-SR4.2
    400GBASE-SR8
    50GBASE-CR
    50GBASE-ER
    50GBASE-FR
    50GBASE-LR
    50GBASE-SR
    5GBASE-T
}
@enduml