@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}


class InternetAccessFeatureAssistance {

    assistanceLevel*: InternetAccessAssistanceLevel
    simpleRequestsPerMonth: integer
    complexRequestsPerMonth: integer
}
InternetAccessFeature <|-- InternetAccessFeatureAssistance



class InternetAccessFeatureCloudPrioritization {

    cloudServiceProvider*: string[]
}
InternetAccessFeature <|-- InternetAccessFeatureCloudPrioritization



class InternetAccessFeatureDedicatedFirewall {

    firewallCapability*: InternetAccessFirewallCapability
}
InternetAccessFeature <|-- InternetAccessFeatureDedicatedFirewall



class InternetAccessFeatureDns {

    searchDomain: string[]
}
InternetAccessFeature <|-- InternetAccessFeatureDns


class InternetAccessFeatureLayer3Resiliency {

    layer3Resiliency*: InternetAccessLayer3Resiliency
}
InternetAccessFeature <|-- InternetAccessFeatureLayer3Resiliency



class InternetAccessFeatureMobileBackup {

}
InternetAccessFeature <|-- InternetAccessFeatureMobileBackup

InternetAccessFeatureMobileBackup *-->"1" BiDirSimpleBandwidth : minimumExpectedBandwidth


class BiDirSimpleBandwidth {
    downstream: InformationRate
    upstream: InformationRate
}



class InternetAccessFeatureMonitoring {

    monitoringType*: InternetAccessMonitoringType
}
InternetAccessFeature <|-- InternetAccessFeatureMonitoring



class InternetAccessFeatureRouting {

    routingType*: InternetAccessRoutingType
}
InternetAccessFeature <|-- InternetAccessFeatureRouting

InternetAccessFeatureRouting *--> InternetAccessBgp : bgp
InternetAccessFeatureRouting *--> Static : static

class InternetAccessBgp {
    <<skipped>>
}

class Static {
    <<skipped>>

}


class InternetAccessFeatures {

}

InternetAccessFeatures *--> InternetAccessFeatureAssistance : assistance
InternetAccessFeatures *--> InternetAccessFeatureCloudPrioritization : cloudPrioritization
InternetAccessFeatures *--> InternetAccessFeature : ddosMitigation
InternetAccessFeatures *--> InternetAccessFeatureDedicatedFirewall : dedicatedFirewall
InternetAccessFeatures *--> InternetAccessFeatureDns : dns
InternetAccessFeatures *--> InternetAccessFeatureFacilityDiversity : facilityDiversity
InternetAccessFeatures *--> InternetAccessFeatureLayer3Resiliency : layer3Resiliency
InternetAccessFeatures *--> InternetAccessFeatureMobileBackup : mobileBackup
InternetAccessFeatures *--> InternetAccessFeatureMonitoring : monitoring
InternetAccessFeatures *--> InternetAccessFeature : performanceReporting
InternetAccessFeatures *--> InternetAccessFeatureRouting : routing
InternetAccessFeatures *--> InternetAccessFeature : snmpRead



@enduml
