@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}


class InternetAccessFeatureAssistance {

    assistanceLevel*: AssistanceLevel
    simpleRequestsPerMonth: integer
    complexRequestsPerMonth: integer
}
InternetAccessFeature <|-- InternetAccessFeatureAssistance

enum AssistanceLevel {

    SELF_MANAGED
    CO_MANAGED
    FULLY_MANAGED
}


@enduml
