@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}


class InternetAccessFeatureAssistance {

    assistanceLevel*: InternetAccessAssistanceLevel
    simpleRequestsPerMonth: integer
    complexRequestsPerMonth: integer
}
InternetAccessFeature <|-- InternetAccessFeatureAssistance

enum InternetAccessAssistanceLevel {

    SELF_MANAGED
    CO_MANAGED
    FULLY_MANAGED
}


@enduml
