@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureCloudPrioritization {

    cloudServiceProvider*: string[]
}
InternetAccessFeature <|-- InternetAccessFeatureCloudPrioritization



@enduml
