@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureDedicatedFirewall {

    firewallCapability*: InternetAccessFirewallCapability
}
InternetAccessFeature <|-- InternetAccessFeatureDedicatedFirewall

enum InternetAccessFirewallCapability {

    BASIC
    ADVANCED
}

@enduml
