@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureDedicatedFirewall {

    firewallType*: FirewallType
}
InternetAccessFeature <|-- InternetAccessFeatureDedicatedFirewall

enum FirewallType {

    BASIC
    COMPLEX
}

@enduml
