@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureDns {

    searchDomain: string[]
}
InternetAccessFeature <|-- InternetAccessFeatureDns



@enduml
