@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}


class InternetAccessFeatureFacilityDiversity {

    internetAccessRef: string
}
InternetAccessFeature <|-- InternetAccessFeatureFacilityDiversity



@enduml
