@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}


class InternetAccessFeatureLayer3Resiliency {

    layer3Resiliency*: Layer3Resiliency
}
InternetAccessFeature <|-- InternetAccessFeatureLayer3Resiliency


enum Layer3Resiliency {

    DUAL_ACCESS_ALL_ACTIVE
    DUAL_ACCESS_ACTIVE_STANDBY
    WIRELESS_BACKUP
}

@enduml
