@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureMonitoring {

    monitoringType*: InternetAccessMonitoringType
}
InternetAccessFeature <|-- InternetAccessFeatureMonitoring

enum InternetAccessMonitoringType {

    PROACTIVE
    REACTIVE
}

@enduml
