@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureMonitoring {

    monitoringType*: MonitoringType
}
InternetAccessFeature <|-- InternetAccessFeatureMonitoring

enum MonitoringType {

    PROACTIVE
    REACTIVE
}

@enduml
