@startuml



class InternetAccessFeature {

    isSupported*: boolean
    isEnabled*: boolean
}



class InternetAccessFeatureRouting {

    routingType*: InternetAccessRoutingType
}
InternetAccessFeature <|-- InternetAccessFeatureRouting

InternetAccessFeatureRouting *--> InternetAccessBgp : bgp
InternetAccessFeatureRouting *--> Static : static

enum InternetAccessRoutingType {

    BGP
    STATIC
}


class InternetAccessBgp {
    <<skipped>>
}
class Static {
    <<skipped>>
}


@enduml
