@startuml

class BiDirSimpleBandwidth {

}

BiDirSimpleBandwidth *-->"1" InformationRate : downstream
BiDirSimpleBandwidth *-->"1" InformationRate : upstream



class InformationRate {

    irValue: number
    irUnits: InformationRateUnits
}



enum InformationRateUnits {

    BPS
    KBPS
    MBPS
    GBPS
    TBPS
    PBPS
    EBPS
    ZBPS
    YBPS
}

@enduml
