@startuml


enum InternetAccessBillingModelType {

    FLAT
    BURSTABLE_PERCENTILE
    DATA_TRANSFER
}


class InternetAccessBillingModel {

    billingModelType*: InternetAccessBillingModelType
    billingModelPlanName*: string
}





@enduml
