@startuml
class InternetAccessLocalNetworkAddresses {

    lanAddressBlock: string
    dhcpStatus: EnabledDisabled
    dhcpStart: string
    dhcpEnd: string
    nat: string
}

InternetAccessLocalNetworkAddresses *-->"*" InternetAccessDhcpStaticListEntry : dhcpStaticList

class InternetAccessDhcpStaticListEntry {

    staticMACAddress: string
    staticIpAddress: string
}



@enduml
