@startuml
class InternetAccessPublicAddressesPrefixLength {

    ipv4*: InternetAccessIpv4PublicAddressesPrefixLength
    ipv6*: InternetAccessIpv6PublicAddressesPrefixLength
}


enum InternetAccessIpv4PublicAddressesPrefixLength {

    /24
    /25
    /26
    /27
    /28
    /29
    /30
    /31
    /32
    NONE
}
enum InternetAccessIpv6PublicAddressesPrefixLength {

    /96
    /100
    /104
    /108
    /112
    /116
    /120
    /124
    /128
    NONE
}
@enduml
