@startuml

class InternetAccessTransitAddresses {

    ipv4TransitAddressPrefixLength: InternetAccessIpv4TransitAddressPrefixLength
    ipv6TransitAddressPrefixLength: InternetAccessIpv6TransitAddressPrefixLength
    ipv4TransitAddressBlock: string
    ipv6TransitAddressBlock: string
}


enum InternetAccessIpv4TransitAddressPrefixLength {

    /24
    /25
    /26
    /27
    /28
    /29
    /30
    /31
    /32
    NONE
}
enum InternetAccessIpv6TransitAddressPrefixLength {

    /120
    /124
    /128
    NONE
}
@enduml
