@startuml

class InternetAccessTransitAddresses {

    requestedIpv4TransitAddressPrefixLength: InternetAccessIpv4TransitAddressPrefixLength
    requestedIpv6TransitAddressPrefixLength: InternetAccessIpv6TransitAddressPrefixLength
    serviceProviderIpv4TransitAddress: string
    serviceProviderIpv6TransitAddress: string
}



enum InternetAccessIpv4TransitAddressPrefixLength {

    /24
    /25
    /26
    /27
    /28
    /29
    /30
    /31
    /32
    NONE
}
enum InternetAccessIpv6TransitAddressPrefixLength {

    /120
    /124
    /128
    NONE
}
@enduml
