@startuml

enum TicketStatusType {
   ACKNOWLEDGED
   IN_PROGRESS
   RESOLVED
   CLOSED
   PENDING
   CANCELLED
   CLEARANCE_REJECTED
}
enum TroubleSeverity {
   CRITICAL
   MAJOR
   MINOR
}
enum RequestedStatusType {
   CANCELLED
   CLOSED
   CLEARANCE_REJECTED
}
enum PriorityType {
   CRITICAL
   HIGH
   MEDIUM
   LOW
   NA
}
enum TroubleType {
   INSTALLATION
   MAINTENANCE
   FAILURE
   ASSISTANCE
}

class ErrorRepresentation {
   code:int
   reason:string
   message:string
   status:int
   referenceError:string
   @type:string
   @schemaLocation:string
}

class Note {
   date:date
   author:string
   text:string
}

class RelatedObject {
   involvement:string
   reference:string
}

class TroubleTicket {
   id:string
   href:string
   externalId:string
   description:string
   creationDate:dateTime
   targetResolutionDate:dateTime
   resolutionDate:dateTime
   @baseType:string
   @type:string
   @schemaLocation:string
}
   TroubleTicket --> "0-1" TroubleSeverity : severity
   TroubleTicket --> "0-1" PriorityType : priority
   TroubleTicket --> "0-1" TroubleType : type
   TroubleTicket --> "0-1" TicketStatusType : status
   TroubleTicket --> "0-*" Note : note
   TroubleTicket --> "0-*" RelatedParty : relatedParty
   TroubleTicket --> "0-*" RelatedObject : relatedObject
   TroubleTicket --> "0-*" StatusChange : statusChange
   TroubleTicket --> "0-*" Attachment : attachment

class RelatedParty {
   id:string
   href:string
   @referredType:string
   role:string
   name:string
   emailAddress:string
   number:string
   numberExtension:string
}

class Hub {
   id:string
   query:string
   callback:string
}

class Attachment {
   id:string
   href:string
   name:string
   url:string
   @type:string
}

class StatusChange {
   statusValue:string
   statusChangeReason:string
   statusChangeDate:dateTime
}

class CreateTicket {
   externalId:string
   description:string
   @baseType:string
   @type:string
   @schemaLocation:string
}
   CreateTicket --> "0-1" TroubleSeverity : severity
   CreateTicket --> "0-1" TroubleType : type
   CreateTicket --> "0-1" PriorityType : priority
   CreateTicket --> "0-*" RelatedParty : relatedParty
   CreateTicket --> "0-*" RelatedObject : relatedObject
   CreateTicket --> "0-*" Note : note
   CreateTicket --> "0-*" Attachment : attachment

class UpdateTicket {
   externalId:string
   description:string
   @baseType:string
   @type:string
   @schemaLocation:string
}
   UpdateTicket --> "0-1" TroubleType : type
   UpdateTicket --> "0-1" RequestedStatusType : requestedStatus
   UpdateTicket --> "0-*" RelatedParty : relatedParty
   UpdateTicket --> "0-*" RelatedObject : relatedObject
   UpdateTicket --> "0-*" Note : note
   UpdateTicket --> "0-*" Attachment : attachment

class TicketSummary {
   id:string
   href:string
   creationDate:dateTime
   targetResolutionDate:dateTime
   resolutionDate:dateTime
}
   TicketSummary --> "0-1" TroubleSeverity : severity
   TicketSummary --> "0-1" TicketStatusType : status
   TicketSummary --> "0-1" PriorityType : priority
   TicketSummary --> "0-*" RelatedObject : relatedObject

@enduml