@startjson
#highlight "l2Technology"
#highlight "l2Technology" / "demux"
#highlight "ipv4ConnectionAddressing" 
#highlight "ipv6ConnectionAddressing" 

{
  "identifier": "UNIAL.Budapest.66.1.1",
  "connectionType": "POINT_TO_POINT",
  "l2Technology": {
    "demux": []
  },
  "mtu": 1500,
  "prefixDelegation": "DISABLED",
  "reservedVrids": [],
  "egressBwpEnvelope": [],
  "ingressBwpEnvelope": [],
  "ipv4ConnectionAddressing": [],
  "ipv6ConnectionAddressing": [
    {
      "ipv6AddressType": "DHCP"
    }
  ]
}
@endjson