@startjson
#highlight "ethernetPhysicalLink" 
#highlight "ethernetPhysicalLink" / "0"
#highlight "ethernetPhysicalLink" / "0" / "physicalLayer"

{
  "ethernetPhysicalLink": [
    {
      "identifier": "UNIALT.Budapest.66.1.1",
      "physicalLayer": "1000BASE_SX",
      "synchronousEthernet": "DISABLED",
      "connectorType": "SC",
      "gender": "SOCKET"
    }
  ],
  "ethernetLinkAggregation": null,
  "ethernetLinkOam": "DISABLED"
}
@endjson