@startjson
#highlight "listOfControlProtocols" 
#highlight "listOfControlProtocols" / "0"
#highlight "listOfControlProtocols" / "1"
#highlight "listOfControlProtocols" / "2"
#highlight "listOfControlProtocols" / "0" / "protocolName"
#highlight "listOfControlProtocols" / "1" / "protocolName"
#highlight "listOfControlProtocols" / "2" / "protocolName"

#highlight "ingressBandwidthProfileEnvelope"
#highlight "ingressBandwidthProfileEnvelope" / "cir" 
#highlight "ingressBandwidthProfileEnvelope" / "cir" / "irValue"
#highlight "ingressBandwidthProfileEnvelope" / "maxIr"
#highlight "ingressBandwidthProfileEnvelope" / "maxIr" / "irValue"


{
  "managementType": "SUBSCRIBER_MANAGED",
  "reversePathForwarding": "ENABLED",
  "listOfControlProtocols": [
    {
      "addressing": "SP_OPERATOR_ADDRESSES",
      "protocolName": "ICMP",
      "reference": ["RFC 792"]
    },
    {
      "addressing": "ANY",
      "protocolName": "DHCP",
      "reference": ["RFC 2131", "RFC 2132"]
    },
    {
      "addressing": "ANY",
      "protocolName": "DHCPv6",
      "reference": ["RFC 8415"]
    }
  ],
  "ingressBandwidthProfileEnvelope": {
    "cir": {
      "irValue": 0,
      "irUnits": "MBPS"
    },
    "maxIr": {
      "irValue": 100,
      "irUnits": "MBPS"
    },
    "tE": 10,
    "burstBehavior": "OPTIMIZE_THROUGHPUT"
  }
}
@endjson