@startjson
#highlight "l2Technology"
#highlight "l2Technology" / "demux"
#highlight "l2Technology" / "demux" / "utpt" 
#highlight "ipv4ConnectionAddressing" 
#highlight "ipv6ConnectionAddressing" 

{
  "identifier": "UNIAL.Budapest.66.1.1",
  "connectionType": "POINT_TO_POINT",
  "l2Technology": {
    "demux": {
      "utpt": true
    }
  },
  "mtu": 1500,
  "prefixDelegation": "DISABLED",
  "reservedVrids": [],
  "egressBwpEnvelope": null,
  "ingressBwpEnvelope": null,
  "ipv4ConnectionAddressing": {},
  "ipv6ConnectionAddressing": {
    "ipv6AddressType": "DHCP"
  }
}
@endjson