@startjson

#highlight "@type"
#highlight "ipvcEndPoint" / "prefixMapping"
{
  "@type": "urn:mef:lso:spec:cantata-sonata:advanced-internet-access-ipvc:v0.2.0:all",
  "maximumNumberOfIpv4Routes": [1],
  "maximumNumberOfIpv6Routes": [1],
  "dscpPreservation": "DISABLED",
  "classOfServiceName": "Best-effort",
  "mtu": 1500,
  "pathMtuDiscovery": "ENABLED",
  "serviceLevelSpecification": [
    {
      "startTime": "2023-06-28T22:00:00.000Z",
      "periodOfTime": {
        "timeDurationValue": 1,
        "timeDurationUnits": "MONTH"
      },
      "serviceUptime": [
        {
          "serviceUptimeObjective": 99
        }
      ]
    }
  ],
  "cloud": {
    "dns": {
      "dnsType": "DHCP"
    },
    "subscriberPrefixList": [
      {
        "prefixes": [
          {
            "ipv4Prefix": {
              "ipv4Address": "192.0.2.0",
              "prefixLength": 29
            }
          },
          {
            "ipv6Prefix": {
              "ipv6Address": "2001:0DB8:0066::",
              "prefixLength": 56
            }
          }
        ],
        "origin": "SP"
      }
    ]
  },
  "reservedPrefixes": [
    {
      "ipv4Prefix": {
        "ipv4Address": "203.0.113.0",
        "prefixLength": 27
      }
    },
    {
      "ipv6Prefix": {
        "ipv6Address": "2001:0DB8::",
        "prefixLength": 64
      }
    }
  ],
  "ipvcEndPoint": {
    "identifier": "IPVCEP.Budapest.66.1.1",
    "maximumNumberOfIpv4Routes": [1],
    "maximumNumberOfIpv6Routes": [1],
    "prefixMapping": [],
    "egressClassOfServiceMap": [],
    "egressBandwidthProfileEnvelope": [],
    "ingressBandwidthProfileEnvelope": []
  }
}

@endjson