@startjson


#highlight "productOfferingQualificationItem" / "0" / "id" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "id"
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "relationshipType"

#highlight "productOfferingQualificationItem" / "1" / "id" 
#highlight "productOfferingQualificationItem" / "1" / "product" / "productConfiguration" / "@type"

#highlight "productOfferingQualificationItem" / "2" / "id" 
#highlight "productOfferingQualificationItem" / "2" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "2" / "qualificationItemRelationship" / "0" / "id"
#highlight "productOfferingQualificationItem" / "2" / "qualificationItemRelationship" / "0" / "relationshipType"
#highlight "productOfferingQualificationItem" / "2" / "qualificationItemRelationship" / "1" / "id"
#highlight "productOfferingQualificationItem" / "2" / "qualificationItemRelationship" / "1" / "relationshipType"


#highlight "productOfferingQualificationItem" / "3" / "id"
#highlight "productOfferingQualificationItem" / "3" / "product" / "place" / "0" / "@type"
#highlight "productOfferingQualificationItem" / "3" / "product" / "place" / "0" / "id"
#highlight "productOfferingQualificationItem" / "3" / "product" / "place" / "0" / "role"
#highlight "productOfferingQualificationItem" / "3" / "product" / "productConfiguration" / "@type"

{
  "externalId": "BuyerPoq-00003",
  "instantSyncQualification": false,
  "provideAlternative": false,
  "projectId": "BuyerProject3",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "action": "add",
      "id": "item-00001",
      "qualificationItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_IPUNI",
          "id": "item-00002"
        }
      ],
      "product": {
        "productOffering": {
          "id": "AdvancedInternetAccessIpvcOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:advanced-internet-access-ipvc:v0.2.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "action": "add",
      "id": "item-00002",
      "product": {
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ip-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "action": "add",
      "id": "item-00003",
      "qualificationItemRelationship": [
        {
          "relationshipType": "PART_OF_IPUNI",
          "id": "item-00002"
        },
        {
          "relationshipType": "CARRIED_OVER_TRUNK",
          "id": "item-00004"
        }
      ],
      "product": {
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniAccessLinkOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ip-uni-access-link:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "action": "add",
      "id": "item-00004",
      "product": {
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniAccessLinkTrunkOffering-0001"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "Budapest.66.1.1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ethernet-uni-access-link-trunk:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    }
  ]
}
@endjson