@startjson
#highlight "@type" 

{
  "@type": "urn:mef:lso:spec:cantata-sonata:ethernet-uni-access-link-trunk:v1.0.0:all",
  "ethernetPhysicalLink": [
    {
      "identifier": "UNIALT.Budapest.66.1.1",
      "physicalLayer": "1000BASE_SX",
      "synchronousEthernet": "DISABLED",
      "connectorType": "SC",
      "gender": "SOCKET"
    }
  ],
  "ethernetLinkAggregation": [],
  "ethernetLinkOam": "DISABLED"
}
@endjson