@startjson
#highlight "@type"
#highlight "dhcpRelay"
#highlight "bfd"
#highlight "egressBwpEnvelope"
#highlight "ingressBwpEnvelope"

#highlight "l2Technology" / "demux"
#highlight "l2Technology" / "demux" / "0" 
#highlight "ipv4ConnectionAddressing" /  "0" / "ipv4AddressingType"
#highlight "ipv4ConnectionAddressing" /  "0" / "ipv4PrimarySubnet"
#highlight "ipv4ConnectionAddressing" /  "0" / "ipv4PrimarySubnet" / "ipv4Prefix"
#highlight "ipv4ConnectionAddressing" /  "0" / "ipv4PrimarySubnet" / "ipv4Prefix" / "prefixLength"

#highlight "ipv6ConnectionAddressing" /  "0" / "ipv6Subnet" 
#highlight "ipv6ConnectionAddressing" /  "0" / "ipv6Subnet" / "ipv6Prefix"

#highlight "ipv6ConnectionAddressing" /  "0" / "ipv6Subnet" / "ipv6Prefix" / "prefixLength"
#highlight "ipv6ConnectionAddressing" /  "0" / "ipv6AddressType"


{
  "@type": "urn:mef:lso:spec:cantata-sonata:ip-uni-access-link:v1.0.0:all",
  "identifier": "UNIAL.Budapest.66.1.1",
  "connectionType": "POINT_TO_POINT",
  "dhcpRelay": [],
  "bfd": [],
  "l2Technology": {
    "demux": [66]
  },
  "mtu": 1500,
  "prefixDelegation": "DISABLED",
  "reservedVrids": [],
  "egressBwpEnvelope": [],
  "ingressBwpEnvelope": [],
  "ipv4ConnectionAddressing": [
    {
      "ipv4AddressingType": "STATIC",
      "ipv4PrimarySubnet": {
        "ipv4Prefix": {
          "prefixLength": 31
        }
      }
    }
  ],
  "ipv6ConnectionAddressing": [
    {
      "ipv6AddressType": "DHCP",
      "ipv6Subnet": {
        "ipv6Prefix": {
          "prefixLength": 64
        }
      }
    }
  ]
}
@endjson