@startjson


#highlight "productOfferingQualificationItem" / "0" / "id" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "id"
#highlight "productOfferingQualificationItem" / "0" / "qualificationItemRelationship" / "0" / "relationshipType"

#highlight "productOfferingQualificationItem" / "1" / "id" 
#highlight "productOfferingQualificationItem" / "1" / "product" / "productConfiguration" / "@type"

#highlight "productOfferingQualificationItem" / "1" / "product" / "place" / "0" / "@type"
#highlight "productOfferingQualificationItem" / "1" / "product" / "place" / "0" / "id"
#highlight "productOfferingQualificationItem" / "1" / "product" / "place" / "0" / "role"

{
  "externalId": "BuyerPoq-00003",
  "instantSyncQualification": false,
  "provideAlternative": false,
  "projectId": "BuyerProject3",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "action": "add",
      "id": "item-00001",
      "qualificationItemRelationship": [
        {
          "relationshipType": "CARRIED_OVER_TRUNK",
          "id": "item-00002"
        }
      ],
      "product": {
        "productOffering": {
          "id": "ExclusiveAdvancedInternetAccessIpvcOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:exclusive-advanced-internet-access:v0.3.0:all",
          "ipvc": "<<skipped>>",
          "ipUni":  "<<skipped>>",
          "ipUniAccessLink":  "<<skipped>>"
        }
      }
    },
    {
      "action": "add",
      "id": "item-00002",
      "product": {
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniAccessLinkTrunkOffering-0001"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "Budapest.66.1.1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ethernet-uni-access-link-trunk:v0.3.0:all",
           "other": "<<skipped>>"
        }
      }
    }
  ]
}

@endjson