@startjson


#highlight "productOfferingQualificationItem" / "0" / "id" 
#highlight "productOfferingQualificationItem" / "0" / "action" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "id" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" / "@type"


{
  "externalId": "BuyerPoq-00007",
  "instantSyncQualification": false,
  "provideAlternative": false,
  "projectId": "BuyerProject7",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "action": "add",
      "id": "item-00001",
      "product": {
        "id": "SellerIpUniId-0001",
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ip-uni:v0.3.0:all",
          "other": "<<skipped>>"
        }
      }
    }
  ]
}

@endjson