@startjson


#highlight "quoteItem" / "0" / "id" 
#highlight "quoteItem" / "0" / "action" 
#highlight "quoteItem" / "0" / "product" / "id" 

{
  "requestedQuoteCompletionDate": "2023-06-25T22:00:00Z",
  "externalId": "BuyerQuote-00010",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProject10",
  "instantSyncQuote": false,
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "buyerContactInformation",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "quoteItem": [
    {
      "action": "delete",
      "id": "item-00001",
      "product": {
        "id": "SellerBasicInternetAccessId-0001"
      }
    }
  ]
}


@endjson