@startjson


#highlight "productOrderItem" / "0" / "action" 
#highlight "productOrderItem" / "0" / "id" 
#highlight "productOrderItem" / "0" / "product" / "id" 

#highlight "productOrderItem" / "1" / "action" 
#highlight "productOrderItem" / "1" / "id" 
#highlight "productOrderItem" / "1" / "product" / "id" 

#highlight "productOrderItem" / "1" / "product" / "productConfiguration" / "@type"


{
  "externalId": "BuyerOrder-00009",
  "projectId": "BuyerProject9",
  "relatedContactInformation": "<<skipped>>",
  "productOrderItem": [
    {
      "action": "delete",
      "id": "item-00001",
      "product": {
        "id": "SellerAdvancedInternetAccessIpvcId-0001"
      }
    },
    {
      "action": "modify",
      "id": "item-00002",
      "expediteIndicator": false,
      "requestedItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly subscription"
      },
      "relatedContactInformation": "<<skipped>>",
      "billingAccount": "<<skipped>>",
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "requestedCompletionDate": "2023-06-28T22:00:00Z",
      "product": {
        "id": "SellerIpUniId-0001",
        "productOffering": {
          "id": "AdvancedInternetAccessIpUniOffering-0001"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:ip-uni:v0.3.0:all",
          "other": "<<skipped>>"
        }
      }
    }
  ]
}

@endjson