@startjson
{
    "id": "ID_Access E-Line OVC Excellence",
    "name": "Access E-Line OVC Excellence",
    "description": "Access E-Line, SLA 99.99%",
    "lastUpdate": "2024-11-28T11:25:20",
    "lifecycleStatus": "launched",
    "statusReason": "Approved & ready for market",
    "agreement": "standard-agreement-AG012023",
    "region": [
        {
            "stateOrProvince": "AZ",
            "countryCode": "US"
        },
        {
            "stateOrProvince": "AL",
            "countryCode": "US"
        },
        {
            "stateOrProvince": "AR",
            "countryCode": "US"
        }
    ],
    "isBundle": false,
    "isSellable": true,
    "statusTransition": [
        {
            "transitionDate": "2024-11-27T11:25:20",
            "lifecycleStatus": "active"
        },
        {
            "transitionDate": "2024-11-28T11:25:20",
            "lifecycleStatus": "launched"
        }
    ],
    "productSpecification": {
        "id": "ID_OVC_Spec",
        "href": "https://example.com/productSpecification/ID_OVC_Spec"
    },
    "productOfferingTerm": [
        {
            "name": "standard24MonthOvcTerm",
            "description": "24 month term for OVC Excellence",
            "duration": {
                "amount": 24,
                "units": "months"
            },
            "endOfTermAction": "roll",
            "rollInterval": {
                "amount": 1,
                "units": "months"
            },
            "productOfferingPrice": [
                {
                    "description": "Standard OVC construction price in AZ",
                    "lastUpdate": "2024-11-28T11:25:20",
                    "validFor": {
                        "endDateTime": "2024-12-28T11:25:20"
                    },
                    "region": [
                        {
                            "stateOrProvince": "AZ",
                            "countryCode": "US"
                        }
                    ],
                    "priceType": "nonRecurring",
                    "price": {
                        "taxRate": 7,
                        "taxIncludedAmount": {
                            "unit": "USD",
                            "value": 800
                        },
                        "dutyFreeAmount": {
                            "unit": "USD",
                            "value": 747.66
                        }
                    },
                    "priceModifier": [
                        {
                            "description": "Standard contract renewal discount",
                            "lastUpdate": "2024-11-28T11:25:20",
                            "validFor": {
                                "endDateTime": "2025-12-31T23:59:59Z"
                            },
                            "minimumQuantity": 1,
                            "dealReference": "0123456",
                            "reductionPercentage": 10
                        }
                    ]
                },
                {
                    "description": "Standard OVC installation price in AZ",
                    "lastUpdate": "2024-11-28T11:25:20",
                    "validFor": {
                        "endDateTime": "2024-12-28T11:25:20"
                    },
                    "region": [
                        {
                            "stateOrProvince": "AZ",
                            "countryCode": "US"
                        }
                    ],
                    "priceType": "nonRecurring",
                    "price": {
                        "taxRate": 7,
                        "taxIncludedAmount": {
                            "unit": "USD",
                            "value": 200
                        },
                        "dutyFreeAmount": {
                            "unit": "USD",
                            "value": 186.92
                        }
                    },
                    "priceModifier": [
                        {
                            "description": "Standard contract renewal discount",
                            "lastUpdate": "2024-11-28T11:25:20",
                            "validFor": {
                                "endDateTime": "2025-12-31T23:59:59Z"
                            },
                            "minimumQuantity": 1,
                            "dealReference": "0123456",
                            "reductionPercentage": 10
                        }
                    ]
                },
                {
                    "description": "Standard OVC usage price in AZ",
                    "lastUpdate": "2024-11-28T11:25:20",
                    "validFor": {
                        "endDateTime": "2024-12-28T11:25:20"
                    },
                    "region": [
                        {
                            "stateOrProvince": "AZ",
                            "countryCode": "US"
                        }
                    ],
                    "priceType": "recurring",
                    "recurringChargePeriod": {
                        "amount": 1,
                        "units": "months"
                    },
                    "price": {
                        "taxRate": 7,
                        "taxIncludedAmount": {
                            "unit": "USD",
                            "value": 200
                        },
                        "dutyFreeAmount": {
                            "unit": "USD",
                            "value": 186.92
                        }
                    }
                }
            ]
        }
    ]
}
@endjson
