@startuml
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor DarkRed
    shadowing true
}
hide empty description

''' diagram'''
[*] -d-> available :  Seller publishes the category to be used for querying
available -d-> obsolete : Seller ends the life cycle of the Category
obsolete --> [*]

@enduml