@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}


class ProductCategory {

    id*: string
    href: uri
    name*: string
    description*: string
    lastUpdate*: date-time
}

ProductCategory *--> ProductCategoryRef : parentCategory
ProductCategory *-->"*" ProductCategoryRef : subCategory
ProductCategory *-->"*" ProductOfferingRef : productOffering


class ProductCategoryRef {

    id*: string
    href: uri
}

class ProductOfferingRef {

    id*: string
    href: uri
}



@enduml
