@startuml
skinparam {
    ObjectBackgroundColor White
    ObjectBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}

object AccessELineOvcBasic {
    id*:  productOffering-1
    name*: Access E-line OVC Basic
    lastUpdate*: 2023-01-19T16:30:51.626Z
    lifecycleStatus*: orderable
    productType*: AccessElineOvc
    channel: [DirectSales,Distribution]
    marketSegment: [Federal,Financial]
    agreement: Official agreement no 4
}

object AccessELineOvcExcellence {
    id*:  productOffering-2
    name*: Access E-line OVC Excellence
    lastUpdate*: 2023-01-19T16:33:51.626Z
    lifecycleStatus*: orderable
    productType*: AccessElineOvc
    channel: [DirectSales]
    marketSegment: [Federal]
    agreement: Official agreement no 4
}

object AccessELineOvc {
    id*:  productSpecification-1
    name*: Access E-line OVC
    lastUpdate*: 2023-01-19T16:32:51.626Z
    lifecycleStatus*: orderable
}

object AccessELineProductOfferings {
    id*:  productCategory-2
    name*: Access E-Lines Product Offerings
    lastUpdate*: 2023-01-19T16:32:51.626Z
    lifecycleStatus*: active
}

AccessELineProductOfferings *-- AccessELineOvcBasic: productOffering
AccessELineOvc <-- AccessELineOvcBasic: productSpecification

@enduml
