@startuml


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class ProductCategoryAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- ProductCategoryAttributeValueChangeEvent

ProductCategoryAttributeValueChangeEvent *-->"1" ProductCategoryEventPayload : event


class ProductCategoryCreateEvent {

    eventType*: string
}
Event <|-- ProductCategoryCreateEvent

ProductCategoryCreateEvent *-->"1" ProductCategoryEventPayload : event


class ProductCategoryEventPayload {

    id*: string
    href: uri
}



class ProductOfferingAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- ProductOfferingAttributeValueChangeEvent

ProductOfferingAttributeValueChangeEvent *-->"1" ProductOfferingEventPayload : event


class ProductOfferingCreateEvent {

    eventType*: string
}
Event <|-- ProductOfferingCreateEvent

ProductOfferingCreateEvent *-->"1" ProductOfferingEventPayload : event


class ProductOfferingEventPayload {

    id*: string
    href: uri
}



enum ProductOfferingLifecycleStatusType {

    active
    endOfSale
    endOfSupport
    inTest
    obsolete
    onHold
    launched
    rejected
}
class ProductOfferingStateChangeEvent {

    eventType*: string
}
Event <|-- ProductOfferingStateChangeEvent

ProductOfferingStateChangeEvent *-->"1" ProductOfferingStateChangeEventPayload : event


class ProductOfferingStateChangeEventPayload {

    id*: string
    href: uri
    lifecycleStatus*: ProductOfferingLifecycleStatusType
}



class ProductSpecificationAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- ProductSpecificationAttributeValueChangeEvent

ProductSpecificationAttributeValueChangeEvent *-->"1" ProductSpecificationEventPayload : event


class ProductSpecificationCreateEvent {

    eventType*: string
}
Event <|-- ProductSpecificationCreateEvent

ProductSpecificationCreateEvent *-->"1" ProductSpecificationEventPayload : event


class ProductSpecificationEventPayload {

    id*: string
    href: uri
}



enum ProductSpecificationLifecycleStatusType {

    obsolete
    published
}
class ProductSpecificationStateChangeEvent {

    eventType*: string
}
Event <|-- ProductSpecificationStateChangeEvent

ProductSpecificationStateChangeEvent *-->"1" ProductSpecificationStateChangeEventPayload : event


class ProductSpecificationStateChangeEventPayload {

    id*: string
    href: uri
    lifecycleStatus*: ProductSpecificationLifecycleStatusType
}



@enduml
