@startuml


class ProductOffering_Common {

    id: string
    href: uri
    name: string
    description: string
    lastUpdate: date-time
    lifecycleStatus: ProductOfferingLifecycleStatusType
    agreement: string
    isBundle: boolean
    isSellable: boolean
    channel: string[]
    marketSegment: string[]
}

ProductOffering_Common *-->"*" Region : region
ProductOffering_Common *-->"*" ProductCategoryRef : category
ProductOffering_Common *--> ProductSpecificationRef : productSpecification


class ProductOffering_Find {

}
ProductOffering_Common <|-- ProductOffering_Find

class ProductCategoryRef {

    id*: string
    href: uri
}
class Region {

    city: string
    locality: string
    stateOrProvince: string
    countryCode*: string
}


enum ProductOfferingLifecycleStatusType {

    active
    endOfSale
    endOfSupport
    inTest
    obsolete
    onHold
    launched
    rejected
}

class ProductSpecificationRef {

    id*: string
    href: uri
}


@enduml
