@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}



class ProductOffering_Common {

    id: string
    href: uri
    name: string
    description: string
    lastUpdate: date-time
    lifecycleStatus: ProductOfferingLifecycleStatusType
    agreement: string
    channel: string[]
    marketSegment: string[]
}

ProductOffering_Common *-->"*" Region : region
ProductOffering_Common *-->"*" ProductCategoryRef : category
ProductOffering_Common *--> ProductSpecificationRef : productSpecification


class ProductOffering_Find {

}
ProductOffering_Common <|-- ProductOffering_Find

class ProductCategoryRef {

    id*: string
    href: uri
}

class Region {

    locality: string
    stateOrProvince: string
    country*: string
}

enum ProductOfferingLifecycleStatusType {

    announced
    endOfSale
    endOfSupport
    inTest
    obsolete
    onHold
    orderable
    rejected
}

class ProductSpecificationRef {

    id*: string
    href: uri
}


@enduml
