@startuml
skinparam {
participantBorderColor DarkRed
participantBorderThickness 1
participantBackgroundColor BUSINESS

LifeLineBorderColor DarkRed
LifeLineBackgroundColor DarkRed

databaseBorderColor Grey
databaseBorderThickness 1

shadowing true
RoundCorner 0
LineColor DarkRed
ArrowColor DarkRed
ArrowThickness 1
}

hide footbox

participant Buyer as b
participant Seller as s

activate b
b -> s++: GET {{baseUrl}}/produdctSpecification/{{id}}
alt Success (HTTP 200)
b <-- s: HTTP 200 Ok (list with one element) 
else Bussines Failure (HTTP 400/401/403)
b <-- s: HTTP 4xx 
else Not found (HTTP 404)
b <-- s: HTTP 404 Not found 
else Server Failure (HTTP 500)
b <-- s--: HTTP 500 Internal error 
end
deactivate b

...
@enduml