@startuml
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor DarkRed
    shadowing true
}
hide empty description

[*] -d-> published
published -d-> obsolete
obsolete --> [*]

@enduml