@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}

class ProductSpecification_Common {

    id: string
    href: uri
    name: string
    lifecycleStatus: ProductSpecificationLifecycleStatusType
    lastUpdate: date-time
}

class ProductSpecification_Find {

}
ProductSpecification_Common <|-- ProductSpecification_Find

enum ProductSpecificationLifecycleStatusType {

    obsolete
    published
}

@enduml
