@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}

class ProductSpecification_Common {
    id*: string
    href: string
    name*: string
    description: string
    lastUpdate*: date-time
    lifecycleStatus* ProductSpecificationLifecycleStatus
}

class ProductSpecification {
    brand: string
    producNumber: string
}

class  ProductSpecification_Find {

}

ProductSpecification_Common <|-- ProductSpecification_Find
ProductSpecification_Common <|-- ProductSpecification


class AttachmentValue {
    attachmentId*: string
    author*: string
    content: string
    creationDate*: string
    description: string
    mimeType: string
    name*: string
    source: MEFBuyerSellerType
    url: string
}

class MEFByteSize {
   ammount*: float
   units*: DataSizeUnit
}

AttachmentValue *-->"0..1" MEFByteSize : size

class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}

class SchemaRefOrValue {
    schema: string
    schemaLocation: string
}

class ProductSpecificationRelationship {
    id*: string
    type*: string
    minCardinality*: number
    maxCardinality*: number
}

ProductSpecification *-->"0..*" AttachmentValue : attachment
ProductSpecification *-->"0..*" Note: note
ProductSpecification *-->"1..1" SchemaRefOrValue: sourceSchema
ProductSpecification *-->"0..*" ProductSpecificationRelationship: productSpecificationRelationship

enum ProductSpecificationLifecycleStatus {
    pilotBeta
    rejected
    active
    endOfSale
    endOfSupport
    obsolete
    onHold
    orderable
}

enum DataSizeUnit{
    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}

@enduml
