@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    shadowing true
    RoundCorner 0
    LineColor DarkRed
    ArrowColor DarkRed
    ArrowThickness 1
}

class ProductSpecification_Common {
    id*: string
    href: string
    name*: string
    description: string
    lastUpdate*: date-time
    lifecycleStatus*: ProductSpecificationLifecycleStatus
}

class  ProductSpecification_Find {

}

ProductSpecification_Common <|-- ProductSpecification_Find

enum ProductSpecificationLifecycleStatus {
    pilotBeta
    rejected
    active
    endOfSale
    endOfSupport
    obsolete
    onHold
    orderable
}

@enduml
