@startuml
skinparam usecase {
BackgroundColor<<not in scope>> LightGrey
BorderColor<<not in scope>> Black

BackgroundColor BUSINESS
BorderColor DarkRed

arrowColor DarkRed
arrowThickness 1

shadowing true
}

skinparam actor {
BorderColor DarkRed
BackgroundColor BUSINESS

shadowing true
}

left to right direction
actor Seller 
actor Buyer

rectangle {
(1. Retrieve Product Category List)
(2. Retrieve Product Category by Identifier)
(3. Retrieve Product Offering List)
(4. Retrieve Product Offering by Identifier)
(5. Retrieve Product Specification List)
(6. Retrieve Product Specification by Identifier)
(7.	Register for Product Catalog Notifications)
(8.	Send Product Catalog Notifications)
Buyer --> (1. Retrieve Product Category List)
Buyer --> (2. Retrieve Product Category by Identifier)
Buyer --> (3. Retrieve Product Offering List)
Buyer --> (4. Retrieve Product Offering by Identifier)
Buyer --> (5. Retrieve Product Specification List)
Buyer --> (6. Retrieve Product Specification by Identifier)
Buyer --> (7.	Register for Product Catalog Notifications)

(8.	Send Product Catalog Notifications) <-- Seller


@enduml
