//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 01:55:00 PM CEST 
//


package com.orange.onapbss.datamodel.productordering;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orange.onapbss.datamodel package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZErrorDetail_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ZErrorDetail");
    private final static QName _ZError_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ZError");
    private final static QName _BillingAccountRef_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "BillingAccountRef");
    private final static QName _ProductOrder_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ProductOrder");
    private final static QName _Note_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "Note");
    private final static QName _OrderItem_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "OrderItem");
    private final static QName _ProductOffering_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ProductOffering");
    private final static QName _Product_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "Product");
    private final static QName _OrderItemRelationShip_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "OrderItemRelationShip");
    private final static QName _ProductRelationship_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ProductRelationship");
    private final static QName _RelatedQualification_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "RelatedQualification");
    private final static QName _RelatedParty_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "RelatedParty");
    private final static QName _ProductSpecification_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "ProductSpecification");
    private final static QName _GeographicSubAddress_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "GeographicSubAddress");
    private final static QName _GeographicPoint_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "GeographicPoint");
    private final static QName _GeographicLocation_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "GeographicLocation");
    private final static QName _Site_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "Site");
    private final static QName _GeographicAddress_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "GeographicAddress");
    private final static QName _Describing_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "Describing");
    private final static QName _GeographicAddressEntityId_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "id");
    private final static QName _GeographicAddressEntityHref_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "href");
    private final static QName _GeographicAddressEntityRole_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "role");
    private final static QName _GeographicAddressEntityType_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "type");
    private final static QName _GeographicAddressEntityStreetNr_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetNr");
    private final static QName _GeographicAddressEntityStreetNrSuffix_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetNrSuffix");
    private final static QName _GeographicAddressEntityStreetNrLast_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetNrLast");
    private final static QName _GeographicAddressEntityStreetNrLastSuffix_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetNrLastSuffix");
    private final static QName _GeographicAddressEntityStreetName_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetName");
    private final static QName _GeographicAddressEntityStreetType_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetType");
    private final static QName _GeographicAddressEntityStreetSuffix_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "streetSuffix");
    private final static QName _GeographicAddressEntityLocality_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "locality");
    private final static QName _GeographicAddressEntityCity_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "city");
    private final static QName _GeographicAddressEntityPostcode_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "postcode");
    private final static QName _GeographicAddressEntityStateOrProvince_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "stateOrProvince");
    private final static QName _GeographicAddressEntityPostalCodeExtension_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "postalCodeExtension");
    private final static QName _GeographicAddressEntityCountry_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "country");
    private final static QName _GeographicAddressEntityGeographicSubAddress_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "geographicSubAddress");
    private final static QName _GeographicAddressEntitySchemaLocation_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "schemaLocation");
    private final static QName _GeographicAddressEntityFormattedAddressLine1_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "FormattedAddressLine1");
    private final static QName _GeographicAddressEntityFormattedAddressLine2_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "FormattedAddressLine2");
    private final static QName _GeographicAddressEntityReferenceId_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "referenceId");
    private final static QName _GeographicAddressEntityReferenceType_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "referenceType");
    private final static QName _SiteEntitySiteCompanyName_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "siteCompanyName");
    private final static QName _SiteEntitySiteCustomerName_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "siteCustomerName");
    private final static QName _SiteEntityAdditionalSiteInformation_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "additionalSiteInformation");
    private final static QName _SiteEntitySiteDescription_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "siteDescription");
    private final static QName _GeographicLocationEntityName_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "name");
    private final static QName _GeographicLocationEntityGeographicPoint_QNAME = new QName("http://orange.com/MEF/api/productorder/v0/model", "geographicPoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orange.onapbss.datamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZErrorDetailEntity }
     * 
     */
    public ZErrorDetailEntity createZErrorDetailEntity() {
        return new ZErrorDetailEntity();
    }

    /**
     * Create an instance of {@link ZErrorEntity }
     * 
     */
    public ZErrorEntity createZErrorEntity() {
        return new ZErrorEntity();
    }

    /**
     * Create an instance of {@link BillingAccountRefEntity }
     * 
     */
    public BillingAccountRefEntity createBillingAccountRefEntity() {
        return new BillingAccountRefEntity();
    }


    /**
     * Create an instance of {@link ProductOrderEntity }
     * 
     */
    public ProductOrderEntity createProductOrderEntity() {
        return new ProductOrderEntity();
    }

    /**
     * Create an instance of {@link NoteEntity }
     * 
     */
    public NoteEntity createNoteEntity() {
        return new NoteEntity();
    }

    /**
     * Create an instance of {@link OrderItemEntity }
     * 
     */
    public OrderItemEntity createOrderItemEntity() {
        return new OrderItemEntity();
    }

    /**
     * Create an instance of {@link ProductOfferingEntity }
     * 
     */
    public ProductOfferingEntity createProductOfferingEntity() {
        return new ProductOfferingEntity();
    }

    /**
     * Create an instance of {@link OrderItemRelationShipEntity }
     * 
     */
    public OrderItemRelationShipEntity createOrderItemRelationShipEntity() {
        return new OrderItemRelationShipEntity();
    }


    /**
     * Create an instance of {@link RelatedQualificationEntity }
     * 
     */
    public RelatedQualificationEntity createRelatedQualificationEntity() {
        return new RelatedQualificationEntity();
    }



    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZErrorDetailEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "ZErrorDetail")
    public JAXBElement<ZErrorDetailEntity> createZErrorDetail(ZErrorDetailEntity value) {
        return new JAXBElement<ZErrorDetailEntity>(_ZErrorDetail_QNAME, ZErrorDetailEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZErrorEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "ZError")
    public JAXBElement<ZErrorEntity> createZError(ZErrorEntity value) {
        return new JAXBElement<ZErrorEntity>(_ZError_QNAME, ZErrorEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillingAccountRefEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "BillingAccountRef")
    public JAXBElement<BillingAccountRefEntity> createBillingAccountRef(BillingAccountRefEntity value) {
        return new JAXBElement<BillingAccountRefEntity>(_BillingAccountRef_QNAME, BillingAccountRefEntity.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductOrderEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "ProductOrder")
    public JAXBElement<ProductOrderEntity> createProductOrder(ProductOrderEntity value) {
        return new JAXBElement<ProductOrderEntity>(_ProductOrder_QNAME, ProductOrderEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "Note")
    public JAXBElement<NoteEntity> createNote(NoteEntity value) {
        return new JAXBElement<NoteEntity>(_Note_QNAME, NoteEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderItemEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "OrderItem")
    public JAXBElement<OrderItemEntity> createOrderItem(OrderItemEntity value) {
        return new JAXBElement<OrderItemEntity>(_OrderItem_QNAME, OrderItemEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductOfferingEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "ProductOffering")
    public JAXBElement<ProductOfferingEntity> createProductOffering(ProductOfferingEntity value) {
        return new JAXBElement<ProductOfferingEntity>(_ProductOffering_QNAME, ProductOfferingEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderItemRelationShipEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "OrderItemRelationShip")
    public JAXBElement<OrderItemRelationShipEntity> createOrderItemRelationShip(OrderItemRelationShipEntity value) {
        return new JAXBElement<OrderItemRelationShipEntity>(_OrderItemRelationShip_QNAME, OrderItemRelationShipEntity.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedQualificationEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/MEF/api/productorder/v0/model", name = "RelatedQualification")
    public JAXBElement<RelatedQualificationEntity> createRelatedQualification(RelatedQualificationEntity value) {
        return new JAXBElement<RelatedQualificationEntity>(_RelatedQualification_QNAME, RelatedQualificationEntity.class, null, value);
    }


}
