//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 01:55:00 PM CEST 
//


package com.orange.onapbss.datamodel.productordering;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pricingMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pricingMethod"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Tariff"/&gt;
 *     &lt;enumeration value="Contract"/&gt;
 *     &lt;enumeration value="Individual Case Basis"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "pricingMethod")
@XmlEnum
public enum PricingMethodEntity {

    @XmlEnumValue("Tariff")
    TARIFF("Tariff"),
    @XmlEnumValue("Contract")
    CONTRACT("Contract"),
    @XmlEnumValue("Individual Case Basis")
    INDIVIDUAL_CASE_BASIS("Individual Case Basis"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PricingMethodEntity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PricingMethodEntity fromValue(String v) {
        for (PricingMethodEntity c: PricingMethodEntity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
