//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 01:55:00 PM CEST 
//


package com.orange.onapbss.datamodel.productordering;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.orange.soa.commons.utils.XmlDateTimeAdapter;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for ProductOrder complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ProductOrder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="state" type="{http://orange.com/MEF/api/productOrder/v0/model}StateType" minOccurs="0"/&gt;
 *         &lt;element name="requestedStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="requestedCompletionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="completionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="expeditePriority" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="orderActivity" type="{http://orange.com/MEF/api/productOrder/v0/model}OrderActivity"/&gt;
 *         &lt;element name="desiredResponses" type="{http://orange.com/MEF/api/productOrder/v0/model}desiredResponse"/&gt;
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="projectId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tspRestorationPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="relatedParty" type="{http://orange.com/MEF/api/productOrder/v0/model}RelatedParty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="note" type="{http://orange.com/MEF/api/productOrder/v0/model}Note" minOccurs="0"/&gt;
 *         &lt;element name="orderItem" type="{http://orange.com/MEF/api/productOrder/v0/model}OrderItem" maxOccurs="unbounded"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="schemaLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductOrder", propOrder = {
        "id",
        "externalId",
        "orderDate",
        "state",
        "requestedStartDate",
        "requestedCompletionDate",
        "completionDate",
        "expeditePriority",
        "orderActivity",
        "desiredResponses",
        "version",
        "projectId",
        "tspRestorationPriority",
        "relatedParty",
        "note",
        "orderItem",
        "type",
        "schemaLocation"
})
@Entity(name = "ProductOrderEntity")
@Table(name = "PRODUCT_ORDER_ENTITY")
@Inheritance(strategy = InheritanceType.JOINED)
public class ProductOrderEntity
        implements Serializable {

    private final static long serialVersionUID = -1L;
    protected String id;
    @XmlElement(required = true)
    
    protected String externalId;
    @XmlElement(required = true, type = String.class)
    
    @XmlJavaTypeAdapter(XmlDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date orderDate;
    @XmlSchemaType(name = "string")
    protected StateTypeEntity state;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date requestedStartDate;
    @XmlElement(required = true, type = String.class)
    
    @XmlJavaTypeAdapter(XmlDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date requestedCompletionDate;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(XmlDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date completionDate;
    protected Integer expeditePriority;
    @XmlElement(required = true)
    
    @XmlSchemaType(name = "string")
    protected OrderActivityEntity orderActivity;
    @XmlElement(required = true)
    
    @XmlSchemaType(name = "string")
    protected DesiredResponseEntity desiredResponse;
    @XmlElement(required = true)
    
    protected String version;
    protected String projectId;
    protected String tspRestorationPriority;
    protected List<RelatedPartyEntity> relatedParty;
    protected NoteEntity note;
    @XmlElement(required = true)
    
    protected List<OrderItemEntity> orderItem;
    @JsonProperty("@type")
    protected String type;
    @JsonProperty("@schemaLocation")
    protected String schemaLocation;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    @Id
    @Column(name = "ID", length = 100)
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the externalId property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "EXTERNAL_ID", length = 255)
    
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the orderDate property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "ORDER_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrderDate(Date value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link StateTypeEntity }
     */
    @Basic
    @Column(name = "STATE_", length = 255)
    public String getState() {

        return state != null ? state.value() : null;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link StateTypeEntity }
     */
    public void setState(String value) {
        if (value != null) {
            this.state = StateTypeEntity.fromValue(value);
        }
    }

    public void setStateValue(StateTypeEntity value) {
        this.state = value;
    }

    /**
     * Gets the value of the requestedStartDate property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "REQUESTED_START_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getRequestedStartDate() {
        return requestedStartDate;
    }

    /**
     * Sets the value of the requestedStartDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRequestedStartDate(Date value) {
        this.requestedStartDate = value;
    }

    /**
     * Gets the value of the requestedCompletionDate property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "REQUESTED_COMPLETION_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getRequestedCompletionDate() {
        return requestedCompletionDate;
    }

    /**
     * Sets the value of the requestedCompletionDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRequestedCompletionDate(Date value) {
        this.requestedCompletionDate = value;
    }

    /**
     * Gets the value of the completionDate property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "COMPLETION_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCompletionDate(Date value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the expeditePriority property.
     *
     * @return possible object is
     * {@link Integer }
     */
    @Basic
    @Column(name = "EXPEDITE_PRIORITY", precision = 10, scale = 0)
    public Integer getExpeditePriority() {
        return expeditePriority;
    }

    /**
     * Sets the value of the expeditePriority property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setExpeditePriority(Integer value) {
        this.expeditePriority = value;
    }

    /**
     * Gets the value of the orderActivity property.
     *
     * @return possible object is
     * {@link OrderActivityEntity }
     */
    @Basic
    @Column(name = "ORDER_ACTIVITY", length = 255)
    public String getOrderActivity() {
        return orderActivity != null ? orderActivity.value() : null;
    }

    /**
     * Sets the value of the orderActivity property.
     *
     * @param value allowed object is
     *              {@link OrderActivityEntity }
     */
    public void setOrderActivity(String value) {
        if (value != null) {
            this.orderActivity = OrderActivityEntity.fromValue(value);
        }
    }

    public void setOrderActivityValue(OrderActivityEntity value) {
        this.orderActivity = value;
    }

    /**
     * Gets the value of the desiredResponses property.
     *
     * @return possible object is
     * {@link DesiredResponseEntity }
     */
    @Basic
    @Column(name = "DESIRED_RESPONSES", length = 255)
    public String getDesiredResponse() {
        return desiredResponse != null ? desiredResponse.value() : null;
    }

    /**
     * Sets the value of the desiredResponses property.
     *
     * @param value allowed object is
     *              {@link DesiredResponseEntity }
     */
    public void setDesiredResponse(String value) {
        if (value != null) {
            this.desiredResponse = DesiredResponseEntity.fromValue(value);
        }
    }

    public void setDesiredResponseValue(DesiredResponseEntity value) {
        this.desiredResponse = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "VERSION_", length = 255)
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the projectId property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "PROJECT_ID", length = 255)
    public String getProjectId() {
        return projectId;
    }

    /**
     * Sets the value of the projectId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProjectId(String value) {
        this.projectId = value;
    }

    /**
     * Gets the value of the tspRestorationPriority property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "TSP_RESTORATION_PRIORITY", length = 255)
    public String getTspRestorationPriority() {
        return tspRestorationPriority;
    }

    /**
     * Sets the value of the tspRestorationPriority property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTspRestorationPriority(String value) {
        this.tspRestorationPriority = value;
    }

    /**
     * Gets the value of the relatedParty property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedParty property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedParty().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPartyEntity }
     */
    @OneToMany(targetEntity = RelatedPartyEntity.class, cascade = {
            CascadeType.ALL
    })
    @JoinColumn(name = "RELATED_PARTY_PRODUCT_ORDER__0")
    public List<RelatedPartyEntity> getRelatedParty() {
        if (relatedParty == null) {
            relatedParty = new ArrayList<RelatedPartyEntity>();
        }
        return this.relatedParty;
    }

    /**
     *
     *
     */
    public void setRelatedParty(List<RelatedPartyEntity> relatedParty) {
        this.relatedParty = relatedParty;
    }

    /**
     * Gets the value of the note property.
     *
     * @return possible object is
     * {@link NoteEntity }
     */
    @ManyToOne(targetEntity = NoteEntity.class, cascade = {
            CascadeType.ALL
    })
    @JoinColumn(name = "NOTE_PRODUCT_ORDER_ENTITY_HJ_0")
    public NoteEntity getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     *
     * @param value allowed object is
     *              {@link NoteEntity }
     */
    public void setNote(NoteEntity value) {
        this.note = value;
    }

    /**
     * Gets the value of the orderItem property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItem property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItem().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItemEntity }
     */
    @OneToMany(targetEntity = OrderItemEntity.class,cascade = {
            CascadeType.ALL
    })
    @JoinColumn(name = "ORDER_ITEM_PRODUCT_ORDER_ENT_0")
    public List<OrderItemEntity> getOrderItem() {
        if (orderItem == null) {
            orderItem = new ArrayList<OrderItemEntity>();
        }
        return this.orderItem;
    }


    /**
     *
     *
     */
    public void setOrderItem(List<OrderItemEntity> orderItem) {
        this.orderItem = orderItem;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "TYPE_", length = 255)
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the schemaLocation property.
     *
     * @return possible object is
     * {@link String }
     */
    @Basic
    @Column(name = "SCHEMA_LOCATION", length = 255)
    public String getSchemaLocation() {
        return schemaLocation;
    }

    /**
     * Sets the value of the schemaLocation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSchemaLocation(String value) {
        this.schemaLocation = value;
    }

}
