@startuml
skinparam {

    ClassBorderColor<<ProductSpecification>> FireBrick
}
set namespaceSeparator none

class MEFProduct{

    <<... attributes are skipped ...>>
   
}



set namespaceSeparator none

class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


MEFProduct *--> MEFProductConfiguration : productConfiguration



class AccessElineOvc <<ProductSpecification>> {
    @type  urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- AccessElineOvc

class CarrierEthernetOperatorUni <<ProductSpecification>> {
    @type = urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v5.0.0:all
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- CarrierEthernetOperatorUni



@enduml
