@startuml

class ContactInformation {

    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

ContactInformation *--> FieldedAddressRepresentation : postalAddress


class Duration {

    amount*: integer
    units*: TimeUnit
}



class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit


class FormattedAddressRepresentation {

    formattedAddress*: string
    language: string
}



class GeographicAddressRef {

    href: string
    id*: string
    @type*: string
}



class GeographicAddress_Query {

    @type*: string
}

GeographicAddress_Query *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress_Query *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress_Query *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress_Query *-->"*" LabelRepresentation : labelRepresentation


class GeographicPointRepresentation {

    spatialRef*: string
    latitude*: string
    longitude*: string
    elevation: string
}



class GeographicSiteRef {

    href: string
    id*: string
    @type*: string
}



class LabelRepresentation {

    label*: string
    administrativeAuthority*: string
    language: string
}



class MEFBillingAccountRef {

    id*: string
}



enum MEFEndOfTermAction {

    roll
    autoDisconnect
    autoRenew
}
class MEFItemTerm {

    endOfTermAction*: MEFEndOfTermAction
    name*: string
    description: string
}

MEFItemTerm *-->"1" Duration : duration
MEFItemTerm *--> Duration : rollInterval


enum MEFPriceType {

    recurring
    nonRecurring
    usageBased
}
class MEFProduct {

    id*: string
    href: string
    startDate*: date-time
    externalId: string
    status*: MEFProductStatusType
    lastUpdateDate: date-time
    agreementName: string
    terminationDate: date-time
    @type: string
}

MEFProduct *-->"*" MEFProductStatusChange : statusChange
MEFProduct *--> ProductSpecificationRef : productSpecification
MEFProduct *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct *--> ProductOfferingRef : productOffering
MEFProduct *-->"*" RelatedContactInformation : relatedContactInformation
MEFProduct *--> MEFBillingAccountRef : billingAccount
MEFProduct *-->"*" MEFProductOrderItemRef : productOrderItem
MEFProduct *-->"*" MEFItemTerm : productTerm
MEFProduct *--> MEFProductConfiguration : productConfiguration
MEFProduct *-->"*" ProductRelationship : productRelationship
MEFProduct *-->"*" ProductPrice : productPrice


class MEFProductConfiguration {

    @type*: string
}



class MEFProductOrderItemRef {

    productOrderHref: string
    productOrderItemId*: string
    productOrderId*: string
}



class MEFProductStatusChange {

    changeReason: string
    changeDate*: date-time
    status*: MEFProductStatusType
}



enum MEFProductStatusType {

    active
    active.pendingChange
    cancelled
    pendingActive
    pendingTerminate
    suspended
    suspendedPendingTerminate
    terminated
}
class MEFProduct_Find {

    lastUpdateDate: date-time
    externalId: string
    id*: string
    href: string
    startDate: date-time
    status*: MEFProductStatusType
}

MEFProduct_Find *--> ProductSpecificationRef : productSpecification
MEFProduct_Find *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct_Find *--> ProductOfferingRef : productOffering
MEFProduct_Find *-->"*" ProductRelationship : productRelationship
MEFProduct_Find *--> MEFBillingAccountRef : billingAccount
MEFProduct_Find *-->"*" MEFProductOrderItemRef : productOrderItem


class Money {

    unit*: string
    value*: float
}



class PlaceRefOrQuery {
    --
    discriminator:
    GeographicAddressRef
    GeographicSiteRef
    GeographicAddress_Query
}
PlaceRefOrQuery ..> GeographicAddressRef : """"
PlaceRefOrQuery ..> GeographicSiteRef : """"
PlaceRefOrQuery ..> GeographicAddress_Query : """"

class Price {

    taxRate: float
}

Price *--> Money : taxIncludedAmount
Price *-->"1" Money : dutyFreeAmount


class ProductOfferingRef {

    href: string
    id*: string
}



class ProductPrice {

    unitOfMeasure: string
    name: string
    priceType*: MEFPriceType
    description: string
}

ProductPrice *-->"1" Price : price
ProductPrice *--> Duration : recurringChargePeriod


class ProductRelationship {

    relationshipType*: string
    id*: string
    href: string
}



class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress


class RelatedPlaceRefOrQuery {

    role*: string
}

RelatedPlaceRefOrQuery *-->"1" PlaceRefOrQuery : place
RelatedPlaceRefOrQuery *-->"*" ContactInformation : contact


class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



enum TimeUnit {

    seconds
    minutes
    businessHours
    calendarHours
    businessDays
    calendarDays
    months
    years
}
@enduml
