@startuml

hide empty description


[*] --[hidden]> pendingActive

pendingActive --[hidden]> active.pendingChange
pendingActive --[hidden]> active
pendingActive --[hidden]> pendingTerminate
cancelled --[hidden]> pendingTerminate

active --[hidden]> suspended
pendingTerminate --[hidden]> suspendedPendingTerminate
pendingTerminate --[hidden]> terminated

terminated --[hidden]> [*]
note right : Final state

[*] -[norank]> active : Product instantiated in inventory\nwhile Product Order is completed
[*] -[norank]> pendingActive : Product instantiated in inventory\nwhile Product Order is in progress

pendingActive -[norank]> active : Product Order\nCompleted
pendingActive -[norank]> cancelled : Product Order\nCancelled

cancelled -[norank]> [*]

active -[norank]> active.pendingChange : Change in progress
active -[norank]> suspended : Suspension
active -[norank]> pendingTerminate : Waiting for Termination

active.pendingChange -[norank]> active : Change order in final state

suspended -[norank]> active : Reactivation
suspended -[norank]> suspendedPendingTerminate : Waiting for Termination

pendingTerminate -[norank]> active : Termination Failed\n or Cancelled
pendingTerminate -[norank]> terminated : Termination

suspendedPendingTerminate -[norank]> suspended : Termination Failed\n or Cancelled
suspendedPendingTerminate -[norank]> terminated : Termination

terminated -[norank]> [*]


@enduml