@startuml


class ContactInformation {

    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation

}


class Duration {

    amount*: integer
    units*: TimeUnit
}



class MEFBillingAccountRef {

    id*: string
}


class MEFItemTerm {

    endOfTermAction*: MEFEndOfTermAction
    name*: string
    description: string
}

MEFItemTerm *-->"1" Duration : duration
MEFItemTerm *--> Duration : rollInterval

class MEFProduct {

    id*: string
    href: string
    startDate*: date-time
    externalId: string
    status*: MEFProductStatusType
    lastUpdateDate: date-time
    agreementName: string
    terminationDate: date-time
    @type: string
}

MEFProduct *-->"*" MEFProductStatusChange : statusChange
MEFProduct *--> ProductSpecificationRef : productSpecification
MEFProduct *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct *--> ProductOfferingRef : productOffering
MEFProduct *-->"*" RelatedContactInformation : relatedContactInformation
MEFProduct *--> MEFBillingAccountRef : billingAccount
MEFProduct *-->"*" MEFProductOrderItemRef : productOrderItem
MEFProduct *-->"*" MEFItemTerm : productTerm
MEFProduct *--> MEFProductConfiguration : productConfiguration
MEFProduct *-->"*" ProductRelationship : productRelationship
MEFProduct *-->"*" ProductPrice : productPrice


class MEFProductConfiguration {

    @type*: string
}



class MEFProductOrderItemRef {

    productOrderHref: string
    productOrderItemId*: string
    productOrderId*: string
}



class MEFProductStatusChange {

    changeReason: string
    changeDate*: date-time
    status*: MEFProductStatusType
}


class Money {

    unit*: string
    value*: float
}



class PlaceRefOrQuery {

}



class Price {

    taxRate: float
}

Price *--> Money : taxIncludedAmount
Price *-->"1" Money : dutyFreeAmount


class ProductOfferingRef {

    href: string
    id*: string
}



class ProductPrice {

    unitOfMeasure: string
    name: string
    priceType*: MEFPriceType
    description: string
}

ProductPrice *-->"1" Price : price
ProductPrice *--> Duration : recurringChargePeriod


class ProductRelationship {

    relationshipType*: string
    id*: string
    href: string
}



class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


class RelatedPlaceRefOrQuery {

    role*: string
}

RelatedPlaceRefOrQuery *-->"1" PlaceRefOrQuery : place
RelatedPlaceRefOrQuery *-->"*" ContactInformation : contact


class MEFProduct_Find {

    externalId: string
    id*: string
    href: string
    lastUpdateDate: date-time
    startDate: date-time
    status*: MEFProductStatusType
}

MEFProduct_Find *--> ProductSpecificationRef : productSpecification
MEFProduct_Find *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct_Find *--> ProductOfferingRef : productOffering
MEFProduct_Find *-->"*" ProductRelationship : productRelationship
MEFProduct_Find *--> MEFBillingAccountRef : billingAccount
MEFProduct_Find *-->"*" MEFProductOrderItemRef : productOrderItem

@enduml
