@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class FieldedAddress {

    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    streetName*: string
    streetNr: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetNrSuffix: string
    streetSuffix: string
    streetType: string
}

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class GeographicSubAddress {

    buildingName: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFBillingAccount {

    id*: string
    agreementName: string
}

MEFBillingAccount *--> RelatedContactInformation : billingContact


class MEFProductOrderItemRef {

    productOrderItemId*: string
    productOrderHref: string
    productOrderId*: string
}



class MEFProduct_Find {

    id*: string
    href: string
    externalId: string
    lastUpdateDate: date-time
    startDate: date-time
    status*: MEFProductStatusType
}

MEFProduct_Find *--> MEFBillingAccount : billingAccount
MEFProduct_Find *--> ProductOfferingRef : productOffering
MEFProduct_Find *-->"*" MEFProductOrderItemRef : productOrderItem
MEFProduct_Find *-->"*" ProductRelationship : productRelationship
MEFProduct_Find *--> ProductSpecificationRef : productSpecification
MEFProduct_Find *-->"*" RelatedGeographicSite : relatedSite

class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedGeographicSite {

    id*: string
    href: string
    role*: string
}



enum MEFProductStatusType {

    active
    active.pendingChange
    cancelled
    pendingActive
    pendingTerminate
    suspended
    suspendedPendingTerminate
    terminated
}


class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class ProductOfferingRef {

    href: string
    id*: string
}




class ProductRelationship {

    id*: string
    href: string
    relationshipType*: string
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddress : postalAddress


@enduml
