@startuml


class MEFBillingAccountRef {

    id*: string
}


class MEFProductOrderItemRef {

    productOrderItemId*: string
    productOrderHref: string
    productOrderId*: string
}



class MEFProduct_Find {

    externalId: string
    id*: string
    href: string
    lastUpdateDate: date-time
    startDate: date-time
    status*: MEFProductStatusType
}

MEFProduct_Find *--> ProductSpecificationRef : productSpecification
MEFProduct_Find *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct_Find *--> ProductOfferingRef : productOffering
MEFProduct_Find *-->"*" ProductRelationship : productRelationship
MEFProduct_Find *--> MEFBillingAccountRef : billingAccount
MEFProduct_Find *-->"*" MEFProductOrderItemRef : productOrderItem

class ProductSpecificationRef {

    href: string
    id*: string
}



enum MEFProductStatusType {

    active
    active.pendingChange
    cancelled
    pendingActive
    pendingTerminate
    suspended
    suspendedPendingTerminate
    terminated
}

class ProductOfferingRef {

    href: string
    id*: string
}




class ProductRelationship {

    id*: string
    href: string
    relationshipType*: string
}
class RelatedPlaceRefOrQuery {

    <<skipped>>
}



@enduml
