@startuml


class ContactInformation {

    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation

}


class Duration {

    amount*: integer
    units*: TimeUnit
}



class MEFBillingAccountRef {

    id*: string
}



enum MEFEndOfTermAction {

    roll
    autoDisconnect
    autoRenew
}
class MEFItemTerm {

    endOfTermAction*: MEFEndOfTermAction
    name*: string
    description: string
}

MEFItemTerm *-->"1" Duration : duration
MEFItemTerm *--> Duration : rollInterval


enum MEFPriceType {

    recurring
    nonRecurring
    usageBased
}
class MEFProduct {

    id*: string
    href: string
    startDate*: date-time
    externalId: string
    status*: MEFProductStatusType
    lastUpdateDate: date-time
    agreementName: string
    terminationDate: date-time
    @type: string
}

MEFProduct *-->"*" MEFProductStatusChange : statusChange
MEFProduct *--> ProductSpecificationRef : productSpecification
MEFProduct *-->"*" RelatedPlaceRefOrQuery : place
MEFProduct *--> ProductOfferingRef : productOffering
MEFProduct *-->"*" RelatedContactInformation : relatedContactInformation
MEFProduct *--> MEFBillingAccountRef : billingAccount
MEFProduct *-->"*" MEFProductOrderItemRef : productOrderItem
MEFProduct *-->"*" MEFItemTerm : productTerm
MEFProduct *--> MEFProductConfiguration : productConfiguration
MEFProduct *-->"*" ProductRelationship : productRelationship
MEFProduct *-->"*" ProductPrice : productPrice


class MEFProductConfiguration {

    @type*: string
}



class MEFProductOrderItemRef {

    productOrderHref: string
    productOrderItemId*: string
    productOrderId*: string
}



class MEFProductStatusChange {

    changeReason: string
    changeDate*: date-time
    status*: MEFProductStatusType
}



enum MEFProductStatusType {

    active
    active.pendingChange
    cancelled
    pendingActive
    pendingTerminate
    suspended
    suspendedPendingTerminate
    terminated
}

class Money {

    unit*: string
    value*: float
}



class PlaceRefOrQuery {

}



class Price {

    taxRate: float
}

Price *--> Money : taxIncludedAmount
Price *-->"1" Money : dutyFreeAmount


class ProductOfferingRef {

    href: string
    id*: string
}



class ProductPrice {

    unitOfMeasure: string
    name: string
    priceType*: MEFPriceType
    description: string
}

ProductPrice *-->"1" Price : price
ProductPrice *--> Duration : recurringChargePeriod


class ProductRelationship {

    relationshipType*: string
    id*: string
    href: string
}



class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


class RelatedPlaceRefOrQuery {

    role*: string
}

RelatedPlaceRefOrQuery *-->"1" PlaceRefOrQuery : place
RelatedPlaceRefOrQuery *-->"*" ContactInformation : contact


enum TimeUnit {

    seconds
    minutes
    businessHours
    calendarHours
    businessDays
    calendarDays
    months
    years
}
@enduml
