@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class MEFBillingAccountRef {

    id*: string
}


class MEFProductOrderItemRef {

    productOrderItemId*: string
    productOrderHref: string
    productOrderId*: string
}



class MEFProduct_Find {

    id*: string
    href: string
    externalId: string
    lastUpdateDate: date-time
    startDate: date-time
    status*: MEFProductStatusType
}

MEFProduct_Find *--> MEFBillingAccountRef : billingAccount
MEFProduct_Find *--> ProductOfferingRef : productOffering
MEFProduct_Find *-->"*" MEFProductOrderItemRef : productOrderItem
MEFProduct_Find *-->"*" ProductRelationship : productRelationship
MEFProduct_Find *--> ProductSpecificationRef : productSpecification
MEFProduct_Find *-->"*" RelatedGeographicSite : relatedSite

class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedGeographicSite {

    id*: string
    href: string
    role*: string
}



enum MEFProductStatusType {

    active
    active.pendingChange
    cancelled
    pendingActive
    pendingTerminate
    suspended
    suspendedPendingTerminate
    terminated
}

class ProductOfferingRef {

    href: string
    id*: string
}




class ProductRelationship {

    id*: string
    href: string
    relationshipType*: string
}



@enduml
