@startuml

left to right direction
actor Seller
actor Buyer

rectangle {

Buyer --> (1. Retrieve Product List)
Buyer --> (2. Retrieve Product by Identifier)

}
Seller -[hidden]up-> (1. Retrieve Product List)
Seller -[hidden]up-> (2. Retrieve Product by Identifier)
@enduml
