//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDate;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * 
 * 
 * <p>Java class for ProductOfferingQualificationItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductOfferingQualificationItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="desiredActivationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="state" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}state" minOccurs="0"/&gt;
 *         &lt;element name="serviceabilityConfidence" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}serviceabilityColor" minOccurs="0"/&gt;
 *         &lt;element name="estimatedResponseDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="serviceConfidenceReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="installationInterval" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}TimeInterval" minOccurs="0"/&gt;
 *         &lt;element name="MPOE" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="product" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}Product" minOccurs="0"/&gt;
 *         &lt;element name="productOfferingRef" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}ProductOfferingRef" minOccurs="0"/&gt;
 *         &lt;element name="productOfferingQualificationItemRelationship" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}productOfferingQualificationItemRelationship" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="alternateProductProposal" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}AlternateProductProposal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="terminationError" type="{http://orange.com/POC_ONAP/api/productOfferingQualification/v0/model}TerminationError" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductOfferingQualificationItem", propOrder = {
    "id",
    "desiredActivationDate",
    "state",
    "serviceabilityConfidence",
    "estimatedResponseDate",
    "serviceConfidenceReason",
    "installationInterval",
    "mpoe",
    "product",
    "productOfferingRef",
    "productOfferingQualificationItemRelationship",
    "alternateProductProposal",
    "terminationError"
})
public class ProductOfferingQualificationItemEntity
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String id;
    @XmlSchemaType(name = "date")
    protected Date desiredActivationDate;
    @XmlSchemaType(name = "string")
    protected StateEntity state;
    @XmlSchemaType(name = "string")
    protected ServiceabilityColorEntity serviceabilityConfidence;
    @XmlSchemaType(name = "date")
    protected Date estimatedResponseDate;
    protected String serviceConfidenceReason;
    protected TimeIntervalEntity installationInterval;
    @XmlElement(name = "MPOE")
    protected Boolean mpoe;
    protected ProductEntity product;
    protected ProductOfferingRefEntity productOfferingRef;
    protected List<ProductOfferingQualificationItemRelationshipEntity> productOfferingQualificationItemRelationship;
    protected List<AlternateProductProposalEntity> alternateProductProposal;
    protected List<TerminationErrorEntity> terminationError;


    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the desiredActivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDesiredActivationDate() {
        return desiredActivationDate;
    }

    /**
     * Sets the value of the desiredActivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDesiredActivationDate(Date value) {
        this.desiredActivationDate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateEntity }
     *     
     */
    public StateEntity getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateEntity }
     *     
     */
    public void setState(StateEntity value) {
        this.state = value;
    }

    /**
     * Gets the value of the serviceabilityConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceabilityColorEntity }
     *     
     */
    public ServiceabilityColorEntity getServiceabilityConfidence() {
        return serviceabilityConfidence;
    }

    /**
     * Sets the value of the serviceabilityConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceabilityColorEntity }
     *     
     */
    public void setServiceabilityConfidence(ServiceabilityColorEntity value) {
        this.serviceabilityConfidence = value;
    }

    /**
     * Gets the value of the estimatedResponseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getEstimatedResponseDate() {
        return estimatedResponseDate;
    }

    /**
     * Sets the value of the estimatedResponseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedResponseDate(Date value) {
        this.estimatedResponseDate = value;
    }

    /**
     * Gets the value of the serviceConfidenceReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceConfidenceReason() {
        return serviceConfidenceReason;
    }

    /**
     * Sets the value of the serviceConfidenceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceConfidenceReason(String value) {
        this.serviceConfidenceReason = value;
    }

    /**
     * Gets the value of the installationInterval property.
     * 
     * @return
     *     possible object is
     *     {@link TimeIntervalEntity }
     *     
     */
    public TimeIntervalEntity getInstallationInterval() {
        return installationInterval;
    }

    /**
     * Sets the value of the installationInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeIntervalEntity }
     *     
     */
    public void setInstallationInterval(TimeIntervalEntity value) {
        this.installationInterval = value;
    }

    /**
     * Gets the value of the mpoe property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMPOE() {
        return mpoe;
    }

    /**
     * Sets the value of the mpoe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMPOE(Boolean value) {
        this.mpoe = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductEntity }
     *     
     */
    public ProductEntity getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductEntity }
     *     
     */
    public void setProduct(ProductEntity value) {
        this.product = value;
    }

    /**
     * Gets the value of the productOfferingRef property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOfferingRefEntity }
     *     
     */
    public ProductOfferingRefEntity getProductOfferingRef() {
        return productOfferingRef;
    }

    /**
     * Sets the value of the productOfferingRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOfferingRefEntity }
     *     
     */
    public void setProductOfferingRef(ProductOfferingRefEntity value) {
        this.productOfferingRef = value;
    }

    /**
     * Gets the value of the productOfferingQualificationItemRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productOfferingQualificationItemRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductOfferingQualificationItemRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductOfferingQualificationItemRelationshipEntity }
     * 
     * 
     */
    public List<ProductOfferingQualificationItemRelationshipEntity> getProductOfferingQualificationItemRelationship() {
        if (productOfferingQualificationItemRelationship == null) {
            productOfferingQualificationItemRelationship = new ArrayList<ProductOfferingQualificationItemRelationshipEntity>();
        }
        return this.productOfferingQualificationItemRelationship;
    }

    /**
     * 
     * 
     */
    public void setProductOfferingQualificationItemRelationship(List<ProductOfferingQualificationItemRelationshipEntity> productOfferingQualificationItemRelationship) {
        this.productOfferingQualificationItemRelationship = productOfferingQualificationItemRelationship;
    }

    /**
     * Gets the value of the alternateProductProposal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateProductProposal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateProductProposal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternateProductProposalEntity }
     * 
     * 
     */
    public List<AlternateProductProposalEntity> getAlternateProductProposal() {
        if (alternateProductProposal == null) {
            alternateProductProposal = new ArrayList<AlternateProductProposalEntity>();
        }
        return this.alternateProductProposal;
    }

    /**
     * 
     * 
     */
    public void setAlternateProductProposal(List<AlternateProductProposalEntity> alternateProductProposal) {
        this.alternateProductProposal = alternateProductProposal;
    }

    /**
     * Gets the value of the terminationError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminationError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminationError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminationErrorEntity }
     * 
     * 
     */
    public List<TerminationErrorEntity> getTerminationError() {
        if (terminationError == null) {
            terminationError = new ArrayList<TerminationErrorEntity>();
        }
        return this.terminationError;
    }

    /**
     * 
     * 
     */
    public void setTerminationError(List<TerminationErrorEntity> terminationError) {
        this.terminationError = terminationError;
    }




}
