//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceabilityColor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceabilityColor"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GREEN"/&gt;
 *     &lt;enumeration value="RED"/&gt;
 *     &lt;enumeration value="YELLOW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "serviceabilityColor")
@XmlEnum
public enum ServiceabilityColorEntity {

    GREEN,
    RED,
    YELLOW;

    public String value() {
        return name();
    }

    public static ServiceabilityColorEntity fromValue(String v) {
        return valueOf(v);
    }

}
