//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 10:41:50 AM CEST 
//


package com.orange.onapbss.datamodel.productofferingq;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="timeUnit"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SECS"/&gt;
 *     &lt;enumeration value="MINS"/&gt;
 *     &lt;enumeration value="HOURS"/&gt;
 *     &lt;enumeration value="BUSINESS_DAYS"/&gt;
 *     &lt;enumeration value="CALENDAR_DAYS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "timeUnit")
@XmlEnum
public enum TimeUnitEntity {

    SECS,
    MINS,
    HOURS,
    BUSINESS_DAYS,
    CALENDAR_DAYS;

    public String value() {
        return name();
    }

    public static TimeUnitEntity fromValue(String v) {
        return valueOf(v);
    }

}
