@startuml


class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit


class FormattedAddressRepresentation {

    formattedAddress*: string
    language: string
}



class GeographicAddress {

    id*: string
    href: string
    hasPublicSite*: TrueFalseUnknown
    allowsNewSite*: TrueFalseUnknown
}

GeographicAddress *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress *-->"*" LabelRepresentation : labelRepresentation


class GeographicAddressValidation {

    id: string
    state*: GeographicAddressValidationStateType
}
GeographicAddressValidation_Create <|-- GeographicAddressValidation

GeographicAddressValidation *-->"1..*" GeographicAddress : alternateGeographicAddress
GeographicAddressValidation *-->"1" GeographicAddress : bestMatchGeographicAddress


enum GeographicAddressValidationStateType {

    acknowledged
    inProgress
    ready
    rejected
}
class GeographicAddressValidation_Create {

    instantSyncValidation*: boolean
}

GeographicAddressValidation_Create *-->"1" GeographicAddress_Query : submittedGeographicAddress


class GeographicAddress_Query {
    @type*: string 
}

GeographicAddress_Query *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress_Query *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress_Query *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress_Query *-->"*" LabelRepresentation : labelRepresentation


class GeographicPointRepresentation {

    spatialRef*: string
    latitude*: string
    longitude*: string
    elevation: string
}



class LabelRepresentation {

    label*: string
    administrativeAuthority*: string
    language: string
}



class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



enum TrueFalseUnknown {

    true
    false
    unknown
}
@enduml
