@startuml

enum OrderItemAction {
   INSTALL
   CHANGE
   DISCONNECT
   NO_CHANGE
}
enum OrderStatus {
   ACKNOWLEDGED
   REJECTED
   IN_PROGRESS
   PENDING
   HELD
   ASSESSING_CANCELLATION
   PENDING_CANCELLATION
   CANCELLED
   CONFIGURED
   CONFIRMED
   JEOPARDY
   FAILED
   PARTIAL
   COMPLETED
}
enum RelationshipType {
   RELIES_ON
   BUNDLED
   COMES_FROM
}
enum OrderActivity {
   INSTALL
   CHANGE
   DISCONNECT
}
enum DesiredOrderResponses {
   CONFIRMATION_AND_ENGINEERING_DESIGN
   CONFIRMATION_ONLY
   NONE
}
enum PricingMethod {
   TARIFF
   CONTRACT
   INDIVIDUAL_CASE_BASIS
   OTHER
}
enum OrderItemStatus {
   ACKNOWLEDGED
   REJECTED
   IN_PROGRESS
   PENDING
   HELD
   ASSESSING_CANCELLATION
   PENDING_CANCELLATION
   CANCELLED
   CONFIGURED
   FAILED
   COMPLETED
}
enum OrderItemRequestedState {
   CANCELLED
}

class ErrorRepresentation {
   code:int
   reason:string
   message:string
   status:int
   referenceError:string
   @type:string
   @schemaLocation:string
}

class BillingAccountRef {
   id:string
}

class Place {
   id:string
   href:string
   role:string
   @referredType:string
   @schemaLocation:string
}

class ProductOrder {
   id:string
   href:string
   externalId:string
   orderDate:dateTime
   requestedStartDate:dateTime
   requestedCompletionDate:dateTime
   completionDate:dateTime
   expeditePriority:int
   orderVersion:string
   projectId:string
   tspRestorationPriority:string
   @type:string
   @schemaLocation:string
   @baseType:string
}
   ProductOrder --> "1-1" OrderStatus : state
   ProductOrder --> "1-1" OrderActivity : orderActivity
   ProductOrder --> "1-1" DesiredOrderResponses : desiredResponses
   ProductOrder --> "0-*" RelatedParty : relatedParty
   ProductOrder --> "0-1" Note : note
   ProductOrder --> "0-*" OrderItem : orderItem

class Note {
   text:string
   date:dateTime
   author:string
}

class OrderItem {
   id:string
   pricingReference:string
   pricingTerm:int
   @type:string
   @schemaLocation:string
}
   OrderItem --> "1-1" OrderItemAction : action
   OrderItem --> "1-1" OrderItemStatus : state
   OrderItem --> "0-1" PricingMethod : pricingMethod
   OrderItem --> "0-1" BillingAccountRef : billingAccount
   OrderItem --> "0-1" ProductOfferingRef : productOffering
   OrderItem --> "0-1" Product : product
   OrderItem --> "0-*" OrderItemRelationShip : orderItemRelationship
   OrderItem --> "0-*" QualificationRef : qualification

class ProductOfferingRef {
   id:string
}

class Product {
   id:string
   @type:string
}
   Product --> "0-1" ProductSpecification : productSpecification
   Product --> "0-*" Place : place
   Product --> "0-*" RelatedParty : relatedParty
   Product --> "0-*" ProductRelationship : productRelationship

class OrderItemRelationShip {
   id:string
}
   OrderItemRelationShip --> "1-1" RelationshipType : type

class ProductRelationship
   ProductRelationship --> "1-1" RelationshipType : type
   ProductRelationship --> "1-1" ProductRef : product

class ProductRef {
   id:string
}

class Hub {
   id:string
   query:string
   callback:string
}

class QualificationRef {
   id:string
   href:string
   qualificationItem:string
   @referredType:string
}

class RelatedParty {
   id:string
   href:string
   @referredType:string
   role:string
   name:string
   emailAddress:string
   number:string
   numberExtension:string
}

class CreateProductOrder {
   externalId:string
   requestedCompletionDate:dateTime
   requestedStartDate:dateTime
   expeditePriority:int
   @type:string
   @schemaLocation:string
   @baseType:string
   orderVersion:string
   projectId:string
   tspRestorationPriority:string
}
   CreateProductOrder --> "1-1" OrderActivity : orderActivity
   CreateProductOrder --> "1-1" DesiredOrderResponses : desiredResponse
   CreateProductOrder --> "0-*" RelatedParty : relatedParty
   CreateProductOrder --> "0-1" Note : note
   CreateProductOrder --> "0-*" CreateOrderItem : orderItem

class ProductSpecification {
   id:string
}
   ProductSpecification --> "0-1" Describing : describing

class Describing {
   @type:string
   @schemaLocation:string
}

class CreateOrderItem {
   id:string
   pricingReference:string
   pricingTerm:int
   @type:string
   @schemaLocation:string
}
   CreateOrderItem --> "1-1" OrderItemAction : action
   CreateOrderItem --> "0-1" PricingMethod : pricingMethod
   CreateOrderItem --> "0-1" BillingAccountRef : billingAccount
   CreateOrderItem --> "1-1" ProductOfferingRef : productOffering
   CreateOrderItem --> "0-1" Product : product
   CreateOrderItem --> "0-*" OrderItemRelationShip : orderItemRelationship
   CreateOrderItem --> "0-*" QualificationRef : qualification

class ProductOrderSummary {
   id:string
   externalId:string
   orderDate:dateTime
   requestedCompletionDate:dateTime
   projectId:string
}
   ProductOrderSummary --> "1-1" OrderStatus : state

class CancelOrderResponse {
   id:string
   cancellationDeniedReason:string
}
   CancelOrderResponse --> "1-1" OrderStatus : state

class UpdateOrderItem {
   id:string
   pricingReference:string
   pricingTerm:int
   @type:string
   @schemaLocation:string
}
   UpdateOrderItem --> "1-1" OrderItemAction : action
   UpdateOrderItem --> "0-1" OrderItemRequestedState : requestedState
   UpdateOrderItem --> "0-1" PricingMethod : pricingMethod
   UpdateOrderItem --> "0-1" BillingAccountRef : billingAccount
   UpdateOrderItem --> "0-1" ProductOfferingRef : productOffering
   UpdateOrderItem --> "0-1" Product : product
   UpdateOrderItem --> "0-*" OrderItemRelationShip : orderItemRelationship
   UpdateOrderItem --> "0-*" QualificationRef : qualification

class UpdateProductOrder {
   externalId:string
   requestedCompletionDate:dateTime
   requestedStartDate:dateTime
   expeditePriority:int
   orderVersion:string
   projectId:string
   tspRestorationPriority:string
   @type:string
   @schemaLocation:string
   @baseType:string
}
   UpdateProductOrder --> "0-1" OrderActivity : orderActivity
   UpdateProductOrder --> "0-1" DesiredOrderResponses : desiredResponse
   UpdateProductOrder --> "0-*" RelatedParty : relatedParty
   UpdateProductOrder --> "0-1" Note : note
   UpdateProductOrder --> "0-*" UpdateOrderItem : orderItem

@enduml