@startjson
#highlight "quoteItem" / "0"/ "action"
#highlight "quoteItem" / "0"/ "product" / "id"
#highlight "quoteItem" / "0"/ "product" / "productRelationship" / "1" / "relationshipType"
#highlight "quoteItem" / "0"/ "product" / "productRelationship" / "1" / "id"

{
  "requestedQuoteCompletionDate": "2022-11-28T22:00:00Z",
  "externalId": "BuyerQuote-00002",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProjectX",
  "instantSyncQuote": false,
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@example.com",
      "role": "buyerContactInformation",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "quoteItem": [
    {
      "id": "item-001",
      "action": "modify",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "relatedContactInformation": [
        {
          "number": "12-345-6789",
          "emailAddress": "john.example@example.com",
          "role": "quoteItemTechnicalContact",
          "organization": "Buyer Co.",
          "name": "John Example",
          "numberExtension": "1234"
        }
      ],
      "product": {
        "id": "AccessEline-0001",
        "productConfiguration": "<<skipped>>",
        "productOffering": {
          "id": "000073"
        },
        "productRelationship": [
          {
            "relationshipType": "CONNECTS_TO_ENNI",
            "id": "SP1_ENNI"
          },
          {
            "relationshipType": "CONNECTS_TO_UNI",
            "id": "NewYork_UNI"
          }
        ]
      }
    }
  ]
}
@endjson