@startjson
{
  "identifier": "SP1_ENNI-EP1",
  "maintenanceIntermediatePoint": "6",
  "ovcEgressMap": [
    {
      "mapType": "CN_PCP",
      "cnPcpEntries": [
        {
          "cosName": "low",
          "pcpValue": "1"
        }
      ]
    }
  ],
  "ovcEndPointMap": {
    "mapType": "FORM_E",
    "ovcEndPointMapFormE": [13]
  },
  "colorMap": {
    "mapType": "DEI"
  },
  "ingressClassOfServiceMap": {
    "mapType": "ENDPOINT",
    "map_M": "low",
    "l2cp_P": {
      "l2cpIdentifier": {
        "l2cpProtocolType": "LLC",
        "llcAddressOrEtherType": 66
      },
      "l2cpCosName": "low"
    }
  },
  "maintenanceEndPointList": [
    {
      "level": 7,
      "mepDirection": "UP"
    }
  ]
}
@endjson