@startjson
{
  "provideAlternative": false,
  "submittedGeographicAddress": {
    "@type": "FieldedAddress",
    "streetNr": "20",
    "streetNrSuffix": "14",
    "streetName": "Example",
    "city": "New York",
    "postcode": "10279",
    "country": "United States"
  }
}
@endjson