@startjson
{
  "@type": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all",
  "ceVlanIdPreservation": "PRESERVE",
  "cTagPcpPreservation": "ENABLED",
  "cTagDeiPreservation": "ENABLED",
  "maximumFrameSize": 1526,
  "ovcL2cpAddressSet": "CTA",
  "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "**listOfClassOfServiceNames**": ["**low**", "**high**"],
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeDuration": "<<skipped>>",
      "startTime":  "<<skipped>>"
    }
  ],
  "enniEp": {
    "identifier": "SP2_ENNI-EP1",
    "others": "<<skipped>>"
  },
  "uniEp": {
    "identifier": "NewYork_UNI-EP2",
    "others": "<<skipped>>"
  }
}



@endjson