@startjson

#highlight "productOrderItem" / "0"/ "action"
#highlight "productOrderItem" / "1"/ "action"

#highlight "productOrderItem" / "0" / "product" / "id"
#highlight "productOrderItem" / "1" / "product" / "id"

{
  "externalId": "BuyerOrder-00004",
  "projectId": "BuyerProjectX",
  "requestedCompletionDate": "2021-10-14T23:00:00Z",
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@example.com",
      "role": "productOrderContact",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "productOrderItem": [
    {
      "action": "delete",
      "id": "item-001",
      "product": {
        "id": "AccessEline-0001"
      }
    },
    {
      "action": "delete",
      "id": "item-002",
      "product": {
        "id": "NewYork_UNI"
      }
    }
  ]
}
@endjson