@startjson

{
  "identifier": "NewYork_UNI-EP2",
  "maintenanceIntermediatePoint": "6",
  "ovcEgressMap": [
    {
      "mapType": "CN_PCP",
      "cnPcpEntries": [
        {
          "cosName": "low",
          "pcpValue": "1"
        },
        {
          "cosName": "high",
          "pcpValue": "5"
        }
      ]
    }
  ],
  "ingressBandwidthProfilePerClassOfServiceName": [
    {
      "classOfServiceName": "low",
      "bwpFlow": {
        "eirMax": {
          "irValue": 70,
          "irUnits": "MBPS"
        },
        "envelopeRank": 1,
        "cirMax": {
          "irValue": 0,
          "irUnits": "MBPS"
        },
        "cbs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "couplingFlag": true,
        "envelopeId": "env2", 
        "tokenRequestOffset": 0,
        "ebs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "colorMode": "COLOR_BLIND",
        "cir": {
          "irValue": 0,
          "irUnits": "MBPS"
        },
        "eir": {
          "irValue": 40,
          "irUnits": "MBPS"
        }
      }
    },
    {
      "classOfServiceName": "high",
      "bwpFlow": {
        "eirMax": {
          "irValue": 50,
          "irUnits": "MBPS"
        },
        "envelopeRank": 2,
        "cirMax": {
          "irValue": 50,
          "irUnits": "MBPS"
        },
        "cbs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "couplingFlag": true,
        "envelopeId": "env2",
        "tokenRequestOffset": 0,
        "ebs": {
          "dataSizeUnits": "KBYTES",
          "dataSizeValue": 40
        },
        "colorMode": "COLOR_BLIND",
        "cir": {
          "irValue": 50,
          "irUnits": "MBPS"
        },
        "eir": {
          "irValue": 50,
          "irUnits": "MBPS"
        }
      }
    }
  ],
  "ovcEndPointMap": {
    "mapType": "FORM_U",
    "ovcEndPointMapFormU": [3]
  },
  "colorMap": {
    "mapType": "DEI"
  },
  "ingressClassOfServiceMap": {
    "mapType": "C_TAG_PCP",
    "map_M": [
      {
        "pcpVal": "0",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "1",
        "pcpCosName": "low"
      },
      {
        "pcpVal": "2",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "3",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "4",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "5",
        "pcpCosName": "high"
      },
      {
        "pcpVal": "6",
        "pcpCosName": "DISCARD"
      },
      {
        "pcpVal": "7",
        "pcpCosName": "DISCARD"
      },
      {
          "pcpVal": "UNTAGGED",
          "pcpCosName": "DISCARD"
      }
    ],
    "l2cp_P": {
      "l2cpIdentifier": {
        "l2cpProtocolType": "LLC",
        "llcAddressOrEtherType": "66"
      },
      "l2cpCosName": "high"
    }
  },
  "maintenanceEndPointList": [
    {
      "level": 7,
      "mepDirection": "UP"
    }
  ]
}

@endjson