@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductConfiguration>> FireBrick
}

class MEFProductRefOrValueForQuote{

    href: string 
    id: string 
}


class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


MEFProductRefOrValueForQuote*-->"0..1" MEFProductConfiguration : productConfiguration

class accessElineOperatorUniQuote <<ProductConfiguration>> {
    @type*: string = accessElineOperatorUniQuote
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- accessElineOperatorUniQuote


class accessElineOvcQuote <<ProductConfiguration>> {
    @type*: string = accessElineOvcQuote
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- accessElineOvcQuote

@enduml
