@startuml


skinparam activity {
    BackgroundColor White
    BorderColor Black
}

start
if(immediate response?) then (yes)
    if(sufficient information?) then (no)
        :cancelled.
        insufficientInformationProvided;
    elseif(able to quote all items?) then (no)
        :cancelled.
        unableToProvide;
    else(yes)
        :approved.
        answered;
        :rejected.
        expired;
    endif
else (no)
    :inProgress;
    if(cancelled by the Buyer?) then (no)
      if(sufficient information?) then (no)
          :cancelled.
          insufficientInformationProvided;
      elseif(able to quote all items?) then (no)
          :cancelled.
          unableToProvide;
      else(yes)
          :approved.
          answered;
          :rejected.
          expired;
      endif
    else(yes)
      :cancelled;
    endif
endif

stop

@enduml