@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/hub with {{callback}} details
Seller --> Buyer: notification confirmation with {{id}}
...
Buyer -> Seller : POST {{baseUrl}}/quote (instantSyncQuote=false)
Seller -> Seller : validate Request

alt succesful inquiry (<30sec)
Seller -> Buyer:  {{callbackUrl}}/listener/QuoteCreateEvent
Seller -> Buyer: {{callbackUrl}}/listener/QuoteStateChangeEvent
Seller --> Buyer : 201 Quote with {{id}} in completion state

else validation or internal problem

Seller --> Buyer : 4xx or 5xx errorresponse
end 
...
Buyer -> Seller : DELETE {{baseUrl}}/hub/{{id}} 

@enduml