@startuml
hide footbox

hide footbox

participant Buyer
participant Seller


Buyer -> Seller : POST {{baseUrl}}/quote (instantSyncQuote=false)
Seller -> Seller : validate Request

alt succesful inquiry

    Seller --> Buyer : 201 Quote with {{id}}, "inProgress" state
    loop until Quote in completion state
        Buyer -> Seller :   GET {{baseUrl}}/Quote/{{id}}
        return Quote in current state
    end
else validation or internal problem

Seller --> Buyer : 4xx or 5xx error response

end 
@enduml