@startuml

left to right direction
actor Seller
actor Buyer

rectangle {

Buyer --> (1. Create Quote Request)
    (1. Create Quote Request) --> (1c. Deferred Quote Response, \n Immediate Response Provided)
    (1. Create Quote Request) --> (1b. Deferred Quote Response, \n Deferred Response Provided)
    (1. Create Quote Request) --> (1a. Immediate Quote Response)
    

Buyer --> (2. Retrieve Quote List)
Buyer --> (3. Retrieve Quote by Quote Identifier)
Buyer --> (4. Cancel Quote by Quote Identifier)
Buyer --> (5. Reject Quote by Quote Identifier)
Buyer --> (6. Register for Quote Notification)
(7. Send Quote Notification) <-- Seller
}

@enduml
