@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/hub with {{callback}} details
return notification confirmation with {{id}}

...

Buyer -> Seller : POST {{baseUrl}}/cancelQuote
return confirmation

...

Seller -> Buyer: {{callbackUrl}}/listener/QuoteStateChangeEvent

Buyer -> Seller :   GET {{baseUrl}}/quote/{{id}}
return Quote in current state

@enduml