skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}

class Error400 {

    code*: String
}
Error <|-- Error400

class Error401 {

    code*: String
}
Error <|-- Error401



class Error403 {

    code*: String
}
Error <|-- Error403



class Error404 {

    code*: String
}
Error <|-- Error404

class Error408 {

    code*: String
}
Error <|-- Error408

class Error422 {

    code*: String
    propertyPath: String
}
Error <|-- Error422



class Error500 {

    code*: String
}
Error <|-- Error500



class Error501 {

    code*: String
}
Error <|-- Error501



class Error {

    message: String
    reason*: String
    referenceError: Uri
    status: String
}