@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}

class AlternateProductOfferingProposal {
}

AlternateProductOfferingProposal *-->"1" MEFProductExtension : alternateProduct

class MEFProductExtension {

}

class MEFProductConfiguration {
    @type*: string <<discriminator>>
}

MEFProductExtension *-->"1" MEFProductConfiguration : productConfiguration


class MEFProductRefOrValue {

    @type*: string <<discriminator>>
    href: string 
    id: string 
}

MEFProductRefOrValue *-->"0..1" MEFProductConfiguration : productConfiguration


class accessElineOperatorUniPOQ <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- accessElineOperatorUniPOQ



class accessElineOvcPOQ <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- accessElineOvcPOQ

@enduml
