@startuml
hide footbox

hide footbox
skinparam {
    ParticipantBackgroundColor White
    ParticipantBorderColor Black
}

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/productOfferingQualification

alt succesful inquiry
Seller --> Buyer : 201 POQ in terminal state

else validation or internal problem

Seller --> Buyer : 4xx or 5xx response

end 
@enduml