@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class AlternateProductOfferingProposal {

    id*: string 
}

AlternateProductOfferingProposal *-->"1" MEFProductExtension : alternateProduct


enum EnniTokenShare {

    ENABLED
    DISABLED
}
enum Field_F {

    DSCP
}
class OneWayConsecutiveHighLossIntervalPmMetric {

    consecutiveNumberP: integer 
    oneWayChliObjective: integer 
    orderedPairs: OrderedPair[] 
}



class OneWayMeanFrameDelayRangePmMetric {

    oneWayFdrPercentile: Percentage 
    oneWayFdrObjective: Time 
    orderedPairs: OrderedPair[] 
}



class OrderedPair {

    toUni: string 
    fromUni: string 
    uuid: string 
}



class Percentage {

}



enum SVlanIdControl {

    FULL
    PARTIAL
}
enum ConnectorType {

    SC
    LC
    RJ45
    OTHER
}
enum LagLinkMeg {

    ENABLED
    DISABLED
}
class MEFProductConfiguration {

    @type*: string 
    @schemaLocation: uri 
}



class MEFProductExtension {

}

MEFProductExtension *--> MEFProductConfiguration : productConfiguration


class MEFProductRefOrValue {

    @type*: string 
    href: string 
    id: string 
}

MEFProductRefOrValue *--> MEFProductConfiguration : productConfiguration


class OneWayAvailabilityPmMetric {

    oneWayAvailabilityObjective: Percentage 
    orderedPairs: OrderedPair[] 
}



class OneWayCompositePmMetric {

    oneWayIfdvThreshold: Time 
    cpmObjective: Percentage 
    compositeFrameDelay: integer 
    compositeFrameDelayVariation: integer 
    oneWayFdThreshold: Time 
    compositeFrameLoss: integer 
    orderedPairs: OrderedPair[] 
    compositePerformanceIndicatorThreshold: number 
}



class OneWayFrameDelayPmMetric {

    oneWayFdObjective: Time 
    oneWayFdPercentile: Percentage 
    orderedPairList: OrderedPair[] 
}



class OneWayFrameLossRatioPmMetric {

    oneWayFrameLossRatioObjective: Percentage 
    orderedPairs: OrderedPair[] 
}



class OneWayGroupAvailabilityPmMetric {

    minimumNumberOfSetsAvailableK: integer 
    oneWayGroupAvailabilityObjective: Percentage 
}

OneWayGroupAvailabilityPmMetric *-->"*" SetOfOrderedPairs : setOfOrderedPairs


class OneWayHighLossIntervalPmMetric {

    oneWayHighLossIntervalsObjective: integer 
    orderedPairs: OrderedPair[] 
}



class OneWayInterFrameDelayVariationPmMetric {

    oneWayIfdvPercentile: Percentage 
    oneWayIfdvObjective: Time 
    timeDuration: Time 
    orderedPairs: OrderedPair[] 
}



class OneWayMeanFrameDelayPmMetric {

    oneWayMfdObjective: Time 
    orderedPairs: OrderedPair[] 
}

class SetOfOrderedPairs {

    orderedPairsList: OrderedPair[] 
}



class SlsCosNameEntry {

    thresholdC: number 
    consecutiveIntervalN: integer 
    deltaT: integer 
    cosName: string 
}

SlsCosNameEntry *-->"*" SlsObjectiveAndParameters : slsObjectiveAndParameterList


class SlsObjectiveAndParameters {

}

SlsObjectiveAndParameters *-->"*" OneWayMeanFrameDelayRangePmMetric : oneWayMeanFrameDelayRangePmMetric
SlsObjectiveAndParameters *-->"*" OneWayAvailabilityPmMetric : oneWayAvailabilityPmMetric
SlsObjectiveAndParameters *-->"*" OneWayCompositePmMetric : oneWayCompositePmMetric
SlsObjectiveAndParameters *-->"*" OneWayFrameDelayPmMetric : oneWayFrameDelayPmMetric
SlsObjectiveAndParameters *-->"*" OneWayInterFrameDelayVariationPmMetric : oneWayInterFrameDelayVariationPmMetric
SlsObjectiveAndParameters *-->"*" OneWayFrameLossRatioPmMetric : oneWayFrameLossRatioPmMetric
SlsObjectiveAndParameters *-->"*" OneWayMeanFrameDelayPmMetric : oneWayMeanFrameDelayPmMetric
SlsObjectiveAndParameters *-->"*" OneWayHighLossIntervalPmMetric : oneWayHighLossIntervalPmMetric
SlsObjectiveAndParameters *-->"*" OneWayGroupAvailabilityPmMetric : oneWayGroupAvailabilityPmMetric
SlsObjectiveAndParameters *-->"*" OneWayConsecutiveHighLossIntervalPmMetric : oneWayConsecutiveHighLossIntervalPmMetric


class Time {

    number: number 
    unit: TimeUnit 
}



class TimeAndDate {

    hour: integer 
    month: integer 
    year: integer 
    day: integer 
    minute: integer 
    second: integer 
}



class TimeInterval {

    amount*: integer 
    timeUnit*: TimeUnit 
}



class TimeIntervalT {

    number: integer 
    unit: Unit 
}



class accessElineEnniPOQ {

}
MEFProductConfiguration <|-- accessElineEnniPOQ

accessElineEnniPOQ *-->"1" objOperatorMultilateral : enniMultilateral
accessElineEnniPOQ *-->"1" objEnniService : enniService


class accessElineOperatorUniPOQ {

    connectorType*: ConnectorType[] 
    numberOfLinks: number 
    defaultCeVlanId: integer 
    physicalLayer*: string[] 
    maximumNumberOfCeVlanIdsPerOvcEndPoint: integer 
    lagLinkMeg: LagLinkMeg 
    l2cpAddressSet: L2cpAddressSet 
    linkOAM: LinkOAM 
    meg: Meg 
    synchronousMode: SynchronousMode 
    linkAggregation: LinkAggregation 
    maximumNumberOfOvcEndPoints: integer 
    tokenShare: TokenShare 
    maximumServiceFrameSize: number 
}
MEFProductConfiguration <|-- accessElineOperatorUniPOQ

accessElineOperatorUniPOQ *--> objConvToAggLink : portConversation
accessElineOperatorUniPOQ *--> ingressBandwidthProfile_oneOf : ingressBandwidthProfile
accessElineOperatorUniPOQ *--> egressBandwidthProfile_oneOf : egressBandwidthProfile
accessElineOperatorUniPOQ *-->"*" objL2cpIdentifer : l2cpPeering
accessElineOperatorUniPOQ *-->"*" objEnvelope : envelopes


class accessElineOvcPOQ {

    ceVlanIdPreservation: CeVlanIdPreservation 
    cTagPcpPreservation: CTagPcpPreservation 
    cTagDeiPreservation: CTagDeiPreservation 
    listOfClassOfServiceNames: string[] 
    availableMegLevel: number 
    l2cpAddressSet: accessElineOvcPOQL2cpAddressSet 
    maximumFrameSize: integer 
}
MEFProductConfiguration <|-- accessElineOvcPOQ

accessElineOvcPOQ *-->"1" objOvcEP : enniEP
accessElineOvcPOQ *--> objSLS : carrierEthernetSls
accessElineOvcPOQ *-->"1" objOvcEP : uniEP


class cosBWP_oneOf {

}
objBWP <|-- cosBWP_oneOf
objDisabled <|-- cosBWP_oneOf



class egressBandwidthProfile_oneOf {

}
objBWP <|-- egressBandwidthProfile_oneOf
objDisabled <|-- egressBandwidthProfile_oneOf



class ingressBandwidthProfilePerEndPoint_oneOf {

}
objBWP <|-- ingressBandwidthProfilePerEndPoint_oneOf
objDisabled <|-- ingressBandwidthProfilePerEndPoint_oneOf



class ingressBandwidthProfile_oneOf {

}
objBWP <|-- ingressBandwidthProfile_oneOf
objDisabled <|-- ingressBandwidthProfile_oneOf



class ingressClassOfServiceMap_oneOf {

}
objCosFromOvcEp <|-- ingressClassOfServiceMap_oneOf
objCosFromStagPcp <|-- ingressClassOfServiceMap_oneOf
objCosFromCtagPcp <|-- ingressClassOfServiceMap_oneOf
objCosFromDscp <|-- ingressClassOfServiceMap_oneOf



class vlanMap_oneOf {

}
objVlanRangeList <|-- vlanMap_oneOf
objAll <|-- vlanMap_oneOf



class objAll {

    constantAll*: ConstantAll 
}



class objCcDei {

    deiyellow*: Deiyellow 
    deigreen*: Deigreen 
    cosname*: string 
}



class objCosFromDscp {

    field_F*: Field_F 
}

objCosFromDscp *-->"1" objCosDscpMap : map_M
objCosFromDscp *-->"1" objCosL2cp : l2cp_P


class objDisabled {

    constantDisabled*: ConstantDisabled 
}



class objEnniService {

    maximumNumberOfOvcs: integer 
    enniTokenShare: EnniTokenShare 
    sVlanIdControl: SVlanIdControl 
}

objEnniService *-->"*" objEnvelope : enniEnvelopes


class objEtherType {

    etherType*: string 
}



class objL2cpIdentifer {

    macAddr*: string 
}

objL2cpIdentifer *-->"1" objL2cpProtocolIdentifier : protocolIdentifier


class objSaLimit {

    numAddr*: integer 
    interval*: integer 
}



class objVlanMap {

}

objVlanMap *-->"1" vlanMap_oneOf : vlanMap


class objVlanRange {

    start*: integer 
    end: integer 
}



class objVlanRangeList {

}

objVlanRangeList *-->"1..*" objVlanRange : vlanRangeList


enum TimeUnit {

    nanoSeconds
    microSeconds
    milliSeconds
    seconds
    minutes
    hours
    days
    weeks
    months
    years
}
class objBWP {

    eirmax: integer 
    envelopeRank*: integer 
    envelopeName*: string 
    cf: number 
    cirmax: integer 
    offset: integer 
    cbs: integer 
    ebs: integer 
    cm*: Cm 
    cir: integer 
    eir: integer 
}



class objCcDeiList {

}

objCcDeiList *-->"1..*" objCcDei : ccDeiList


class objCcPcp {

    cosname*: string 
    pcpgreen*: Pcpgreen 
    pcpyellow*: Pcpyellow 
}



class objCcPcpList {

}

objCcPcpList *-->"1..*" objCcPcp : ccPcpList


class objCnPcp {

    cosname*: string 
    pcp*: Pcp 
}



class objCnPcpList {

}

objCnPcpList *-->"1..*" objCnPcp : cnPcpList


class objConvToAggLink {

    aggLinkList*: integer[] 
}

objConvToAggLink *-->"1" objVlanRange : vlans


class objCosBWP {

    cosName*: string 
}

objCosBWP *-->"1" cosBWP_oneOf : cosBWP


class objCosDscpMap {

    notIP: string 
    otherIPv6: string 
    otherIPv4: string 
}

objCosDscpMap *-->"*" objCosDscpMapEntry : dscpValueCoSList


class objCosDscpMapEntry {

    cosName*: string 
}

objCosDscpMapEntry *--> objDscpValues : ipv4List
objCosDscpMapEntry *--> objDscpValues : ipv6List


class objCosFromCtagPcp {

    field_F*: objCosFromCtagPcpField_F 
}

objCosFromCtagPcp *-->"1" objCosPCPList : map_M
objCosFromCtagPcp *-->"1" objCosL2cp : l2cp_P


class objCosFromOvcEp {

    map_M*: string 
    field_F*: objCosFromOvcEpField_F 
}

objCosFromOvcEp *-->"1" objCosL2cp : l2cp_P


class objCosFromStagPcp {

    field_F*: objCosFromStagPcpField_F 
}

objCosFromStagPcp *-->"1" objCosPCPList : map_M
objCosFromStagPcp *-->"1" objCosL2cp : l2cp_P


class objCosL2cp {

    l2cpCosName*: string 
}

objCosL2cp *-->"1" objL2cpProtocolIdentifier : l2cpIdentifier


class objCosPCPList {

}

objCosPCPList *-->"1..*" objCosPcpMapEntry : cosPCPList


class objCosPcpMapEntry {

    pcpVal*: integer 
    pcpCosName*: string 
}



class objDscpValues {

    dscpValues: integer[] 
}



class objEnvelope {

    name*: string 
    cf0*: integer 
}



class objEtherTypeSubType {

    etherType*: string 
    subType*: string 
}



class objL2cpProtocolIdentifier {

}

objL2cpProtocolIdentifier *-->"1" protoID_oneOf : protoID


class protoID_oneOf {

}
objEtherType <|-- protoID_oneOf
objLLC <|-- protoID_oneOf
objEtherTypeSubType <|-- protoID_oneOf



class objLLC {

    llc*: string 
}



class objLinkDepth {

    vlanID*: integer 
    lagDepth*: integer 
}



class objMEPspec {

    megLevel*: integer 
    mepDirection*: MepDirection 
}



class objOperatorMultilateral {

}



class objOvcEP {

    megIntermediatePoint: MegIntermediatePoint 
}

objOvcEP *--> objSaLimit : sourceAddressMacLimit
objOvcEP *--> objLinkDepth : aggregationLinkDepth
objOvcEP *--> objOvcEgressMapItems : egressMap
objOvcEP *--> objVlanMap : ovcEndPointMap
objOvcEP *--> ingressBandwidthProfilePerEndPoint_oneOf : ingressBandwidthProfilePerEndPoint
objOvcEP *-->"*" objCosBWP : ingressBandwidthProfilePerClassOfServiceName
objOvcEP *--> ingressClassOfServiceMap_oneOf : ingressClassOfServiceMap
objOvcEP *-->"*" objMEPspec : maintenanceEndPointList


class objOvcEgressMapItems {

}

objOvcEgressMapItems *-->"*" objCnPcpList : cnpcp
objOvcEgressMapItems *-->"*" objCcDeiList : ccdei
objOvcEgressMapItems *-->"*" objCcPcpList : ccpcp


class objSLS {

}

objSLS *-->"*" SlsCosNameEntry : slsCosNameEntry
objSLS *--> TimeIntervalT : timeInterval
objSLS *--> TimeAndDate : startTime


enum L2cpAddressSet {

    CTA
    CTB
    CTB2
}
enum LinkOAM {

    ENABLED
    DISABLED
}
enum Meg {

    ENABLED
    DISABLED
}
enum SynchronousMode {

    ENABLED
    DISABLED
}
enum LinkAggregation {

    NONE
    2_LINK_ACTIVE_STANDBY
    ALL_ACTIVE
    OTHER
}
enum TokenShare {

    ENABLED
    DISABLED
}
enum Deiyellow {

    0
    1
    DISCARD
}
enum Deigreen {

    0
    1
    DISCARD
}
enum CeVlanIdPreservation {

    PRESERVE
    STRIP
    RETAIN
}
enum CTagPcpPreservation {

    ENABLED
    DISABLED
}
enum CTagDeiPreservation {

    ENABLED
    DISABLED
}
enum accessElineOvcPOQL2cpAddressSet {

    CTA
    CTB
    CTB2
}
enum ConstantDisabled {

    DISABLED
}
enum MepDirection {

    UP
    DOWN
}
enum objCosFromStagPcpField_F {

    S_TAG_PCP
}
enum Cm {

    COLOR_BLIND
    COLOR_AWARE
}
enum Unit {

    second
    minute
    hour
    day
    month
    week
    year
}
enum objCosFromOvcEpField_F {

    OVC_EP
}
enum Pcp {

    0
    1
    2
    3
    4
    5
    6
    7
    DISCARD
}
enum objCosFromCtagPcpField_F {

    C_TAG_PCP
}
enum ConstantAll {

    ALL
}
enum Pcpgreen {

    0
    1
    2
    3
    4
    5
    6
    7
    DISCARD
}
enum Pcpyellow {

    0
    1
    2
    3
    4
    5
    6
    7
    DISCARD
}
enum MegIntermediatePoint {

    ENABLED
    DISABLED
}
@enduml
