@startuml


skinparam activity {
    BackgroundColor White
    BorderColor Black
}

start

:accepted;
if(instant qualification requested?) then (yes)
    if(any other item failed?) then (yes)
        :done
        .abandoned;
    else (no)
        if(sufficient information?) then (yes)
            :done;
        else (no)
            :terminatedWithError;
        endif
    endif
else (no)
    :inProgress;
    if(any other item failed?) then (yes)
        :done
        .abandoned;
    else (no)
        if(sufficient information?) then (yes)
            :done;
        else (no)
            :terminatedWithError;
        endif
    endif
endif

stop

@enduml