@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor<<API>> Black
}

hide  <<API>> stereotype

class MEFProductConfiguration<<API>> {

    @type*: string 
    @schemaLocation: uri 
}

class accessElineOvcPOQ {

    ceVlanIdPreservation: CeVlanIdPreservation 
    cTagPcpPreservation: CTagPcpPreservation 
    cTagDeiPreservation: CTagDeiPreservation 
    listOfClassOfServiceNames: string[] 
    availableMegLevel: number 
    l2cpAddressSet: accessElineOvcPOQL2cpAddressSet 
    maximumFrameSize: integer 
}
MEFProductConfiguration <|-- accessElineOvcPOQ
accessElineOvcPOQ *-->"1" objOvcEP : enniEP
accessElineOvcPOQ *-->"1" objOvcEP : uniEP

class objOvcEP {

    megIntermediatePoint: MegIntermediatePoint 
}

objOvcEP *--> objSaLimit : sourceAddressMacLimit
objOvcEP *--> objLinkDepth : aggregationLinkDepth
objOvcEP *--> objOvcEgressMapItems : egressMap
objOvcEP *--> objVlanMap : ovcEndPointMap
objOvcEP *--> ingressBandwidthProfilePerEndPoint_oneOf : ingressBandwidthProfilePerEndPoint
objOvcEP *-->"*" objCosBWP : ingressBandwidthProfilePerClassOfServiceName
objOvcEP *--> ingressClassOfServiceMap_oneOf : ingressClassOfServiceMap
objOvcEP *-->"*" objMEPspec : maintenanceEndPointList

class ingressBandwidthProfilePerEndPoint_oneOf <<Virtual>> { }
ingressBandwidthProfilePerEndPoint_oneOf --|> objBWP 
ingressBandwidthProfilePerEndPoint_oneOf --|> objDisabled

class objCosBWP {

    cosName*: string 
}

objCosBWP *-->"1" cosBWP_oneOf : cosBWP

class cosBWP_oneOf <<Virtual>> { }
cosBWP_oneOf --|> objBWP 
cosBWP_oneOf --|> objDisabled

class objBWP {

    eirmax: integer 
    envelopeRank*: integer 
    envelopeName*: string 
    cf: number 
    cirmax: integer 
    offset: integer 
    cbs: integer 
    ebs: integer 
    cm*: Cm 
    cir: integer 
    eir: integer 
}

class objDisabled {

    constantDisabled*: ConstantDisabled 
}

enum CeVlanIdPreservation {

    PRESERVE
    STRIP
    RETAIN
}

enum Cm {

    COLOR_BLIND
    COLOR_AWARE
}

enum ConstantDisabled {

    DISABLED
}

enum CTagPcpPreservation {

    ENABLED
    DISABLED
}
enum CTagDeiPreservation {

    ENABLED
    DISABLED
}

enum MegIntermediatePoint {

    ENABLED
    DISABLED
}

@enduml