@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}
scale 4096 width
class AlternateProductOfferingProposal {

    id*: string 
}

AlternateProductOfferingProposal *-->"1" MEFProductExtension : alternateProduct
AlternateProductOfferingProposal *-->"1" ProductOfferingRef : alternateProductOffering
AlternateProductOfferingProposal *-->"1" TimeInterval : installationInterval


class Error400 {

    code*: string 
}
Error <|-- Error400



class Error401 {

    code*: string 
}
Error <|-- Error401



class Error403 {

    code*: string 
}
Error <|-- Error403



class Error404 {

    code*: string 
}
Error <|-- Error404



class Error405 {

    code*: string 
}
Error <|-- Error405



class Error422 {

    code*: string 
    propertyPath: string 
}
Error <|-- Error422



class Error500 {

    code*: string 
}
Error <|-- Error500



class Error501 {

    code*: string 
}
Error <|-- Error501



class Error {

    message: string 
    reason*: string 
    referenceError: uri 
}



class EventSubscription {

    callback*: string 
    id*: string 
    query: string 
}



class EventSubscriptionInput {

    callback*: string 
    query: string 
}



class FieldedAddress {

    city*: string 
    country*: string 
    locality: string 
    postcode: string 
    postcodeExtension: string 
    stateOrProvince: string 
    streetName*: string 
    streetNr: string 
    streetNrLast: string 
    streetNrLastSuffix: string 
    streetNrSuffix: string 
    streetSuffix: string 
    streetType: string 
}
RelatedPlaceRefOrValue <|-- FieldedAddress

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class FormattedAddress {

    addrLine1*: string 
    addrLine2: string 
    city*: string 
    country*: string 
    locality: string 
    postcode: string 
    postcodeExtension: string 
    stateOrProvince: string 
}
RelatedPlaceRefOrValue <|-- FormattedAddress



class GeographicAddressIdentifier {

    externalReferenceId*: string 
    externalReferenceType*: string 
}
RelatedPlaceRefOrValue <|-- GeographicAddressIdentifier



class GeographicAddressRef {

    href: string 
    id*: string 
}
RelatedPlaceRefOrValue <|-- GeographicAddressRef



class GeographicSiteRef {

    href: string 
    id*: string 
}
RelatedPlaceRefOrValue <|-- GeographicSiteRef



class GeographicSubAddress {

    buildingName: string 
    levelNumber: string 
    levelType: string 
    privateStreetName: string 
    privateStreetNumber: string 
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFGeographicPoint {

    spatialRef*: string 
    x*: string 
    y*: string 
    z: string 
}
RelatedPlaceRefOrValue <|-- MEFGeographicPoint



class MEFPOQItemStateChange {

    changeDate*: date-time 
    changeReason: string 
    state*: MEFPOQItemTaskStateType 
}



class MEFPOQStateChange {

    changeDate*: date-time 
    changeReason: string 
    state*: MEFPOQTaskStateType 
}



class MEFProductConfiguration {

    @schemaLocation: uri 
    @type*: string 
}



class MEFProductExtension {

}

MEFProductExtension *--> MEFProductConfiguration : productConfiguration


class MEFProductRefOrValue {

    href: string 
    id: string 
}

MEFProductRefOrValue *-->"*" RelatedPlaceRefOrValue : place
MEFProductRefOrValue *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValue *--> ProductOfferingRef : productOffering
MEFProductRefOrValue *-->"*" ProductRelationship : productRelationship
MEFProductRefOrValue *--> ProductSpecificationRef : productSpecification


class MEFSubUnit {

    subUnitNumber*: string 
    subUnitType*: string 
}



class ProductOfferingQualification {

    effectiveQualificationDate: date-time 
    expectedPOQCompletionDate: date-time 
    href: string 
    id*: string 
    state*: MEFPOQTaskStateType 
}
ProductOfferingQualification_Common <|-- ProductOfferingQualification

ProductOfferingQualification *-->"1..*" ProductOfferingQualificationItem : productOfferingQualificationItem
ProductOfferingQualification *-->"*" MEFPOQStateChange : stateChange


class ProductOfferingQualificationItem {

    guaranteedUntilDate: date-time 
    serviceabilityConfidenceReason: string 
    serviceabilityConfidence: MEFServiceabilityColor 
    state*: MEFPOQItemTaskStateType 
}
ProductOfferingQualificationItem_Common <|-- ProductOfferingQualificationItem

ProductOfferingQualificationItem *-->"*" AlternateProductOfferingProposal : alternateProductOfferingProposal
ProductOfferingQualificationItem *--> TimeInterval : installationInterval
ProductOfferingQualificationItem *-->"*" MEFPOQItemStateChange : stateChange
ProductOfferingQualificationItem *-->"*" TerminationError : terminationError


class ProductOfferingQualificationItem_Create {

}
ProductOfferingQualificationItem_Common <|-- ProductOfferingQualificationItem_Create



class ProductOfferingQualificationItem_Common {

    action*: ProductActionType 
    id*: string 
}

ProductOfferingQualificationItem_Common *-->"1" MEFProductRefOrValue : product
ProductOfferingQualificationItem_Common *-->"*" QualificationItemRelationship : qualificationItemRelationship
ProductOfferingQualificationItem_Common *-->"*" RelatedContactInformation : relatedContactInformation


class ProductOfferingQualification_Create {

}
ProductOfferingQualification_Common <|-- ProductOfferingQualification_Create

ProductOfferingQualification_Create *-->"1..*" ProductOfferingQualificationItem_Create : productOfferingQualificationItem


class ProductOfferingQualification_Common {

    instantSyncQualification: boolean 
    projectId: string 
    provideAlternative: boolean 
    requestedPOQCompletionDate: date-time 
}

ProductOfferingQualification_Common *-->"1..*" RelatedContactInformation : relatedContactInformation


enum MEFPOQItemTaskStateType {

    acknowledged
    terminatedWithError
    inProgress
    done.abandoned
    done.ready
}
class ProductOfferingQualification_Find {

    id*: string 
    projectId: string 
    requestedPOQCompletionDate: date 
    state*: MEFPOQTaskStateType 
}



class ProductOfferingRef {

    href: string 
    id*: string 
}



class ProductRelationship {

    groupingKey: string 
    href: string 
    id*: string 
    relationshipType*: string 
}



class ProductSpecificationRef {

    href: string 
    id*: string 
}



class QualificationItemRelationship {

    id*: string 
    relationshipType*: string 
}



class RelatedContactInformation {

    emailAddress*: string 
    name*: string 
    number*: string 
    numberExtension: string 
    organization: string 
    role*: string 
}

RelatedContactInformation *--> FieldedAddress : postalAddress


class RelatedPlaceRefOrValue {

    @schemaLocation: uri 
    @type*: string 
    role*: string 
}



class TerminationError {

    value*: string 
}



class TimeInterval {

    amount*: integer 
    timeUnit*: TimeUnit 
}



enum MEFServiceabilityColor {

    green
    yellow
    red
}
enum ProductActionType {

    add
    modify
    delete
}
enum TimeUnit {

    calendarMonths
    calendarDays
    calendarHours
    calendarMinutes
    businessDays
    businessHours
    businessMinutes
}
enum MEFPOQTaskStateType {

    acknowledged
    terminatedWithError
    inProgress
    done.unableToProvide
    done.ready
}
@enduml
