@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Error400 {

    code*: string 
}
Error <|-- Error400



class Error401 {

    code*: string 
}
Error <|-- Error401



class Error403 {

    code*: string 
}
Error <|-- Error403



class Error408 {

    code*: string 
}
Error <|-- Error408



class Error500 {

    code*: string 
}
Error <|-- Error500



class Error {

    message: string 
    reason*: string 
    referenceError: uri 
}



class Event {

    eventId*: string 
    eventType*: PoqEventType 
    eventTime*: date-time 
}

Event *-->"1" PoqEvent : event


class PoqEvent {

    id*: string 
    href: string 
    buyerId: string 
    sellerId: string 
}



enum PoqEventType {

    poqCreateEvent
    poqStateChangeEvent
}
@enduml
