@startuml


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class AppointmentAttributeValueChangeEvent {

    eventType*: string
}
Event <|-- AppointmentAttributeValueChangeEvent

AppointmentAttributeValueChangeEvent *-->"1" AppointmentAttributeValueChangeEventPayload : event


class AppointmentAttributeValueChangeEventPayload {

    id*: string
    href: string
}



class AppointmentStatusChangeEvent {

    eventType*: string
}
Event <|-- AppointmentStatusChangeEvent

AppointmentStatusChangeEvent *-->"1" AppointmentStatusChangeEventPayload : event


class AppointmentStatusChangeEventPayload {

    id*: string
    href: uri
    status*: AppointmentStatusType
}



enum AppointmentStatusType {

    confirmed
    inProgress
    cancelled
    missed
    failed
    completed
}
@enduml
