@startuml



class Appointment_Update {

}

Appointment_Update *-->"*" AttachmentValue : attachment
Appointment_Update *-->"*" Note : note
Appointment_Update *--> RelatedPlaceRefOrQuery : relatedPlace
Appointment_Update *-->"*" RelatedContactInformation : relatedContactInformation
Appointment_Update *--> TimePeriod : validFor


class AttachmentValue {

    author*: string
    creationDate*: date-time
    description: string
    mimeType: string
    name*: string
    source*: MEFBuyerSellerType
    url*: string
}


AttachmentValue *--> MEFByteSize : size


class MEFByteSize {

    amount*: float
    units*: DataSizeUnit
}




class RelatedPlaceRefOrQuery {
    contact: ContactInformation
    place*: PlaceRefOrQuery
    role*: string
    subUnit: SubUnit
}

class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}

class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}


class TimePeriod {

    endDateTime: date-time
    startDateTime: date-time
}


@enduml
