@startuml

class Workorder_Find {

    appointmentRequired*: boolean
    id*: string
    state*: WorkorderStateType
}

Workorder_Find *-->"*" RelatedPlaceRefOrQuery : place
Workorder_Find *-->"1..*" RelatedEntity : relatedEntity



class RelatedEntity {

    @referredType*: string
    href: string
    id*: string
    role*: string
}




class RelatedPlaceRefOrQuery {
    contact: ContactInformation
    place*: PlaceRefOrQuery
    role*: string
    subUnit: SubUnit
}


@enduml
