@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class SearchTimeSlot {

}

SearchTimeSlot *-->"1..*" TimeSlot : availableTimeSlot
SearchTimeSlot *-->"1..*" TimeSlot : requestedTimeSlot
SearchTimeSlot *-->"1" WorkOrderRef : workOrder


class SearchTimeSlot_Create {

}

SearchTimeSlot_Create *-->"1..*" TimeSlot : requestedTimeSlot
SearchTimeSlot_Create *-->"1" WorkOrderRef : workOrder


class TimePeriod {

    endDateTime: date-time
    startDateTime: date-time
}


class TimeSlot {

}

TimeSlot *-->"1" TimePeriod : validFor

class WorkOrderRef {

    href: string
    id*: string
}


@enduml
