@startuml

left to right direction
actor Buyer
actor Seller 

skinparam usecase {

}

rectangle {
(7.	Search Appointment Timeslot)
(8.	Create Appointment)
(9.	Retrieve Appointment List)
(10.	Retrieve Appointment by Appointment Identifier)
(11. Patch Appointment by Appointment Identifier)
(12. Cancel Appointment)
(13. Retrieve Workorder List)
(14. Retrieve Workorder by Workorder Identifier)
(19. Register for Appointment Notifications)
(20. Send Appointment Notification)
(21. Register for Workorder Notifications)
(22. Send Workorder Notification)



Buyer --> (7.	Search Appointment Timeslot)
Buyer --> (8.	Create Appointment)
Buyer --> (9.	Retrieve Appointment List)
Buyer --> (10.	Retrieve Appointment by Appointment Identifier)
Buyer --> (11. Patch Appointment by Appointment Identifier)
Buyer --> (12. Cancel Appointment)
Buyer --> (13. Retrieve Workorder List)
Buyer --> (14. Retrieve Workorder by Workorder Identifier)
Buyer --> (19. Register for Appointment Notifications)
Buyer --> (20. Send Appointment Notification)
Buyer --> (21. Register for Workorder Notifications)
(19. Register for Appointment Notifications) <--Seller 
(20. Send Appointment Notification)<--Seller
(21. Register for Workorder Notifications)<--Seller
(22. Send Workorder Notification)<--Seller

@enduml
