@startuml

class Appointment_Find {

    id*: string
    href: string
    status*: AppointmentStatusType
}

Appointment_Find *-->"1" RelatedPlaceRefOrQuery : relatedPlace
Appointment_Find *-->"1" TimePeriod : validFor
Appointment_Find *-->"1" WorkOrderRef : workOrder




class WorkOrderRef {

    href: string
    id*: string
}

class TimePeriod {

    endDateTime*: date-time
    startDateTime*: date-time
}




class RelatedPlaceRefOrQuery {
    contact: ContactInformation
    place*: PlaceRefOrQuery
    role*: string
    subUnit: SubUnit
}


@enduml
