@startuml

class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class WorkOrderAppointmentRequiredEvent {

    eventType*: string
}
Event <|-- WorkOrderAppointmentRequiredEvent

WorkOrderAppointmentRequiredEvent *-->"1" WorkOrderEventPayload : event


class WorkOrderCreateEvent {

    eventType*: string
}
Event <|-- WorkOrderCreateEvent

WorkOrderCreateEvent *-->"1" WorkOrderEventPayload : event


class WorkOrderStateChangeEvent {

    eventType*: string
}
Event <|-- WorkOrderStateChangeEvent

WorkOrderStateChangeEvent *-->"1" WorkOrderStateChangeEventPayload : event


class WorkOrderStateChangeEventPayload {

    id*: string
    href: uri
    state: WorkOrderStateType
}



class WorkOrderEventPayload {

    id*: string
    href: string
}



enum WorkOrderStateType {

    cancelled
    completed
    inProgress
    open
    planned
    unableToComplete
}
@enduml
