@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class AppointmentRef {

    href: string
    id*: string
}



class Error400 {

    code*: Error400Code
}
Error <|-- Error400



class Error401 {

    code*: Error401Code
}
Error <|-- Error401



class Error403 {

    code*: Error403Code
}
Error <|-- Error403



enum Error403Code {

    accessDenied
    forbiddenRequester
    tooManyUsers
}
class Error500 {

    code*: string
}
Error <|-- Error500



class Error {

    message: string
    reason*: string
    referenceError: uri
}



class EventSubscription {

    callback*: string
    id*: string
    query: string
}



class EventSubscriptionInput {

    callback*: string
    query: string
}



class FieldedAddress {

    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    streetName*: string
    streetNr: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetNrSuffix: string
    streetSuffix: string
    streetType: string
}
RelatedPlaceRefOrValue <|-- FieldedAddress

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class FormattedAddress {

    addrLine1*: string
    addrLine2: string
    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
}
RelatedPlaceRefOrValue <|-- FormattedAddress



class GeographicAddressLabel {

    externalReferenceId*: string
    externalReferenceType*: string
}
RelatedPlaceRefOrValue <|-- GeographicAddressLabel



class GeographicAddressRef {

    href: string
    id*: string
}
RelatedPlaceRefOrValue <|-- GeographicAddressRef



class GeographicSiteRef {

    href: string
    id*: string
}
RelatedPlaceRefOrValue <|-- GeographicSiteRef



class GeographicSubAddress {

    buildingName: string
    id: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFGeographicPoint {

    spatialRef*: string
    x*: string
    y*: string
    z: string
}
RelatedPlaceRefOrValue <|-- MEFGeographicPoint



class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddress : postalAddress


class RelatedEntity {

    @referredType*: string
    href: string
    id*: string
    role*: string
}



class RelatedPlaceRefOrValue {

    @schemaLocation: uri
    @type*: string
    role*: string
}



class TimeDuration {

    timeDurationValue: integer
    timeDurationUnits: TimeDurationUnits
}



class WorkOrder {

    id*: string
    href: string
    appointmentRequired*: boolean
    plannedExecutionDate: date-time
    state*: WorkOrderStateType
    task*: string
}

WorkOrder *-->"*" AppointmentRef : appointment
WorkOrder *-->"1" TimeDuration : duration
WorkOrder *-->"*" Note : note
WorkOrder *-->"1..*" RelatedPlaceRefOrValue : place
WorkOrder *-->"1..*" RelatedContactInformation : relatedContactInformation
WorkOrder *-->"1..*" RelatedEntity : relatedEntity


enum WorkOrderStateType {

    cancelled
    completed
    inProgress
    open
    planned
    unableToComplete
}
class WorkOrder_Find {

    id*: string
    appointmentRequired*: boolean
    state*: WorkOrderStateType
}

WorkOrder_Find *-->"1..*" RelatedPlaceRefOrValue : place
WorkOrder_Find *-->"1..*" RelatedEntity : relatedEntity


enum Error401Code {

    missingCredentials
    invalidCredentials
}
enum Error400Code {

    missingQueryParameter
    missingQueryValue
    invalidQuery
    invalidBody
}
class Error404 {

    code*: string
}
Error <|-- Error404



enum MEFBuyerSellerType {

    buyer
    seller
}
enum TimeDurationUnits {

    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}
@enduml
