@startuml

class AppointmentRef {

    href: string
    id*: string
}


class EventSubscription {

    callback*: string
    id*: string
    query: string
}



class EventSubscriptionInput {

    callback*: string
    query: string
}




enum MEFBuyerSellerType {

    buyer
    seller
}

class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}



class RelatedEntity {

    @referredType*: string
    href: string
    id*: string
    role*: string
}



class TimeDuration {

    timeDurationValue*: integer
    timeDurationUnits*: TimeDurationUnits
}



enum TimeDurationUnits {

    NS
    US
    MS
    SEC
    MIN
    HOUR
    DAY
    WEEK
    MONTH
    YEAR
}
class WorkOrder {

    id*: string
    href: string
    appointmentRequired*: boolean
    plannedExecutionDate: date-time
    state*: WorkOrderStateType
    task*: string[]
}

WorkOrder *-->"*" AppointmentRef : appointment
WorkOrder *-->"1" TimeDuration : duration
WorkOrder *-->"*" Note : note
WorkOrder *-->"1..*" RelatedPlaceRefOrQuery : place
WorkOrder *-->"1..*" RelatedContactInformation : relatedContactInformation
WorkOrder *-->"1..*" RelatedEntity : relatedEntity


enum WorkOrderStateType {

    cancelled
    completed
    inProgress
    open
    planned
    unableToComplete
}
class WorkOrder_Find {

    id*: string
    appointmentRequired*: boolean
    state*: WorkOrderStateType
}

WorkOrder_Find *-->"1..*" RelatedPlaceRefOrQuery : place
WorkOrder_Find *-->"1..*" RelatedEntity : relatedEntity


class RelatedPlaceRefOrQuery {
    contact: ContactInformation
    place*: PlaceRefOrQuery
    role*: string
    subUnit: SubUnit
}

class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


@enduml
