//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 01:55:00 PM CEST 
//


package com.orange.onapbss.datamodel.productordering;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for desiredResponse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="desiredResponse"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Confirmation and Engineering"/&gt;
 *     &lt;enumeration value="Confirmation"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "desiredResponse")
@XmlEnum
public enum DesiredResponseEntity {

    @XmlEnumValue("Confirmation and Engineering")
    CONFIRMATION_AND_ENGINEERING("Confirmation and Engineering"),
    @XmlEnumValue("Confirmation")
    CONFIRMATION("Confirmation"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    DesiredResponseEntity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DesiredResponseEntity fromValue(String v) {
        for (DesiredResponseEntity c: DesiredResponseEntity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
