//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.20 at 01:55:00 PM CEST 
//


package com.orange.onapbss.datamodel.productordering;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationShipType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelationShipType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="reliesOn"/&gt;
 *     &lt;enumeration value="brings"/&gt;
 *     &lt;enumeration value="hasParent"/&gt;
 *     &lt;enumeration value="hasChild"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RelationShipType")
@XmlEnum
public enum RelationShipTypeEntity {

    @XmlEnumValue("reliesOn")
    RELIES_ON("reliesOn"),
    @XmlEnumValue("brings")
    BRINGS("brings"),
    @XmlEnumValue("hasParent")
    HAS_PARENT("hasParent"),
    @XmlEnumValue("hasChild")
    HAS_CHILD("hasChild");
    private final String value;

    RelationShipTypeEntity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RelationShipTypeEntity fromValue(String v) {
        for (RelationShipTypeEntity c: RelationShipTypeEntity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
