@startuml


skinparam activity {
    BackgroundColor White
    BorderColor Black
}

start
if(immediate response?) then (yes)
    'goto information_check
else (no)
    :acknowledged;
    if(issues detected?) then (no)
        :inProgress;
        if(cancelled by the Buyer?) then (no)
            'goto information_check
        else(yes)
            :cancelled;
            stop
        endif
    else (yes)
        :rejected;
        stop
    endif
endif
'label information_check
if(able to quote all items?) then (no)
    :unableToProvide;
else(yes)
    :answered;
    :expired;
endif

stop

@enduml