@startuml


class Quote_Common {

    requestedQuoteCompletionDate: date-time
    description: string
    externalId: string
    buyerRequestedQuoteLevel*: MEFBuyerQuoteLevel
    projectId: string
    instantSyncQuote*: boolean
    note: Note
}

Quote_Common *-->"*" RelatedContactInformation : relatedContactInformation



class MEFProductConfiguration {

    @type*: string 
}



class MEFProductRefOrValueQuote {

    id: string
    href: string
}

MEFProductRefOrValueQuote *-->"*" RelatedPlaceRefOrQueryWithSubUnit : place
MEFProductRefOrValueQuote *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValueQuote *--> ProductOfferingRef : productOffering
MEFProductRefOrValueQuote *-->"*" ProductRelationship : productRelationship


class MEFQuoteItem_Create {

}
MEFQuoteItem_Common <|-- MEFQuoteItem_Create



class MEFQuoteItem_Common {

    id*: string
    action*: MEFProductActionType
    agreementName: string
    dealReference: string
    note: Note
    productOfferingQualificationItem: ProductOfferingQualificationItemRef
    requestedQuoteItemInstallationInterval: Duration
    requestedQuoteItemTerm: MEFItemTerm
}

MEFQuoteItem_Common *-->"1" MEFProductRefOrValueQuote : product
MEFQuoteItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFQuoteItem_Common *-->"*" QuoteItemRelationship : quoteItemRelationship


class ProductOfferingRef {

    id*: string 
    href: string 
}

class ProductRelationship {

    href: string
    id*: string
    relationshipType*: string
}


class QuoteItemRelationship {

    id*: string 
    relationshipType*: string 
}


class Quote_Create {

}
Quote_Common <|-- Quote_Create

Quote_Create *-->"1..*" MEFQuoteItem_Create : quoteItem


class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


class RelatedPlaceRefOrQueryWithSubUnit {

    role*: string
    place: PlaceRefOrQuery
    subUnit: SubUnit
    contact: ContactInformation
}



@enduml
