@startuml


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



enum MEFQuoteItemStateType {

    answered
    acknowledged
    approved.orderable
    approved.orderableAlternate
    inProgress
    inProgress.draft
    rejected
    abandoned
    unableToProvide
}
enum MEFQuoteStateType {

    accepted
    acknowledged
    answered
    approved.orderable
    approved.orderableAlternate
    cancelled
    unableToProvide
    declined
    expired
    inProgress
    inProgress.draft
    rejected
}
class QuoteItemStateChangeEvent {

    eventType*: string
}
Event <|-- QuoteItemStateChangeEvent

QuoteItemStateChangeEvent *-->"1" QuoteItemStateChangeEventPayload : event


class QuoteItemStateChangeEventPayload {

    id*: string
    href: string
    quoteItemId*: string
    state*: MEFQuoteItemStateType
}



class QuoteStateChangeEvent {

    eventType*: string
}
Event <|-- QuoteStateChangeEvent

QuoteStateChangeEvent *-->"1" QuoteStateChangeEventPayload : event


class QuoteStateChangeEventPayload {

    id*: string
    href: string
    state*: MEFQuoteStateType
}



@enduml
