@startuml

class ContactInformation {

    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

ContactInformation *--> FieldedAddressRepresentation : postalAddress


class Duration {

    amount*: integer
    units*: TimeUnit
}


class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}
FieldedAddressRepresentation *-->"*" SubUnit : subUnit


class FormattedAddressRepresentation {

    formattedAddress*: string
    language: string
}



class GeographicAddressRef {

    href: string
    id*: string
    @type*: string
}



class GeographicAddress_Query {
    @type*: string
}

GeographicAddress_Query *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress_Query *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress_Query *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress_Query *-->"*" LabelRepresentation : labelRepresentation


class GeographicPointRepresentation {

    spatialRef*: string
    latitude*: string
    longitude*: string
    elevation: string
}



class GeographicSiteRef {

    href: string
    id*: string
    @type*: string
}



class LabelRepresentation {

    label*: string
    administrativeAuthority*: string
    language: string
}



enum MEFBuyerQuoteLevel {

    budgetary
    firm
}
enum MEFEndOfTermAction {

    roll
    autoDisconnect
    autoRenew
}
class MEFItemTerm {

    endOfTermAction*: MEFEndOfTermAction
    name*: string
    description: string
}

MEFItemTerm *-->"1" Duration : duration
MEFItemTerm *--> Duration : rollInterval


enum MEFPriceType {

    recurring
    nonRecurring
    usageBased
}
enum MEFProductActionType {

    add
    modify
    delete
}
class MEFProductConfiguration {

    @type*: string
}



enum MEFQuoteItemStateType {

    answered
    acknowledged
    approved.orderable
    approved.orderableAlternate
    inProgress
    inProgress.draft
    rejected
    abandoned
    unableToProvide
}
class MEFQuoteItem_Common {

    agreementName: string
    action*: MEFProductActionType
    dealReference: string
    id*: string
}

MEFQuoteItem_Common *--> MEFItemTerm : requestedQuoteItemTerm
MEFQuoteItem_Common *-->"*" Note : note
MEFQuoteItem_Common *-->"1" MEFProductRefOrValueQuote : product
MEFQuoteItem_Common *--> ProductOfferingQualificationItemRef : productOfferingQualificationItem
MEFQuoteItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFQuoteItem_Common *--> Duration : requestedQuoteItemInstallationInterval
MEFQuoteItem_Common *-->"*" QuoteItemRelationship : quoteItemRelationship


class MEFQuoteItem_Create {

}
MEFQuoteItem_Common <|-- MEFQuoteItem_Create



class MEFQuoteItemStateChange {

    changeReason: string
    changeDate*: date-time
    state*: MEFQuoteItemStateType
}



class MEFQuoteStateChange {

    changeReason: string
    changeDate*: date-time
    state*: MEFQuoteStateType
}



enum MEFQuoteStateType {

    accepted
    acknowledged
    answered
    approved.orderable
    approved.orderableAlternate
    cancelled
    unableToProvide
    declined
    expired
    inProgress
    inProgress.draft
    rejected
}
enum MEFSellerQuoteLevel {

    budgetary
    firmSubjectToFeasibilityCheck
    firm
}
class MEFProductRefOrValueQuote {

    id: string
    href: string
}

MEFProductRefOrValueQuote *-->"*" RelatedPlaceRefOrQueryWithSubUnit : place
MEFProductRefOrValueQuote *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValueQuote *--> ProductOfferingRef : productOffering
MEFProductRefOrValueQuote *-->"*" ProductRelationship : productRelationship


class Money {

    unit*: string
    value*: float
}



class Note {

    date*: date-time
    author*: string
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}



enum MEFBuyerSellerType {

    buyer
    seller
}
class PlaceRefOrQuery {

}



class Price {

    taxRate: float
}

Price *--> Money : taxIncludedAmount
Price *-->"1" Money : dutyFreeAmount


class ProductOfferingQualificationItemRef {

    productOfferingQualificationId*: string
    alternateProductOfferingProposalId: string
    productOfferingQualificationHref: string
    id*: string
}



class ProductOfferingRef {

    id*: string
    href: string
}



class ProductRelationship {

    href: string
    id*: string
    relationshipType*: string
}



class Quote {

    effectiveQuoteCompletionDate: date-time
    expectedQuoteCompletionDate: date-time
    quoteLevel: MEFSellerQuoteLevel
    id*: string
    href: string
    state*: MEFQuoteStateType
    quoteDate*: date-time
}
Quote_Common <|-- Quote

Quote *--> TimePeriod : validFor
Quote *-->"1..*" QuoteItem : quoteItem
Quote *-->"1..*" MEFQuoteStateChange : stateChange


class QuoteItem {

    subjectToFeasibilityCheck: boolean
    state*: MEFQuoteItemStateType
}
MEFQuoteItem_Common <|-- QuoteItem

QuoteItem *-->"*" TerminationError : terminationError
QuoteItem *--> Duration : quoteItemInstallationInterval
QuoteItem *-->"0..1" MEFItemTerm : quoteItemTerm
QuoteItem *-->"1..*" MEFQuoteItemStateChange : stateChange
QuoteItem *-->"*" QuotePrice : quoteItemPrice


class QuoteItemRelationship {

    relationshipType*: string
    id*: string
}



class QuoteOperationData {

    reason: string
    quoteId*: string
}



class QuotePrice {

    unitOfMeasure: string
    name*: string
    priceType*: MEFPriceType
    description: string
}

QuotePrice *-->"1" Price : price
QuotePrice *--> Duration : recurringChargePeriod


class Quote_Common {

    requestedQuoteCompletionDate: date-time
    description: string
    externalId: string
    buyerRequestedQuoteLevel*: MEFBuyerQuoteLevel
    projectId: string
    instantSyncQuote*: boolean
}

Quote_Common *-->"*" Note : note
Quote_Common *-->"*" RelatedContactInformation : relatedContactInformation


class Quote_Create {

}
Quote_Common <|-- Quote_Create

Quote_Create *-->"1..*" MEFQuoteItem_Create : quoteItem


class Quote_Find {

    effectiveQuoteCompletionDate: date-time
    expectedQuoteCompletionDate: date-time
    requestedQuoteCompletionDate: date-time
    quoteLevel: MEFSellerQuoteLevel
    externalId: string
    id: string
    state*: MEFQuoteStateType
    projectId: string
    quoteDate: date-time
}



class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress


class RelatedPlaceRefOrQueryWithSubUnit {

    role*: string
}

RelatedPlaceRefOrQueryWithSubUnit *-->"1" PlaceRefOrQuery : place
RelatedPlaceRefOrQueryWithSubUnit *-->"*" SubUnit : subUnit
RelatedPlaceRefOrQueryWithSubUnit *-->"*" ContactInformation : contact


class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class TerminationError {

    code: Error422Code
    propertyPath: string
    value: string
}



class TimePeriod {

    startDateTime: date-time
    endDateTime: date-time
}



enum TimeUnit {

    seconds
    minutes
    businessHours
    calendarHours
    businessDays
    calendarDays
    months
    years
}
@enduml
