@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/hub with {{callbackUrl}} details\n"query":"eventType=quoteStateChangeEvent,quoteItemStateChangeEvent"
Seller --> Buyer: 201 confirmation with {{id}}
...
Buyer -> Seller : POST {{baseUrl}}/quote (instantSyncQuote=false)
Seller -> Seller : validate Request

alt succesful inquiry
  Seller --> Buyer : 201 Quote with {{id}} in `acknowledged` state \nQuoteItems in `acknowledged` state
  
  ...

  note over Buyer, Seller : First QuoteItem moves to `inProgress`
  Seller -> Buyer:  {{callbackUrl}}/listener/quoteItemStateChangeEvent {{id}}, {{quoteItem.id}}
  Buyer --> Seller : 204 confirmation
  
  note over Buyer, Seller : Quote moves to `inProgress`
  Seller -> Buyer: {{callbackUrl}}/listener/quoteStateChangeEvent {{id}}
      Buyer --> Seller : 204 confirmation

  ...

  group loop [for each of remaining QuoteItems that move to `inProgress`]
      Seller -> Buyer:  {{callbackUrl}}/listener/quoteItemStateChangeEvent {{id}}, {{quoteItem.id}}
      Buyer --> Seller : 204 confirmation
  end

  ...

  group loop [for each QuoteItem that moves to `approved.orderable`]
      Seller -> Buyer:  {{callbackUrl}}/listener/quoteItemStateChangeEvent {{id}}, {{quoteItem.id}}
      Buyer --> Seller : 204 confirmation
  end

  ...

  note over Buyer, Seller : All QuoteItems in `approved.orderable` state
  Seller -> Buyer: {{callbackUrl}}/listener/quoteStateChangeEvent {{id}}
  Buyer --> Seller : 204 confirmation
  Buyer -> Seller : GET {{baseUrl}}/quote/{{id}}
  return 200 Quote in  `approved.orderable` state

  ...

  group optional [if Quote moves to accepted, declined, or expired]
    Seller -> Buyer: {{callbackUrl}}/listener/quoteStateChangeEvent ({{id}})
    Buyer --> Seller : 204 confirmation
    Buyer -> Seller : GET {{baseUrl}}/quote/{{id}}
    return 200 Quote in current state
  end


else validation or internal problem
  Seller --> Buyer : 4xx or 5xx errorresponse
end 


...

Buyer -> Seller : DELETE {{baseUrl}}/hub/{{id}} 
Seller -->  Buyer : 204 confirmation

@enduml