@startuml
hide footbox

hide footbox

participant Buyer
participant Seller


Buyer -> Seller : POST {{baseUrl}}/quote (instantSyncQuote=false)
Seller -> Seller : validate Request

alt succesful inquiry
  Seller --> Buyer : 201 Quote with {{id}}, `acknowledged` state
  
  ...

  loop until Quote in completion state
      Buyer -> Seller :   GET {{baseUrl}}/quote/{{id}}
      return 200 Quote in current state
  end

  ...

  group optional [until Quote in accepted, declined, or expired]
    Buyer -> Seller :   GET {{baseUrl}}/quote/{{id}}
    return 200 Quote in current state
  end

else validation or internal problem
  Seller --> Buyer : 4xx or 5xx error response
end


@enduml