@startuml

left to right direction
actor Seller
actor Buyer

rectangle {

Buyer --> (1. Create Quote)
    (1. Create Quote) --> (1c. Deferred Quote Response Requested, Immediate Quote Response Provided)
    (1. Create Quote) --> (1b. Deferred Quote Response Requested and Provided)
    (1. Create Quote) --> (1a. Immediate Quote Response Requested and Provided)
    

Buyer --> (2. Retrieve Quote List)
Buyer --> (3. Retrieve Quote by Quote Identifier)
Buyer --> (4. Cancel Quote by Quote Identifier)
Buyer --> (5. Decline Quote by Quote Identifier)
Buyer --> (6. Register for Quote Notification)
(7. Send Quote Notification) <-- Seller

Seller -[hidden]up-> (1c. Deferred Quote Response Requested, Immediate Quote Response Provided)

}

@enduml
