@startjson
{
  "provideAlternative": "true",
  "bestMatchGeographicAddress": {
    "@type": "FieldedAddress",
    "id": "BudapestAddress-id-1",
    "href": "{{baseUrl}}/geographicAddress/BudapestAddress-id-1",
    "allowsNewSite": "true",
    "hasPublicSite": "true",
    "streetNr": "20",
    "streetName": "Example",
    "streetType": "st.",
    "city": "Budapest",
    "stateOrProvince": "Budapest",
    "postcode": "10279",
    "country": "Hungary"
  },
  "submittedGeographicAddress": {
    "@type": "FieldedAddress",
    "streetNr": "20",
    "streetNrSuffix": "14",
    "streetName": "Example",
    "city": "Budapest",
    "postcode": "10279",
    "country": "Hungary"
  }
}
@endjson