@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}
class BasicIaBwpEnvelope {

    burstBehavior: BurstBehavior
    tE: integer
}

BasicIaBwpEnvelope *--> InformationRate : cir
BasicIaBwpEnvelope *--> InformationRate : maxIr



@enduml
