@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class BasicInternetAccess {

}
BasicInternetAccess *-->"1" BasicIaIpvc : ipvc
BasicInternetAccess *-->"1" BasicIaIpUni : ipUni
BasicInternetAccess *-->"1" BasicIaIpUniAccessLink : ipUniAccessLink
BasicInternetAccess *-->"1" EthernetUniAccessLinkTrunk : ipUniAccessLinkTrunk



class BasicIaIpvc {
  <<skipped>>
}


class BasicIaIpUni {
  <<skipped>>
}



class BasicIaIpUniAccessLink {
  <<skipped>>
}

class EthernetUniAccessLinkTrunk {
  <<skipped>>
}


@enduml