@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Bgp {

    authentication: string[]
    asOverride: EnabledDisabled
    administrativeDistance: integer
    connectionAddressFamily: AddressFamilyIpv4Ipv6
    holdTime: TwoOctetInteger
    subscriberAsNumber: FourOctetInteger
    peerAsNumber: FourOctetInteger
}



Bgp *-->"*" BgpCommunity : bgpCommunityList
Bgp *-->"*" BgpExtendedCommunity : bgpExtendedCommunityList
Bgp *-->"0..1" Damping : damping
Bgp *--> PeeringAddress : peeringAddresses

class BgpCommunity {
    autonomousSystemNumber: TwoOctetInteger 
    autonomousSystemDefined: TwoOctetInteger
    semantics: string
}



class BgpExtendedCommunity {

    regularType: integer
    regularValue: integer
    extendedType: TwoOctetInteger
    extendedValue: integer
    semantics: string
}

class Damping {

    cutoffThreshold: integer
    decayHalfLifeWhileReachable: integer
    decayHalfLifeWhileUnReachable: integer
    decayMemoryLimit: integer
    maxHoldDownTime: integer
    numberOfReuseLists: integer
    reuseListMemory: integer
    reuseListTimeGranularity: integer
    reuseThreshold: integer
    timeGranularity: integer
    reuseIndexArraySize: integer
}




class PeeringAddress {

    peeringAddressType: PeeringAddressType
}

PeeringAddress *-->"*" SubscriberAndSpLoopbackAddresses : subscriberAndSpLoopbackAddresses

class SubscriberAndSpLoopbackAddresses {

}

SubscriberAndSpLoopbackAddresses *--> Ipv4OrIpv6Address : subscriberLoopbackAddress
SubscriberAndSpLoopbackAddresses *--> Ipv4OrIpv6Address : spLoopbackAddress


@enduml
