skinparam Legend {
    BackgroundColor transparent
    BorderColor transparent
}


legend
|_ <b>ip
   |_ <b>common
    |_ ipCommon.yaml
    |_ ipSls.yaml
  |_ <b>internetAccess
    |_ <b>advancedInternetAccessIpvc
      |_ advancedInternetAccessIpvc.yaml
    |_ <b>basicInternetAccess
      |_ basicInternetAccess.yaml
    |_ <b>exclusiveAdvancedInternetAccess
      |_ exclusiveAdvancedInternetAccess.yaml
    |_ <b>internetAccessCommon
      |_ internetAccessCommon.yaml
  |_ <b>ipUni
    |_ ethernetUniAccessLinkTrunk.yaml
    |_ ipUni.yaml
    |_ ipUniAccessLink.yaml
    |_ ipUniCommon.yaml
    
end legend
