@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}



class ExclusiveAdvancedInternetAccess {

}
class AdvancedInternetAccessIpvc {
<<skipped>>
}


class IpUni {
<<skipped>>
}
class IpUniAccessLink {
<<skipped>>
}
ExclusiveAdvancedInternetAccess *-d-> "1" IpUni : ipUni

ExclusiveAdvancedInternetAccess *-d-> "1" AdvancedInternetAccessIpvc : ipvc
ExclusiveAdvancedInternetAccess *-d-> "1" IpUniAccessLink : ipUniAccessLink

@enduml