@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}
set namespaceSeparator none

class MEFProductRefOrValueOrder{

    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    productOffering: ProductOfferingRef
    productRelationship: ProductRelationshipWithGrouping
   
}


class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


MEFProductRefOrValueOrder *-->"0..1" MEFProductConfiguration : productConfiguration

class urn:mef:lso:spec:cantata-sonata:basic-internet-access:v0.3.0:all <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:cantata-sonata:basic-internet-access:v0.3.0:all"



class urn:mef:lso:spec:cantata-sonata:advanced-internet-access-ipvc:v0.3.0:all <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:cantata-sonata:advanced-internet-access-ipvc:v0.3.0:all"

@enduml
