@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

rectangle "Product: Advanced Internet Access IPVC" { 

  class AdvancedInternetAccessIpvc {
  }

  AdvancedInternetAccessIpvc *-d->"1" AdvancedIaIpvcEndPoint : ipvcEndPoint
}

rectangle "Product: IP UNI" { 

  class IpUni {

  }
  AdvancedIaIpvcEndPoint "0..*" o-r-> "1" IpUni : CONNECTS_TO_IPUNI

}


rectangle "Product: IP UNI Access Link" { 

  class IpUniAccessLink {

  }
  IpUniAccessLink "0..*" o-l-> "1" IpUni : PART_OF_IPUNI
}


rectangle "Product: Ethernet UNI Access Link Trunk" { 

class EthernetUniAccessLinkTrunk {

}
  IpUniAccessLink "0..*" o-r-> "1" EthernetUniAccessLinkTrunk : CARRIED_OVER_TRUNK

}


EthernetUniAccessLinkTrunk "0..*" o-d-> "1" RelatedPlaceRefOrValue : INSTALL_LOCATION

@enduml