@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class IpUniCommon {

    managementType: UniManagementType
    reversePathForwarding: EnabledDisabled
}

IpUniCommon *-->"*" ControlProtocol : listOfControlProtocols


class ControlProtocol {

    addressing: ControlProtocolAddressing
    protocolName: string
    reference: string
}

class BasicIaIpUni {

}
IpUniCommon <|-- BasicIaIpUni

BasicIaIpUni *--> BasicIaBwpEnvelope : egressBandwidthProfileEnvelope
BasicIaIpUni *--> BasicIaBwpEnvelope : ingressBandwidthProfileEnvelope

class IpUni {

}
IpUniCommon <|-- IpUni

IpUni *--> IpUniBwpEnvelope : egressBandwidthProfileEnvelope
IpUni *--> IpUniBwpEnvelope : ingressBandwidthProfileEnvelope
IpUni *--> RoutingProtocols : routingProtocols


class RoutingProtocols {
<<skipped>>
}
class BasicIaBwpEnvelope {
<<skipped>>
}
class IpUniBwpEnvelope {
<<skipped>>
}




@enduml