@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class IpUniAccessLinkCommon {
    identifier: IdentifierString
    connectionType: ConnectionType
    prefixDelegation: EnabledDisabled
    mtu: integer
}

IpUniAccessLinkCommon *-r-> L2Technology : l2Technology
IpUniAccessLinkCommon *-l->"*" Vrid : reservedVrids

class BasicIaIpUniAccessLink {

}
IpUniAccessLinkCommon <|-u- BasicIaIpUniAccessLink

BasicIaIpUniAccessLink *-u->"0..1" BasicIaBwpEnvelope : egressBwpEnvelope
BasicIaIpUniAccessLink *-u->"0..1" BasicIaBwpEnvelope : ingressBwpEnvelope
BasicIaIpUniAccessLink *-u->"0..1" BasicIaUniIpv4ConnectionAddressing : ipv4ConnectionAddressing
BasicIaIpUniAccessLink *-u->"0..1" BasicIaUniIpv6ConnectionAddressing : ipv6ConnectionAddressing


class IpUniAccessLink {

}
IpUniAccessLinkCommon <|-d- IpUniAccessLink

IpUniAccessLink *-->"0..1" AccessLinkBfd : bfd
IpUniAccessLink *-->"0..1" DhcpRelay : dhcpRelay
IpUniAccessLink *-->"0..1" IpUniAccessLinkBwpEnvelope : egressBwpEnvelope
IpUniAccessLink *-->"0..1" IpUniAccessLinkBwpEnvelope : ingressBwpEnvelope
IpUniAccessLink *-->"0..1" UniIpv4ConnectionAddressing : ipv4ConnectionAddressing
IpUniAccessLink *-->"0..1" UniIpv6ConnectionAddressing : ipv6ConnectionAddressing


class L2Technology  {
  <<skipped>>
}
class UniIpv4ConnectionAddressing  {
  <<skipped>>
}
class UniIpv6ConnectionAddressing  {
  <<skipped>>
}
class BasicIaUniIpv4ConnectionAddressing  {
  <<skipped>>
}
class BasicIaUniIpv6ConnectionAddressing  {
  <<skipped>>
}
class BasicIaBwpEnvelope  {
  <<skipped>>
}
class IpUniAccessLinkBwpEnvelope  {
  <<skipped>>
}
class AccessLinkBfd {

    activeEnd: BfdActiveEnd
    authenticationType: BfdAuthenticationType
    connectionAddressFamily: AddressFamilyIpv4Ipv6Both
    detectMultiplier: integer
    transmissionInterval: integer
}



class DhcpRelay {

}

DhcpRelay *-->"*" Ipv4OrIpv6Address : dhcpServerList
DhcpRelay *--> IdentifierString : ipvcEndPointIdentifier

@enduml