@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}
IpBwpFlowPerIpvcEp *-d[hidden]-> IpBwpFlowPerIpvcEpAccessLink
IpBwpFlowPerIpvcEpAccessLink *-d[hidden]-> IpBwpFlowAll
IpBwpFlowAll *-d[hidden]-> IpBwpFlowPerAccessLink
IpBwpFlowPerAccessLink *-d[hidden]-> IpBwpFlowPerIpvcEpAndCosName
IpBwpFlowPerIpvcEpAndCosName *-d[hidden]-> IpBwpFlowPerAccessLinkIpvcEpAndCosName

class IpBwpFlow {
}
' h
IpUniBwpEnvelope *-r-> IpBwpFlow

class IpBwpEnvelope {
}


class IpUniBwpEnvelope {

}
IpBwpEnvelope <|-d- IpUniBwpEnvelope
' all h

IpUniBwpEnvelope *-r->"*" IpBwpFlowPerIpvcEp : bwpFlowPerIpvcEp
IpUniBwpEnvelope *-r->"*" IpBwpFlowPerIpvcEpAccessLink : bwpFlowPerIpvcEpAccessLink
IpUniBwpEnvelope *-r-> IpBwpFlowAll : bwpFlowAll
IpUniBwpEnvelope *-r->"*" IpBwpFlowPerAccessLink : bwpFlowPerAccessLink
IpUniBwpEnvelope *-r->"*" IpBwpFlowPerIpvcEpAndCosName : bwpFlowPerIpvcEpAndCosName
IpUniBwpEnvelope *-r->"*" IpBwpFlowPerAccessLinkIpvcEpAndCosName : bwpFlowPerAccessLinkIpvcEpAndCosName




class IpBwpFlowPerAccessLinkIpvcEpAndCosName {
    uniAccessLinkIdentifier: IdentifierString[]
}
IpBwpFlow <|-l- IpBwpFlowPerAccessLinkIpvcEpAndCosName

IpBwpFlowPerAccessLinkIpvcEpAndCosName *-r->"*" IpvcEpAndCosName : ipvcEpAndCosName


class IpBwpFlowAll {

}
IpBwpFlow <|-l- IpBwpFlowAll



class IpBwpFlowPerIpvcEp {
    ipvcEndPointIdentifier: IdentifierString[]
}
IpBwpFlow <|-l- IpBwpFlowPerIpvcEp


class IpBwpFlowPerIpvcEpAndCosName {

}
IpBwpFlow <|-l- IpBwpFlowPerIpvcEpAndCosName

IpBwpFlowPerIpvcEpAndCosName *-r->"*" IpvcEpAndCosName : ipvcEpAndCosName



class IpBwpFlowPerAccessLink {
    uniAccessLinkIdentifier: IdentifierString[]
}
IpBwpFlow <|-l- IpBwpFlowPerAccessLink


class IpBwpFlowPerIpvcEpAccessLink {
    ipvcEndPointIdentifier: IdentifierString[]
    uniAccessLinkIdentifier: IdentifierString[]
}
IpBwpFlow <|-l- IpBwpFlowPerIpvcEpAccessLink

IpvcEpAndCosName *-u[hidden]-> IpBwpFlow

class IpvcEpAndCosName {
    ipvcEndPointIdentifier: IdentifierString
    cosName: string
    
}



@enduml
