@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class IaIpvcCloud {

}

IaIpvcCloud *--> CloudDataLimit : dataLimit
IaIpvcCloud *--> Ipv4Prefix : networkAddressTranslation
IaIpvcCloud *--> CloudDns : dns
IaIpvcCloud *--> SubscriberPrefixList : subscriberPrefixList


class CloudDataLimit {

    startTime: date-time
    upload: integer
    download: integer
}

CloudDataLimit *--> TimeDuration : duration

class CloudDns {

    dnsType: DnsType
}

CloudDns *-->"*" Ipv4OrIpv6Address : dnsServerIpList


class SubscriberPrefixList {

    origin: IpPrefixOrigin
}

SubscriberPrefixList *-->"*" Ipv4OrIpv6Prefix : prefixes


class Ipv4Prefix {

    prefixLength: integer
}

Ipv4Prefix *--> Ipv4Address : ipv4Address


class  TimeDuration {
  <<skipped>>
}

class  Ipv4OrIpv6Prefix {
  <<skipped>>
}

@enduml