@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}
class L2Technology {

}

L2Technology *--> Demux : demux

class Demux {

    utpt: boolean
    vlanId: vlanIdlanId
}

@enduml
