@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Ospf {
areaId: Ipv4Address
    areaType: OspfAreaType
    authenticationType: OspfAuthenticationType
    deadInterval: integer
    helloInterval: TwoOctetInteger
    retransmissionInterval: integer
    administrativeDistance: integer
}

@enduml
