@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class RoutingProtocols {

}
RoutingProtocols *-->"0..1" RoutingProtocolsBgpOptions : bgp
RoutingProtocols *-->"0..1" RoutingProtocolsOspfOptions : ospf
RoutingProtocols *-->"0..1" Static : static


class RoutingProtocolsBgpOptions {

}

RoutingProtocolsBgpOptions *--> Bgp : ipv4
RoutingProtocolsBgpOptions *--> Bgp : ipv6
RoutingProtocolsBgpOptions *--> Bgp : both


class RoutingProtocolsOspfOptions {

}

RoutingProtocolsOspfOptions *--> Ospf : ipv4
RoutingProtocolsOspfOptions *--> Ospf : ipv6



class Bgp {
  <<skipped>>
}

class Ospf {
  <<skipped>>
}

class Static {
  <<skipped>>
}
@enduml
