@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class RoutingProtocols {

}

RoutingProtocols *--> RoutingProtocolsBgpOptions : bgp
RoutingProtocols *--> RoutingProtocolsOspfOptions : ospf
RoutingProtocols *--> Static : static


class RoutingProtocolsBgpOptions {

}

RoutingProtocolsBgpOptions *--> Bgp : ipv4
RoutingProtocolsBgpOptions *--> Bgp : ipv6
RoutingProtocolsBgpOptions *--> Bgp : both


class RoutingProtocolsOspfOptions {

}

RoutingProtocolsOspfOptions *--> Ospf : ipv4
RoutingProtocolsOspfOptions *--> Ospf : ipv6



class Bgp {
  <<skipped>>
}

class Ospf {
  <<skipped>>
}

class Static {
  <<skipped>>
}
@enduml
