@startuml

skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class IpUniAccessLinkTrunk {

}


class EthernetUniAccessLinkTrunk {

    ethernetLinkOam: EnabledDisabled
    ethernetPhysicalLink: EthernetPhysicalLink[]
    ethernetLinkAggregation: UniAccessLinkEthernetLinkAggregation
}
IpUniAccessLinkTrunk <|-- EthernetUniAccessLinkTrunk
@enduml