@startuml

enum Status {
   Planned
   Cancelled
   UnderConstruction
   Existing
   Former
}

class ZErrorDetail {
   code:int
   message:string
   description:string
   infoURL:string
}

class ZError {
   code:int
   message:string
   description:string
   infoURL:string
}
   ZError --> "0-*" ZErrorDetail : details

class GeographicAddress {
   id:string
   streetNr:string
   streetNrSuffix:string
   streetNrLast:string
   streetName:string
   streetType:string
   streetSuffix:string
   locality:string
   city:string
   postcode:string
   stateOrProvince:string
   country:string
   addrLine1:string
   addrLine2:string
   postCodeExtension:string
   referenceId:string
   referenceType:string
   @type:string
   @schemaLocation:string
}
   GeographicAddress --> "0-1" GeographicSubAddress : geographicSubAddress
   GeographicAddress --> "0-1" GeographicLocation : geographicLocation

class Site {
   id:string
   description:string
   siteCompanyName:string
   siteCustomerName:string
   additionnalSiteInformation:string
   @type:string
   @schemaLocation:string
}
   Site --> "0-1" Status : status
   Site --> "0-1" GeographicAddress : geographicAddress

class GeographicPoint {
   spatialRef:string
   x:string
   y:string
}

class GeographicLocation
   GeographicLocation --> "0-*" GeographicPoint : geographicPoint

class GeographicSubAddress {
   id:string
   subUnitType:string
   subUnitNumber:string
   levelType:string
   levelNumber:string
   buildingName:string
   privateStreetNumber:string
   privateStreetName:string
   @type:string
   @schemaLocation:string
}

class GeographicAddressFindResp {
   streetNr:string
   streetName:string
   streetType:string
   city:string
   postcode:string
   country:string
}

class SiteFindResp {
   id:string
   siteCompanyName:string
   siteCustomerName:string
}
   SiteFindResp --> "0-1" Status : status
   SiteFindResp --> "0-1" GeographicAddressFindResp : geographicAddress

@enduml