@startuml


class ErrorRepresentation {
   code:int
   reason:string
   message:string
   status:int
   referenceError:string
   @type:string
   @schemaLocation:string
}

class Event {
   eventId:string
   eventTime:dateTime
   eventType:string
}
   Event --> "1-1" EventRepresentation : event

class EventRepresentation {
   comment:string
   resource:string
}

@enduml