@startuml

left to right direction
actor Buyer 
actor Seller

skinparam usecase {

}

rectangle {
(1.	Register for Invoice Notification)
(2.	Generate Invoice Notifications)
(3.	Retrieve Invoice List)
(4.	Retrieve Invoice by Invoice Identifier)
(5. Retrieve Invoice Line Item by Invoice Identifier)
(6. Retrieve Printable Invoice)



Buyer --> (1.	Register for Invoice Notification)
Buyer --> (3.	Retrieve Invoice List)
Buyer --> (4.	Retrieve Invoice by Invoice Identifier)
Buyer --> (5. Retrieve Invoice Line Item by Invoice Identifier)
Buyer --> (6. Retrieve Printable Invoice)
(2.	Generate Invoice Notifications)<-- Seller


@enduml