@startuml


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}



class CustomerBillCreateEvent {

    eventType*: string
}
Event <|-- CustomerBillCreateEvent

CustomerBillCreateEvent *-->"1" CustomerBillCreateEventPayload : event


class CustomerBillCreateEventPayload {

    id*: string
    href: string
}



class CustomerBillStateChangeEvent {

    eventType*: string
}
Event <|-- CustomerBillStateChangeEvent

CustomerBillStateChangeEvent *-->"1" CustomerBillStateChangeEventPayload : event


class CustomerBillStateChangeEventPayload {

    id*: string
    href: string
    state*: CustomerBillStateType
}


@enduml
