@startuml
hide footbox

hide footbox
skinparam {
    ParticipantBackgroundColor White
    ParticipantBorderColor Black
}

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/hub with {{calback}} details
Seller --> Buyer: notification confirmation with an {{id}}
...
Buyer -> Seller : POST {{baseUrl}}/productOfferingQualification

alt succesful inquiry
Seller --> Buyer : 201 POQ with {{id}} 
Seller -> Buyer:  {{callbackUrl}}/listener/poqCreateEvent

group repeatedUntil  [POQ reaches a terminal state]
    Seller -> Buyer: {{callbackUrl}}/listener/poqStateChangeEvent
    Buyer -> Seller :   GET {{baseUrl}}/productOfferingQualification/{{id}}
    return POQ in current state
end



else validation or internal problem

Seller --> Buyer : 4xx or 5xx response
end 
...
Buyer -> Seller : DELETE {{baseUrl}}/hub/{{id}} 

@enduml