@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class ProductOfferingQualification {

    effectiveQualificationDate: date-time 
    expectedPOQCompletionDate: date-time 
    href: string 
    id*: string 
    state*: MEFPOQTaskStateType
    stateChange: MEFPOQStateChange[]
}
ProductOfferingQualification --|> ProductOfferingQualification_Common

ProductOfferingQualification *->"1..*" ProductOfferingQualificationItem : productOfferingQualificationItem


class ProductOfferingQualificationItem {

    guaranteedUntilDate: date-time 
    installationInterval: Duration
    serviceabilityConfidenceReason: string 
    serviceabilityConfidence: MEFServiceabilityColor 
    state*: MEFPOQItemTaskStateType 
    stateChange: MEFPOQItemStateChange[]
    terminationError: TerminationError[]
}
ProductOfferingQualificationItem --|> ProductOfferingQualificationItem_Common

ProductOfferingQualificationItem *-->"*" AlternateProductOfferingProposal : alternateProductOfferingProposal

class AlternateProductOfferingProposal {
    id*: string 
    installationInterval: Duration
}

AlternateProductOfferingProposal *-->"1" MEFAlternateProduct : alternateProduct

class MEFProductConfiguration {

    @schemaLocation: uri 
    @type*: string 
}



class MEFAlternateProduct {
    productOffering*: string
    productSpecification: string
}

MEFAlternateProduct *--> MEFProductConfiguration : productConfiguration


class MEFProductRefOrValue {

    href: string 
    id: string 
    productOffering: ProductOfferingRef
    productSpecification: ProductSpecificationRef
    @type*: string 
}

MEFProductRefOrValue *-->"*" RelatedPlaceRefOrValue : place
MEFProductRefOrValue *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValue *->"*" ProductRelationship : productRelationship


class ProductOfferingQualificationItem_Common {

    action*: ProductActionType 
    id*: string 

}

ProductOfferingQualificationItem_Common *-->"1" MEFProductRefOrValue : product
ProductOfferingQualificationItem_Common *->"*" QualificationItemRelationship : qualificationItemRelationship
ProductOfferingQualificationItem_Common *-->"*" RelatedContactInformation : relatedContactInformation


class QualificationItemRelationship {

    id*: string 
    relationshipType*: string 
}

class ProductOfferingQualification_Common {

    instantSyncQualification: boolean 
    projectId: string 
    provideAlternative: boolean 
    requestedPOQCompletionDate: date-time 

}

ProductOfferingQualification_Common *-->"1..*" RelatedContactInformation : relatedContactInformation

class ProductRelationship {

    href: string 
    id*: string 
    groupingKey: string 
    relationshipType*: string 
}

class RelatedContactInformation {

    emailAddress*: string 
    name*: string 
    number*: string 
    numberExtension: string 
    organization: string
    postalAddress: FieldedAddress
    role*: string 
}
class RelatedPlaceRefOrValue {

    @schemaLocation: uri 
    @type*: string 
    role*: string 
}


@enduml
