@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor<<API>> Black
}

hide  <<API>> stereotype

class MEFProductSpecification<<API>> {

    @type*: string 
}


class BwpFlow {

    envelopeRank*: integer 
    couplingFlag*: boolean 
    envelopeId*: string 
    tokenRequestOffset*: integer 
    colorMode*: ColorMode 
}

BwpFlow *-->"1" InformationRate : eirMax
BwpFlow *-->"1" InformationRate : cirMax
BwpFlow *-->"1" DataSize : cbs
BwpFlow *-->"1" DataSize : ebs
BwpFlow *-->"1" InformationRate : cir
BwpFlow *-->"1" InformationRate : eir


class CarrierEthernetPhysicalLink {

    physicalLink*: PhysicalLink 
    id*: string 
}



enum ColorMode {

    COLOR_BLIND
    COLOR_AWARE
}


class ConversationIdToAggregationLinkMap {

    aggLinkList*: integer[] 
    conversationIDs*: ConversationIdRange[]
}


class DataSize {

    dataSizeUnits*: DataSizeUnits 
    dataSizeValue*: integer 
}



enum DataSizeUnits {

    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}
enum EnabledDisabled {

    ENABLED
    DISABLED
}
class Envelope {

    couplingFlagForIndexZero*: boolean 
    envelopeID*: string 
}



class InformationRate {

    irValue*: number 
    irUnits*: IrUnits 
}



enum IrUnits {

    BPS
    KBPS
    MBPS
    GBPS
    TBPS
    PBPS
    EBPS
    ZBPS
    YBPS
}
class L2cpPeering {

    destinationAddress*: string 
    linkIdList: string[] 
    protocolID*: L2cpProtocol
}

enum LinkAggregation {

    NONE
    2_LINK_ACTIVE_STANDBY
    ALL_ACTIVE
    OTHER
}


class OperatorUni as "Operator Uni v1.0.0" {

    defaultCeVlanId: integer 
    maximumNumberOfEndPoints: integer 
    lagLinkMeg: EnabledDisabled 
    linkOam: EnabledDisabled 
    meg: EnabledDisabled 
    linkAggregation: LinkAggregation 
    maximumNumberOfCeVlanIdsPerEndPoint: integer 
    tokenShare: EnabledDisabled 
    maximumServiceFrameSize: integer 
}
MEFProductSpecification <|-- OperatorUni

OperatorUni *-->"*" ConversationIdToAggregationLinkMap : aggregationLinkMap
OperatorUni *-->"*" BwpFlow : ingressBandwidthProfile
OperatorUni *-->"1..*" UniPhysicalLink : listofPhysicalLinks
OperatorUni *-->"*" BwpFlow : egressBandwidthProfile
OperatorUni *-->"*" L2cpPeering : l2cpPeering
OperatorUni *-->"*" Envelope : envelopes


enum PhysicalLink {

    10BASE_T
    100BASE_T
    1000BASE_T
    25GBASE_T
    40GBASE_T
    400GBASE_SR8
    ... And many modre...
    OTHER
}
enum UniConnectorGender {

    SOCKET
    PLUG
}
enum UniConnectorType {

    SC
    LC
    RJ45
    FC
    D4
    OTHER
}
class UniPhysicalLink {

}
CarrierEthernetPhysicalLink <|-- UniPhysicalLink
UniSpecifcAttributes <|-- UniPhysicalLink



class UniSpecifcAttributes {

    uniConnectorGender*: UniConnectorGender 
    synchronousEthernet*: EnabledDisabled 
    uniConnectorType*: UniConnectorType 
    precisionTiming*: EnabledDisabled 
}



@enduml
