@startjson
{
"@type": "urn:mef:lso:spec:cantata-sonata:evpl-evc:v1.0.0:all",
"cTagPcpPreservation":"TRUE",
"cTagDeiPreservation":"FALSE",
"frameDisposition": {
  "broadcast": "DELIVER_UNCONDITIONALLY",
  "unicast": "DELIVER_CONDITIONALLY",
  "multicast": "DELIVER_UNCONDITIONALLY"
  },
"listOfCosNames": ["low"],
"availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeInterval": "<<skipped>>",
      "startTime":  "<<skipped>>"
    }
  ],
  "maximumFrameSize": 1522,
  "evcEndPointZ": {
    "identifier": "NewYork_UNI-EP2",
    "others": "<<skipped>>"
  },
    "evcEndPointA": {
    "identifier": "SanFrancisco_UNI-EP1",
    "others": "<<skipped>>"
  }
}



@endjson