@startjson
#highlight "quoteItem" / "0"/ "action"
#highlight "quoteItem" / "0"/ "product" / "id"
#highlight "quoteItem" / "1"/ "action"
#highlight "quoteItem" / "1"/ "product" / "id"
#highlight "quoteItem" / "1"/ "product" / "productRelationship" / "0" / "relationshipType"
#highlight "quoteItem" / "1"/ "product" / "productRelationship" / "0" / "id"
#highlight "quoteItem" / "1"/ "product" / "productRelationship" / "1" / "relationshipType"
#highlight "quoteItem" / "1"/ "product" / "productRelationship" / "1" / "id"
#highlight "quoteItem" / "0"/ "product" / "place" / "0"/ "@type"
#highlight "quoteItem" / "0"/ "product" / "place" / "0"/ "id"
#highlight "quoteItem" / "0"/ "product" / "place" / "0"/ "role"
{
  "requestedQuoteCompletionDate": "2022-11-28T22:00:00Z",
  "externalId": "BuyerQuote-00002",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProjectX",
  "instantSyncQuote": false,
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "buyerContactInformation",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "quoteItem": [
    {
      "id": "item-001",
      "action": "remove",
      "product": {
        "id": "Denver_UNI",
        "productOffering": {
          "id": "000074"
        },
        "productConfiguration": "<<skipped>>"
      }
    },
    {
      "id": "item-002",
      "action": "remove",
      "product": {
        "id": "ROOT_ENDPOINT_OF_EVC",
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": "<<skipped>>"
      }
    }
  ]
}
@endjson