@startjson
#highlight "productOfferingQualificationItem"
#highlight "productOfferingQualificationItem" / "0" 
#highlight "productOfferingQualificationItem" / "0" / "product" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "1" 
#highlight "productOfferingQualificationItem" / "1" / "product" 
#highlight "productOfferingQualificationItem" / "1" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "1" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "2" / "product" 
#highlight "productOfferingQualificationItem" / "2" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "2" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "3" / "product" 
#highlight "productOfferingQualificationItem" / "3" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "3" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "4" / "product" 
#highlight "productOfferingQualificationItem" / "4" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "4" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "5" / "product" 
#highlight "productOfferingQualificationItem" / "5" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "5" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "6" / "product" 
#highlight "productOfferingQualificationItem" / "6" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "6" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "7" / "product" 
#highlight "productOfferingQualificationItem" / "7" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "7" / "product" / "productConfiguration" / "@type"
#highlight "productOfferingQualificationItem" / "8" / "product" 
#highlight "productOfferingQualificationItem" / "8" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "8" / "product" / "productConfiguration" / "@type"

{
  "instantSyncQualification": true,
  "externalId": "BuyerPoq-00001",
  "provideAlternative": false,
  "projectId": "BuyerProjectX",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.example.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
  {
      "**id**": "**item-002**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "DenverAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "**id**": "**item-003**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "HoustonAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "**id**": "**item-004**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "OklahomaAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
        {
      "**id**": "**item-005**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000074"
        },
        "place": [
          {
            "@type": "GeographicAddressRef",
            "id": "MiamiAddress-id-1",
            "role": "INSTALL_LOCATION"
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "other": "<<skipped>>"
        }
      }
    },
    {
      "**id**": "**item-006**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc-endpoint:v1.0.0:all",
          "other": "<<skipped>>"
        },
        "**qualificationItemRelationship**": [
        {
          "**relationshipType**": "**ROOT_ENDPOINT_OF_EVC**",
          "**id**": "**item-001**"
        },
        {
          "**relationshipType**": "**CONNECTS_TO_UNI**",
          "**id**": "**item-002**"
        }

      ]
      }
    },
    {
      "**id**": "**item-007**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc-endpoint:v1.0.0:all",
          "other": "<<skipped>>"
        },
        "**qualificationItemRelationship**": [
        {
          "**relationshipType**": "**LEAF_ENDPOINT_OF_EVC**",
          "**id**": "**item-001**"
        },
        {
          "**relationshipType**": "**CONNECTS_TO_UNI**",
          "**id**": "**item-003**"
        }
      ]
      }
    },
    {
      "**id**": "**item-008**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc-endpoint:v1.0.0:all",
          "other": "<<skipped>>"
        },
        "**qualificationItemRelationship**": [
        {
          "**relationshipType**": "**LEAF_ENDPOINT_OF_EVC**",
          "**id**": "**item-001**"
        },
        {
          "**relationshipType**": "**CONNECTS_TO_UNI**",
          "**id**": "**item-004**"
        }
      ]
      }
    },
        {
      "**id**": "**item-009**",
      "action": "add",
      "product": {
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc-endpoint:v1.0.0:all",
          "other": "<<skipped>>"
        },
        "**qualificationItemRelationship**": [
        {
          "**relationshipType**": "**LEAF_ENDPOINT_OF_EVC**",
          "**id**": "**item-001**"
        },
         {
          "**relationshipType**": "**CONNECTS_TO_UNI**",
          "**id**": "**item-005**"
        }
      ]
      }
    }
  ]
}
@endjson