@startjson
{
  "slsCosNameEntry": [
    {
      "cosName": "low",
      "consecutiveIntervalN": 3,
      "deltaT": 10,
      "thresholdC": 0.5,
      "oneWayFrameDelayPmMetric": [
        {
          "oneWayFdObjective": {
            "shortDurationValue": 100,
            "shortDurationUnits": "MS"
          },
          "oneWayFdPercentile": 99.5,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R",
              "fromCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L"
            },
            {
              "toCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L",
              "fromCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R"
            }
          ]
        }
      ],
      "oneWayMeanFrameDelayPmMetric": [],
      "oneWayFrameDelayRangePmMetric": [],
      "oneWayInterFrameDelayVariationPmMetric": [],
      "oneWayFrameLossRatioPmMetric": [
        {
          "oneWayFlrObjective": 0.001,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R",
              "fromCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L"
            },
            {
              "toCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L",
              "fromCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R"
            }
          ]
        }
      ],
      "oneWayAvailabilityPmMetric": [],
      "oneWayHighLossIntervalsPmMetric": [],
      "oneWayConsecutiveHighLossIntervalsPmMetric": [],
      "oneWayCompositePmMetric": [],
      "oneWayGroupAvailabilityPmMetric": []
    }
  ],
  "timeInterval": {
    "longDurationUnits": "MONTH",
    "longDurationValue": 1
  },
  "startTime": "2021-09-01T00:00:00Z"
}
@endjson