@startjson
#highlight "productOfferingQualificationItem" / "0"/ "action"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "id"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "productRelationship" / "0" / "relationshipType"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "productRelationship" / "0" / "id"


{
  "instantSyncQualification": true,
  "externalId": "BuyerPoq-00003",
  "provideAlternative": false,
  "projectId": "BuyerProjectX",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.example.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "modify",
      "product": {
        "id": "EPL-0001",
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": "<<skipped>>",
        "productRelationship": [
          {
            "relationshipType": "CONNECTS_TO_UNI",
            "id": "NewYork_UNI"
          }
        ]
      }
    }
  ]
}
@endjson