@startjson
{
  "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
  "listOfCosNames": "",
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeDuration": "<<skipped>>",
      "startTime": "<<skipped>>"
    }
  ],
  "maximumFrameSize": 1526,
  "evcEndPointA": {
    "identifier": "NewYork_UNI-EP1",
    "subscriberMegMip": "",
    "egressMap": "",
    "colorMap": "<<skipped>>",
    "evcEndPointEnvelopes":"",
    "ingressClassOfServiceMap": "<<skipped>>",
    "ingressBandwidthProfilePerClassOfServiceName": "<<skipped>>"
  },
  "evcEndPointZ": {
    "identifier": "Washington_UNI-EP1",
    "subscriberMegMip": "",
    "egressMap": "",
    "colorMap": "<<skipped>>",
    "evcEndPointEnvelopes":"",
    "ingressClassOfServiceMap": "<<skipped>>",
    "ingressBandwidthProfilePerClassOfServiceName": "<<skipped>>"
  }
}
@endjson