@startjson
 {
            "identifier": "SanFrancisco_UNI-EP1",
            "subscriberMegMip":"ENABLED",
            "egressMap": [
              {
                "evcEgressMapEntries": [
                  {
                    "cosName": "low",
                    "pcpYellow": 3,
                    "deiYellow": 1,
                    "deiGreen": 0,
                    "pcpGreen": 3
                  }
                ]
              }
            ],
            "colorMap": {
              "mapType": "DEI"
            },
            "evcEndPointEnvelopes": [
              {
                "couplingFlagForIndexZero": "TRUE",
                "envelopeID": "env1"
              }
            ],
            "ingressClassOfServiceMap": {
              "mapType": "ENDPOINT",
              "map_M":"low",
              "l2cp_P":[]
            },
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeValue": 0,
                    "dataSizeUnits": "KBYTES"
                  },
                  "couplingFlag": true,
                  "envelopeId": "env1",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeValue": 40,
                    "dataSizeUnits": "KBYTES"
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 70,
                    "irUnits": "MBPS"
                  },
                  "evcEndPointMap": [
                    {
                      "vlanId": [2, 3],
                      "vlanType": "LIST"
                    }
                  ],
                    "sourceAddressMacLimit": [],
                    "egressBandwidthProfilePerClassofServiceName": []
                }
              }
            ]
          } 
@endjson