@startjson
{
  "slsCosNameEntry": [
    {
      "cosName": "low",
      "consecutiveIntervalN": 3,
      "deltaT": 10,
      "thresholdC": 0.5,
      "oneWayFrameDelayPmMetric": [
        {
          "oneWayFdObjective": {
            "shortDurationValue": 100,
            "shortDurationUnits": "MS"
          },
          "oneWayFdPercentile": 99.5,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1",
              "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
            },
            {
              "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
              "fromCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1"
            }
          ]
        }
      ],
      "oneWayMeanFrameDelayPmMetric": [],
      "oneWayFrameDelayRangePmMetric": [],
      "oneWayInterFrameDelayVariationPmMetric": [],
      "oneWayFrameLossRatioPmMetric": [
        {
          "oneWayFlrObjective": 0.001,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1",
              "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
            },
            {
              "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
              "fromCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1"
            }
          ]
        }
      ],
      "oneWayAvailabilityPmMetric": [],
      "oneWayHighLossIntervalsPmMetric": [],
      "oneWayConsecutiveHighLossIntervalsPmMetric": [],
      "oneWayCompositePmMetric": [],
      "oneWayGroupAvailabilityPmMetric": []
    },
    {
      "cosName": "high",
      "consecutiveIntervalN": 3,
      "deltaT": 10,
      "thresholdC": 0.5,
      "oneWayFrameDelayPmMetric": [
        {
          "oneWayFdObjective": {
            "shortDurationValue": 20,
            "shortDurationUnits": "MS"
          },
          "oneWayFdPercentile": 99.7,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1",
              "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
            },
            {
              "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
              "fromCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1"
            }
          ]
        }
      ],
      "oneWayMeanFrameDelayPmMetric": [],
      "oneWayInterFrameDelayVariationPmMetric": [],
      "oneWayFrameLossRatioPmMetric": [
        {
          "oneWayFlrObjective": 0.0001,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1",
              "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
            },
            {
              "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
              "fromCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1"
            }
          ]
        }
      ],
      "oneWayFrameDelayRangePmMetric": [
        {
          "oneWayFdrObjective": {
            "shortDurationValue": 10,
            "shortDurationUnits": "MS"
          },
          "oneWayFdrPercentile": 99.7,
          "orderedPairList": [
            {
              "toCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1",
              "fromCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2"
            },
            {
              "toCarrierEthernetServiceEndPoint": "NewYork_UNI-EP2",
              "fromCarrierEthernetServiceEndPoint": "SanFrancisco_UNI-EP1"
            }
          ]
        }
      ],
      "oneWayAvailabilityPmMetric": [],
      "oneWayHighLossIntervalsPmMetric": [],
      "oneWayConsecutiveHighLossIntervalsPmMetric": [],
      "oneWayCompositePmMetric": [],
      "oneWayGroupAvailabilityPmMetric": []
    }
  ],
  "timeInterval": {
    "longDurationUnits": "MONTH",
    "longDurationValue": 1
  },
  "startTime": "2021-09-01T00:00:00Z"
}
@endjson