@startjson
#highlight "productOfferingQualificationItem" / "0"/ "action"
#highlight "productOfferingQualificationItem" / "0"/ "product" / "id"
#highlight "productOfferingQualificationItem" / "1"/ "action"
#highlight "productOfferingQualificationItem" / "1"/ "product" / "id"

{
  "instantSyncQualification": true,
  "externalId": "BuyerPoq-00003",
  "provideAlternative": false,
  "projectId": "BuyerProjectX",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.example.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "remove",
      "product": {
        "id": "Miami_UNI",
        "productOffering": {
          "id": "000074"
        },
        "productConfiguration": "<<skipped>>"
      }
    },
    {
      "id": "item-002",
      "action": "remove",
      "product": {
        "id": "LEAF_ENDPOINT_OF_EVC",
        "productOffering": {
          "id": "000075"
        },
        "productConfiguration": "<<skipped>>"
      }
    }
  ]
}
@endjson