@startjson
{
          "@type": "urn:mef:lso:spec:cantata-sonata:evptree-evc:v1.0.0:all",
          "cTagPcpPreservation": "TRUE",
          "cTagDeiPreservation": "FALSE",
          "frameDisposition": {
            "broadcast": "DELIVER_UNCONDITIONALLY",
            "unicast": "DELIVER_CONDITIONALLY",
            "multicast": "DELIVER_UNCONDITIONALLY"
          },
          "listOfCosNames": ["low"],
          "availableMegLevel": "6",
          "carrierEthernetSls": [
            {
              "slsCosNameEntry": [
                {
                  "cosName": "low",
                  "consecutiveIntervalN": 3,
                  "deltaT": 10,
                  "thresholdC": 0.5,
                  "oneWayFrameDelayPmMetric": [
                    {
                      "oneWayFdObjective": {
                        "shortDurationValue": 100,
                        "shortDurationUnits": "MS"
                      },
                      "oneWayFdPercentile": 99.5,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R",
                          "fromCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L",
                          "fromCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R"
                        }
                      ]
                    }
                  ],
                  "oneWayMeanFrameDelayPmMetric": [],
                  "oneWayFrameDelayRangePmMetric": [],
                  "oneWayInterFrameDelayVariationPmMetric": [],
                  "oneWayFrameLossRatioPmMetric": [
                    {
                      "oneWayFlrObjective": 0.001,
                      "orderedPairList": [
                        {
                          "toCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R",
                          "fromCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L"
                        },
                        {
                          "toCarrierEthernetServiceEndPoint": "Oklahoma_UNI-EP1_L",
                          "fromCarrierEthernetServiceEndPoint": "Denver_UNI-EP1_R"
                        }
                      ]
                    }
                  ],
                  "oneWayAvailabilityPmMetric": [],
                  "oneWayHighLossIntervalsPmMetric": [],
                  "oneWayConsecutiveHighLossIntervalsPmMetric": [],
                  "oneWayCompositePmMetric": [],
                  "oneWayGroupAvailabilityPmMetric": []
                }
              ],
              "timeDuration": {
                "timeDurationValue": 1,
                "timeDurationUnits": "MONTH"
              },
              "startTime": "2022-10-12T00:00:00Z"
            }
          ],
          "maximumFrameSize": 1522
        }
@endjson