@startjson
#highlight "productOfferingQualificationItem" / "0"/"product"/"productConfiguration"/"evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"/"irValue"
#highlight "productOfferingQualificationItem" / "0"/"product"/"productConfiguration"/"evcEndPointA"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"/"irValue"
#highlight "productOfferingQualificationItem" / "0"/"product"/"productConfiguration"/"evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eir"/"irValue"
#highlight "productOfferingQualificationItem" / "0"/"product"/"productConfiguration"/"evcEndPointZ"/"ingressBandwidthProfilePerClassOfServiceName"/ "0"/"bwpFlow"/"eirMax"/"irValue"

{
  "instantSyncQualification": true,
  "externalId": "BuyerPoq-00003",
  "provideAlternative": false,
  "projectId": "BuyerProjectX",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.example.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "organization": "Buyer Co.",
      "role": "buyerContactInformation"
    }
  ],
  "productOfferingQualificationItem": [
    {
      "id": "item-001",
      "action": "modify",
      "product": {
        "id": "EPL-0001",
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:epl-evc:v1.0.0:all",
          "listOfCosNames": ["low"],
          "availableMegLevel": "6",
          "carrierEthernetSls": [],
          "maximumFrameSize": 1522,
          "evcEndPointA": {
            "identifier": "NewYork_UNI-EP1",
            "subscriberMegMip": "ENABLED",
            "egressMap": [
              {
                "evcEgressMapEntries": [
                  {
                    "cosName": "low",
                    "pcpYellow": 3,
                    "deiYellow": 1,
                    "deiGreen": 0,
                    "pcpGreen": 3
                  }
                ]
              }
            ],
            "colorMap": {
              "mapType": "DEI"
            },
            "evcEndPointEnvelopes": [
              {
                "couplingFlagForIndexZero": "TRUE",
                "envelopeID": "env1"
              }
            ],
            "ingressClassOfServiceMap": {
              "mapType": "ENDPOINT",
              "map_M": "low",
              "l2cp_P": []
            },
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 100,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeValue": 0,
                    "dataSizeUnits": "KBYTES"
                  },
                  "couplingFlag": true,
                  "envelopeId": "env1",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeValue": 40,
                    "dataSizeUnits": "KBYTES"
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 100,
                    "irUnits": "MBPS"
                  }
                }
              }
            ]
          },
          "evcEndPointZ": {
            "identifier": "Washington_UNI-EP1",
            "subscriberMegMip": "ENABLED",
            "egressMap": [
              {
                "evcEgressMapEntries": [
                  {
                    "cosName": "low",
                    "pcpYellow": 3,
                    "deiYellow": 1,
                    "deiGreen": 0,
                    "pcpGreen": 3
                  }
                ]
              }
            ],
            "colorMap": {
              "mapType": "DEI"
            },
            "evcEndPointEnvelopes": [
              {
                "couplingFlagForIndexZero": "TRUE",
                "envelopeID": "env1"
              }
            ],
            "ingressClassOfServiceMap": {
              "mapType": "ENDPOINT",
              "map_M": "low",
              "l2cp_P": []
            },
            "ingressBandwidthProfilePerClassOfServiceName": [
              {
                "classOfServiceName": "low",
                "bwpFlow": {
                  "eirMax": {
                    "irValue": 100,
                    "irUnits": "MBPS"
                  },
                  "envelopeRank": 1,
                  "cirMax": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "cbs": {
                    "dataSizeValue": 0,
                    "dataSizeUnits": "KBYTES"
                  },
                  "couplingFlag": true,
                  "envelopeId": "env1",
                  "tokenRequestOffset": 0,
                  "ebs": {
                    "dataSizeValue": 40,
                    "dataSizeUnits": "KBYTES"
                  },
                  "colorMode": "COLOR_BLIND",
                  "cir": {
                    "irValue": 0,
                    "irUnits": "MBPS"
                  },
                  "eir": {
                    "irValue": 100,
                    "irUnits": "MBPS"
                  }
                }
              }
            ]
          }
        }
       }
    }
  ]
}

@endjson