@startjson
#highlight "cTagPcpPreservation"
#highlight "cTagDeiPreservation"
#highlight "frameDisposition"
{
  "@type": "urn:mef:lso:spec:cantata-sonata:evplan-evc:v1.0.0:all",
  "cTagPcpPreservation": "TRUE",
  "cTagDeiPreservation": "FALSE",
  "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "listOfCosNames": "",
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeInterval": "<<skipped>>",
      "startTime": "<<skipped>>"
    }
  ],
  "maximumFrameSize": 1526
}
@endjson