@startjson
#highlight "quoteItem" / "0"/"quoteItemRelationship"/"0"/"relationshipType"
{
  "requestedQuoteCompletionDate": "2022-10-28T22:00:00Z",
  "externalId": "BuyerQuote-00001",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProjectX",
  "instantSyncQuote": false,
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "buyerContactInformation",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "quoteItem": [
    {
      "id": "item-001",
      "action": "add",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "quoteItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-002"
        }
      ],
      "relatedContactInformation": [
        {
          "number": "12-345-6789",
          "emailAddress": "john.example@buyer.example.com",
          "role": "quoteItemTechnicalContact",
          "organization": "Buyer Co.",
          "name": "John Example",
          "numberExtension": "1234"
        }
      ],
      "product": "<<skipped>>"
    },
    {
      "action": "add",
      "id": "item-002",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "calendarMonths"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "relatedContactInformation": [
        {
          "number": "12-345-6789",
          "emailAddress": "john.example@buyer.example.com",
          "role": "quoteItemTechnicalContact",
          "organization": "Buyer Co.",
          "name": "John Example",
          "numberExtension": "1234"
        },
        {
          "number": "12-345-6789",
          "emailAddress": "john.example@buyer.example.com",
          "role": "quoteItemLocationContact",
          "organization": "Buyer Co.",
          "name": "John Example",
          "numberExtension": "1234"
        }
      ],
      "product":  "<<skipped>>"
    }
  ]
}
@endjson