@startjson
{
          "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-subscriber-uni:v1.0.0:all",
          "listOfPhyLinks": [
            {
              "uniConnectorGender": "SOCKET",
              "autoNegotiation": "ENABLED",
              "synchronousEthernet": "ENABLED",
              "uniConnectorType": "RJ45",
              "precisionTiming": "DISABLED"
            }
          ],
          "virtualFrameMap": [],
          "portConversation": [],
          "maximumNumberOfEndPoint": 6,
          "lagLinkMeg": "ENABLED",
          "l2cpAddressSet": "CTB",
          "linkOam": "DISABLED",
          "meg": "ENABLED",
          "linkAggregation": "NONE",
          "l2cpPeering": [],
          "maximumNumberOfCtagVlanIdsPerEndPoint": 4094,
          "tokenShare": "ENABLED",
          "maximumServiceFrameSize": 1522,
          "envelopes": [
            {
              "couplingFlagForIndexZero": "TRUE",
              "envelopeID": "env1"
            },
            {
              "couplingFlagForIndexZero": "TRUE",
              "envelopeID": "env2"
            }
          ],
          "instantiation": "PHYSICAL"
        }

@endjson