@startjson
#highlight "productOrderItem" / "0"/ "action"
#highlight "productOrderItem" / "0"/ "product" / "id"
#highlight "productOrderItem" / "0"/ "product" / "productRelationship" / "0" / "relationshipType"
#highlight "productOrderItem" / "0"/ "product" / "productRelationship" / "0" / "id"


{
  "externalId": "BuyerOrder-00002",
  "projectId": "BuyerProjectX",
  "requestedCompletionDate": "2020-12-04T23:00:00Z",
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "productOrderContact",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "productOrderItem": [
    {
      "action": "modify",
      "expediteIndicator": false,
      "id": "item-001",
      "relatedContactInformation": [
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ProductOrderItemContact@example.com",
          "role": "buyerProductOrderItemContact",
          "name": "Buyer Product Order Item Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ImplementationContact@example.com",
          "role": "buyerImplementationContact",
          "name": "Buyer Implementation Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.TechnicalContact@example.com",
          "role": "buyerTechnicalContact",
          "name": "Buyer Technical Contact "
        },
        {
          "emailAddress": "bill.contact@example.com",
          "name": "Bill Contact",
          "number": "+12-345-678-90",
          "organization": "Example Company",
          "role": "billingContact"
        }
      ],
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001"
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "requestedCompletionDate": "2021-11-04T23:00:00Z",
      "product": {
        "id": "EPL-0001",
        "productOffering": {
          "id": "000073"
        },
        "productConfiguration": "<<skipped>>",
        "productRelationship": [
          {
            "relationshipType": "CONNECTS_TO_UNI",
            "id": "NewYork_UNI"
          }
        ]
      }
    }
  ]
}
@endjson