@startjson
#highlight "cTagPcpPreservation"
#highlight "cTagDeiPreservation"
#highlight "frameDisposition"

{
  "@type": "urn:mef:lso:spec:sonata:evlan:v4.0.0:all",
  "cTagPcpPreservation": "TRUE",
  "cTagDeiPreservation": "FALSE",
    "frameDisposition": {
    "broadcast": "DELIVER_UNCONDITIONALLY",
    "unicast": "DELIVER_CONDITIONALLY",
    "multicast": "DELIVER_UNCONDITIONALLY"
  },
  "listOfCosNames": "low",
  "availableMegLevel": "6",
  "carrierEthernetSls": [
    {
      "slsCosNameEntry": "<<skipped>>",
      "timeInterval": "<<skipped>>",
      "startTime": "<<skipped>>"
    }
  ],
  "maximumFrameSize": 1526,
  "evcEndPointA": {
    "identifier": "NewYork_UNI-EP1",
    "subscriberMegMip": "",
    "egressMap": "",
    "colorMap": "<<skipped>>",
    "evcEndPointEnvelopes":"",
    "ingressClassOfServiceMap": "<<skipped>>",
    "ingressBandwidthProfilePerClassOfServiceName": "<<skipped>>",
    "sourceAddressMacLimit": "",
    "egressBandwidthProfilePerClassofServiceName": ""
  },
    "evcEndPointZ": {
    "identifier": "Washington_UNI-EP1",
    "subscriberMegMip": "",
    "egressMap": "",
    "colorMap": "<<skipped>>",
    "evcEndPointEnvelopes":"",
    "ingressClassOfServiceMap": "<<skipped>>",
    "ingressBandwidthProfilePerClassOfServiceName": "<<skipped>>",
    "sourceAddressMacLimit": "",
    "egressBandwidthProfilePerClassofServiceName": ""
  }
}
@endjson