@startjson
#highlight "productOrderItem" / "2"/"productOrderItemRelationship"/"0"/"relationshipType"
#highlight "productOrderItem" / "2"/"productOrderItemRelationship"/"1"/"relationshipType"
{
  "externalId": "BuyerOrder-00001",
  "projectId": "BuyerProjectX",
  "requestedCompletionDate": "2020-11-04T23:00:00Z",
  "relatedContactInformation": [
    {
      "number": "12-345-6789",
      "emailAddress": "john.example@buyer.example.com",
      "role": "productOrderContact",
      "organization": "Buyer Co.",
      "name": "John Example",
      "numberExtension": "1234"
    }
  ],
  "productOrderItem": [
    {
      "action": "add",
      "expediteIndicator": false,
      "id": "item-001",
      "relatedContactInformation": [
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ProductOrderItemContact@example.com",
          "role": "buyerProductOrderItemContact",
          "name": "Buyer Product Order Item Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ImplementationContact@example.com",
          "role": "buyerImplementationContact",
          "name": "Buyer Implementation Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.TechnicalContact@example.com",
          "role": "buyerTechnicalContact",
          "name": "Buyer Technical Contact "
        },
        {
          "emailAddress": "bill.contact@example.com",
          "name": "Bill Contact",
          "number": "+12-345-678-90",
          "organization": "Example Company",
          "role": "billingContact"
        }
      ],
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001"
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "requestedCompletionDate": "2021-11-04T23:00:00Z",
      "product": "<<skipped>>"
    },
    {
      "id": "item-002",
      "action": "add",
      "expediteIndicator": false,
      "requestedCompletionDate": "2021-11-25T23:00:00Z",
      "relatedContactInformation": [
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ProductOrderItemContact@example.com",
          "role": "buyerProductOrderItemContact",
          "name": "Buyer Product Order Item Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ImplementationContact@example.com",
          "role": "buyerImplementationContact",
          "name": "Buyer Implementation Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.TechnicalContact@example.com",
          "role": "buyerTechnicalContact",
          "name": "Buyer Technical Contact "
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ItemServiceSiteContact@example.com",
          "role": "orderItemServiceSiteContact",
          "name": "Buyer Technical Contact "
        },
        {
          "emailAddress": "bill.contact@example.com",
          "name": "Bill Contact",
          "number": "+12-345-678-90",
          "organization": "Example Company",
          "role": "billingContact"
        }
      ],
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001"
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "product": "<<skipped>>"
    },
    {
      "id": "item-003",
      "action": "add",
      "productOrderItemRelationship": [
        {
          "relationshipType": "CONNECTS_TO_UNI",
          "id": "item-002"
        },
        {
          "relationshipType": "ROOT_ENDPOINT_OF_EVC",
          "id": "item-001"
        }
      ],
      "expediteIndicator": false,
      "requestedCompletionDate": "2021-11-25T23:00:00Z",
      "relatedContactInformation": [
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ProductOrderItemContact@example.com",
          "role": "buyerProductOrderItemContact",
          "name": "Buyer Product Order Item Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ImplementationContact@example.com",
          "role": "buyerImplementationContact",
          "name": "Buyer Implementation Contact"
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.TechnicalContact@example.com",
          "role": "buyerTechnicalContact",
          "name": "Buyer Technical Contact "
        },
        {
          "number": "+12-345-678-90",
          "emailAddress": "Buyer.ItemServiceSiteContact@example.com",
          "role": "orderItemServiceSiteContact",
          "name": "Buyer Technical Contact "
        },
        {
          "emailAddress": "bill.contact@example.com",
          "name": "Bill Contact",
          "number": "+12-345-678-90",
          "organization": "Example Company",
          "role": "billingContact"
        }
      ],
      "billingAccount": {
        "id": "00000000-1111-0000-0000-000000000001"
      },
      "agreementName": "Buyer-Seller General Agreement 03/2021",
      "product": "<<skipped>>"
    }
  ]
}
@endjson