@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}

set namespaceSeparator none

class AlternateProductOfferingProposal {
}

AlternateProductOfferingProposal *-->"1" MEFAlternateProduct : alternateProduct

class MEFAlternateProduct {
    productOffering*: ProductOfferingRef
    productSpecification: ProductSpecificationRef

}
class MEFAlternateProduct {


}

class MEFProductConfiguration {
    @type*: string <<discriminator>>
}

MEFAlternateProduct *-->"1" MEFProductConfiguration : productConfiguration



class MEFProductRefOrValue {

    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    productOffering: ProductOfferingRef
    productRelationship: ProductRelationshipWithGrouping
    productSpecification: ProductSpecificationRef
   
}

MEFProductRefOrValue *--> MEFProductConfiguration : productConfiguration


class urn:mef:lso:spec:sonata:OperatorUNI:1.0.0:poq <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:OperatorUNI:1.0.0:poq"



class urn:mef:lso:spec:sonata:AccessElineOvc:1.0.0:poq <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:AccessElineOvc:1.0.0:poq"

@enduml
