@startuml
hide footbox

hide footbox
skinparam {
    ParticipantBackgroundColor White
    ParticipantBorderColor Black
}

participant Buyer
participant Seller


Buyer -> Seller : POST {{baseUrl}}/productOfferingQualification \ninstantSyncQualification=false

alt succesful inquiry
    Seller --> Buyer : 201 POQ with {{id}} in `acknowledged` state
    
    ...
    
    group repeatedUntil  [POQ reaches a terminal state]
        Buyer -> Seller :   GET {{baseUrl}}/productOfferingQualification/{{id}}
        return 200 POQ in current state
    end
else validation or internal problem

Seller --> Buyer : 4xx or 5xx response

end 
@enduml