@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Event {

    eventId*: string 
    eventType*: PoqEventType 
    eventTime*: date-time 
}

Event *-->"1" PoqEvent : event


class PoqEvent {

    id: string 
    href: string 
    buyerId: string
    sellerId: string
}



enum PoqEventType {

    poqCreateEvent
    poqStateChangeEvent
}
@enduml
