@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class RelatedPlaceRefOrValue {

    @schemaLocation: uri
    @type*: string <<discriminator>>
    role*: string
}

class FieldedAddress {

    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    streetName*: string
    streetNr: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetNrSuffix: string
    streetSuffix: string
    streetType: string
}
RelatedPlaceRefOrValue <|-- FieldedAddress

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class FormattedAddress {

    addrLine1*: string
    addrLine2: string
    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
}
RelatedPlaceRefOrValue <|-- FormattedAddress



class GeographicSubAddress {

    buildingName: string
    id: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class GeographicAddressLabel {

    externalReferenceId*: string
    externalReferenceType*: string
}
RelatedPlaceRefOrValue <|-- GeographicAddressLabel



class MEFGeographicPoint {

    spatialRef*: string 
    x*: string 
    y*: string 
    z: string 
}
RelatedPlaceRefOrValue <|-- MEFGeographicPoint

class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}


class GeographicAddressRef  {

    href: string 
    id*: string 
}
RelatedPlaceRefOrValue <|-- GeographicAddressRef 

class GeographicSiteRef  {

    href: string 
    id*: string 
}
RelatedPlaceRefOrValue <|-- GeographicSiteRef 


@enduml