@startuml


skinparam activity {
    BackgroundColor White
    BorderColor Black
}

start
if(immediate response?) then (yes)
    if(sufficient information provided?) then (yes)
        :done.ready;
    else (no)
        :terminatedWithError;
    endif
    stop
else (no)
    :acknowledged;
    :inProgress;
endif
if(insufficient information \n for at least one other POQ item?) then (yes)
    :terminatedWithError;
elseif(Seller able to meet \n response time requirements?) then (yes)
    :done.ready;
else (no)
    :done
    .unableToProvide;
endif
stop
@enduml