@startuml

class GeographicAddressRefOrQuery {
    --
    discriminator:
    GeographicAddressRef
    GeographicAddress_Query
}

GeographicAddressRefOrQuery ..> GeographicAddressRef : ""
GeographicAddressRefOrQuery ..> GeographicAddress_Query : ""




class GeographicAddressRef {

    href: string
    id*: string
    @type*: string
}



class GeographicSite {

    id*: string
    href: string
    name*: string
    administrativeAuthority*: string
    customerName*: string
    siteRestrictionType*: SiteRestrictionType
    networkType*: SiteNetworkType
    @type*: string
}

GeographicSite *-->"1" GeographicAddressRefOrQuery : place
GeographicSite *-->"1..*" SubUnit : subUnit


class GeographicSite_Query {

    name: string
    administrativeAuthority: string
    customerName: string
    siteRestrictionType: SiteRestrictionType
    networkType: SiteNetworkType
}

GeographicSite_Query *-->"1" GeographicAddressRefOrQuery : place
GeographicSite_Query *-->"*" SubUnit : subUnit


enum SiteNetworkType {

    offNet
    onNet
}
enum SiteRestrictionType {

    public
    private
}
class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit


class FormattedAddressRepresentation {

    formattedAddress*: string
    language: string
}



class GeographicAddress_Query {

    @type*: string
}

GeographicAddress_Query *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress_Query *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress_Query *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress_Query *-->"*" LabelRepresentation : labelRepresentation


class GeographicPointRepresentation {

    spatialRef*: string
    latitude*: string
    longitude*: string
    elevation: string
}



class LabelRepresentation {

    label*: string
    administrativeAuthority*: string
    language: string
}



class GeographicAddressRefOrQuery {

}



class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



@enduml
