@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class FieldedAddress {

    city*: string 
    country*: string 
    locality: string 
    postcode: string 
    postcodeExtension: string 
    stateOrProvince: string 
    streetName*: string 
    streetNr: string 
    streetNrLast: string 
    streetNrLastSuffix: string 
    streetNrSuffix: string 
    streetSuffix: string 
    streetType: string 
}
GeographicAddressRefOrValue <|-- FieldedAddress

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class FormattedAddress {

    addrLine1*: string 
    addrLine2: string 
    city*: string 
    country*: string 
    locality: string 
    postcode: string 
    postcodeExtension: string 
    stateOrProvince: string 
}
GeographicAddressRefOrValue <|-- FormattedAddress



class GeographicAddressLabel {

    externalReferenceId*: string 
    externalReferenceType*: string 
}
GeographicAddressRefOrValue <|-- GeographicAddressLabel



class GeographicAddressRef {

    href: string 
    id*: string 
}
GeographicAddressRefOrValue <|-- GeographicAddressRef



class GeographicAddressRefOrValue {

    @schemaLocation: uri 
    @type*: string 
}



class GeographicSite {

    id*: string 
    href: string 
    description: string 
    name: string 
    companyName: string 
    customerName: string 
    siteType: MEFSiteType 
    @type: string 
}

GeographicSite *-->"*" GeographicAddressRefOrValue : place
GeographicSite *-->"*" RelatedContactInformation : relatedContactInformation


class GeographicSubAddress {

    buildingName: string 
    levelNumber: string 
    levelType: string 
    privateStreetName: string 
    privateStreetNumber: string 
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFGeographicPoint {

    spatialRef*: string 
    x*: string 
    y*: string 
    z: string 
}
GeographicAddressRefOrValue <|-- MEFGeographicPoint



class MEFSubUnit {

    subUnitNumber*: string 
    subUnitType*: string 
}



class RelatedContactInformation {

    emailAddress*: string 
    name*: string 
    number*: string 
    numberExtension: string 
    organization: string 
    role*: string 
}

RelatedContactInformation *--> FieldedAddress : postalAddress


enum MEFSiteType {

    public
    private
}
@enduml
