@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : GET {{baseUrl}}/geographicSite/{id}

Seller -> Seller : validate Request

alt success
    Buyer <-- Seller : 200 GeographicSite
else validation or internal problem
    Buyer <-- Seller: 4xx/5xx : error response
end
@enduml