@startuml

actor Seller

left to right direction
actor Buyer

rectangle {

Buyer --> (4. <u>Retrieve Service Site List</u>)
Buyer --> (5. Retrieve Service Site by Service Site Identifier)

Seller -[hidden]up-> (5. Retrieve Service Site by Service Site Identifier)
Seller -[hidden]up-> (4. <u>Retrieve Service Site List</u>)

}


@enduml
