@startuml

enum DataSizeUnit {

    BYTES
    KBYTES
    MBYTES
    GBYTES
    TBYTES
    PBYTES
    EBYTES
    ZBYTES
    YBYTES
}


enum IncidentStatusType {

    closed
    created
    inProgress
}
enum CimIncidentType {

    congestion
    failure
    plannedMaintenance
    policing
}



enum MEFBuyerSellerType {

    buyer
    seller
}

enum MEFObservedImpactType {

    degraded
    intermittent
    down
}


enum CimIncidentPriorityType {

    low
    medium
    high
    critical
}
enum CimIncidentSeverityType {

    minor
    moderate
    significant
    extensive
}
@enduml
