@startuml
skinparam {
    ClassBorderColor<<ProductSpecification>> FireBrick
}

set namespaceSeparator none

class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


class MEFProductRefOrValueOrder {

    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    productOffering: ProductOfferingRef
    productSpecification: ProductSpecificationRef
    productRelationship: ProductRelationshipWithGrouping

   
}

MEFProductRefOrValueOrder *--> MEFProductConfiguration : productConfiguration



class AccessElineOvc <<ProductSpecification>> {
    @type  urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- AccessElineOvc

class CarrierEthernetOperatorUni <<ProductSpecification>> {
    @type = urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v5.0.0:all
    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- CarrierEthernetOperatorUni




@enduml
