@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}
set namespaceSeparator none

class MEFProductRefOrValueOrder{

    id: string 
    href: string 
    place: RelatedPlaceRefOrValue
    productOffering: ProductOfferingRef
    productRelationship: ProductRelationshipWithGrouping
   
}


class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


MEFProductRefOrValueOrder *-->"0..1" MEFProductConfiguration : productConfiguration

class urn:mef:lso:spec:sonata:OperatorUNI:1.0.0:order <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:OperatorUNI:1.0.0:order"



class urn:mef:lso:spec:sonata:AccessElineOvc:1.0.0:order <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:AccessElineOvc:1.0.0:order"

@enduml
