@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class CancelProductOrder {

    cancellationDeniedReason: string
    cancellationReason: string
    cancellationReasonType: CancellationReasonType
    href: string
    id*: string
    state*: MEFChargeableTaskStateType
}

CancelProductOrder *--> MEFProductOrderChargeRef : charge
CancelProductOrder *-->"1" MEFProductOrderRef : productOrder
CancelProductOrder *-->"1..*" RelatedContactInformation : relatedContactInformation


class CancelProductOrder_Create {

    cancellationReason: string
    cancellationReasonType: CancellationReasonType
}

CancelProductOrder_Create *-->"1" MEFProductOrderRef : productOrder
CancelProductOrder_Create *-->"1..*" RelatedContactInformation : relatedContactInformation


class CancelProductOrder_Find {

    cancellationReasonType*: CancellationReasonType
    id*: string
    state*: MEFChargeableTaskStateType
}

CancelProductOrder_Find *-->"1" MEFProductOrderRef : productOrder

class ContactInformation {

    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
}

ContactInformation *--> FieldedAddressRepresentation : postalAddress


class Duration {

    amount*: integer
    units*: TimeUnit
}



class EventSubscription {

    callback*: string
    id*: string
    query: string
}



class EventSubscriptionInput {

    callback*: string
    query: string
}


class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit


class FormattedAddressRepresentation {

    formattedAddress*: string
    language: string
}



class GeographicAddressRef {

    href: string
    id*: string
    @type*: string
}



class GeographicAddress_Query {
    @type*: string
}

GeographicAddress_Query *-->"*" FieldedAddressRepresentation : fieldedAddressRepresentation
GeographicAddress_Query *-->"*" FormattedAddressRepresentation : formattedAddressRepresentation
GeographicAddress_Query *-->"*" GeographicPointRepresentation : geographicPointRepresentation
GeographicAddress_Query *-->"*" LabelRepresentation : labelRepresentation


class GeographicPointRepresentation {

    spatialRef*: string
    latitude*: string
    longitude*: string
    elevation: string
}



class GeographicSiteRef {

    href: string
    id*: string
    @type*: string
}



class LabelRepresentation {

    label*: string
    administrativeAuthority*: string
    language: string
}


class MEFBillingAccountRef {

    id*: string
}


class MEFCancelProductOrderRef {

    href: string
    id*: string
}

class MEFItemTerm {

    description: string
    endOfTermAction*: MEFEndOfTermAction
    name*: string
}

MEFItemTerm *-->"1" Duration : duration
MEFItemTerm *--> Duration : rollInterval


class MEFMilestone {

    date*: date-time
    name*: string
    note: string
}



class MEFModifyProductOrderItemRequestedDeliveryDate {

    creationDate*: date-time
    expediteIndicator: boolean
    href: string
    id*: string
    requestedCompletionDate: date-time
    state*: MEFChargeableTaskStateType
}

MEFModifyProductOrderItemRequestedDeliveryDate *-->"1" MEFProductOrderItemRef : productOrderItem


class MEFModifyProductOrderItemRequestedDeliveryDateRef {

    href: string
    id*: string
}



class MEFModifyProductOrderItemRequestedDeliveryDate_Create {

    expediteIndicator: boolean
    requestedCompletionDate: date-time
}

MEFModifyProductOrderItemRequestedDeliveryDate_Create *-->"1" MEFProductOrderItemRef : productOrderItem


class MEFOrderItemCoordinatedAction {

    coordinationDependency*: MEFOrderItemCoordinationDependencyType
    itemId*: string
}

MEFOrderItemCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class MEFProductConfiguration {

    @type*: string
}



class MEFProductOrderCharge {

    creationDate*: date-time
    href: string
    id*: string
    responseDueDate*: date-time
    state*: MEFProductOrderChargeStateType
}

MEFProductOrderCharge *--> MEFCancelProductOrderRef : cancelProductOrder
MEFProductOrderCharge *-->"1..*" MEFProductOrderChargeItem : chargeItem
MEFProductOrderCharge *--> MEFModifyProductOrderItemRequestedDeliveryDateRef : modifyProductOrderItemRequestedDeliveryDate
MEFProductOrderCharge *--> MEFProductOrderRef : productOrder
MEFProductOrderCharge *--> MEFProductOrderItemRef : productOrderItem


class MEFProductOrderCharge_Find {

    creationDate*: date-time
    id*: string
    responseDueDate*: date-time
    state*: MEFProductOrderChargeStateType
}

MEFProductOrderCharge_Find *--> MEFProductOrderRef : productOrder
MEFProductOrderCharge_Find *--> MEFProductOrderItemRef : productOrderItem


class MEFProductOrderChargeItem {

    acceptanceIndicator: MEFAcceptedRejectedType
    activityType*: MEFProductOrderChargeActivityType
    blocking*: boolean
    id*: string
    priceCategory*: MEFPriceCategory
    priceType*: MEFPriceType
    state*: MEFProductOrderChargeItemStateType
    unitOfMeasure: string
}

MEFProductOrderChargeItem *-->"*" Note : note
MEFProductOrderChargeItem *-->"1" Price : price
MEFProductOrderChargeItem *--> Duration : recurringChargePeriod


class MEFProductOrderChargeItem_Update {

    acceptanceIndicator*: MEFAcceptedRejectedType
    id*: string
}

MEFProductOrderChargeItem_Update *-->"*" Note : note


class MEFProductOrderChargeRef {

    href: string
    id*: string
}


class MEFProductOrderCharge_Update {

}

MEFProductOrderCharge_Update *-->"1..*" MEFProductOrderChargeItem_Update : chargeItem


class MEFProductOrderItemRef {

    productOrderHref: string
    productOrderId*: string
    productOrderItemId*: string
}



class MEFProductOrderItemStateChange {

    changeDate: date-time
    changeReason: string
    state: MEFProductOrderItemStateType
}


class MEFProductOrderItem_Common {

    action*: MEFProductActionType
    agreementName: string
    endCustomerName: string
    expediteIndicator: boolean
    id*: string
    relatedBuyerPON: string
    requestedCompletionDate*: date-time
    tspRestorationPriority: string
}

MEFProductOrderItem_Common *--> MEFBillingAccountRef : billingAccount
MEFProductOrderItem_Common *-->"*" MEFOrderItemCoordinatedAction : coordinatedAction
MEFProductOrderItem_Common *-->"*" Note : note
MEFProductOrderItem_Common *-->"1" MEFProductRefOrValueOrder : product
MEFProductOrderItem_Common *--> ProductOfferingQualificationItemRef : productOfferingQualificationItem
MEFProductOrderItem_Common *-->"*" OrderItemRelationship : productOrderItemRelationship
MEFProductOrderItem_Common *--> MEFQuoteItemRef : quoteItem
MEFProductOrderItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFProductOrderItem_Common *--> MEFItemTerm : requestedItemTerm


class MEFProductOrderItem_Create {

}
MEFProductOrderItem_Common <|-- MEFProductOrderItem_Create



class MEFProductOrderItem_Update {

    endCustomerName: string
    id*: string
    relatedBuyerPON: string
}

MEFProductOrderItem_Update *-->"*" Note : note
MEFProductOrderItem_Update *-->"*" RelatedContactInformation : relatedContactInformation


class MEFProductOrderRef {

    productOrderHref: string
    productOrderId*: string
}



class MEFProductOrderStateChange {

    changeDate: date-time
    changeReason: string
    state: MEFProductOrderStateType
}


class MEFProductRefOrValueOrder {

    href: string
    id: string
}

MEFProductRefOrValueOrder *-->"*" RelatedPlaceRefOrQueryWithSubUnit : place
MEFProductRefOrValueOrder *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValueOrder *--> ProductOfferingRef : productOffering
MEFProductRefOrValueOrder *-->"*" ProductRelationship : productRelationship


class MEFQuoteItemRef {

    id*: string
    quoteHref: string
    quoteId*: string
}



class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class Money {

    unit*: string
    value*: float
}



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}



class OrderItemRelationship {

    id*: string
    relationshipType*: string
}




class PlaceRefOrQuery {
    --
    discriminator:
    GeographicAddressRef
    GeographicSiteRef
    GeographicAddress_Query
}

PlaceRefOrQuery ..> GeographicAddressRef : """"
PlaceRefOrQuery ..> GeographicSiteRef : """"
PlaceRefOrQuery ..> GeographicAddress_Query : """"


class Price {

    taxRate: float
}

Price *-->"1" Money : dutyFreeAmount
Price *--> Money : taxIncludedAmount


class ProductOfferingQualificationItemRef {

    alternateProductOfferingProposalId: string
    id*: string
    productOfferingQualificationHref: string
    productOfferingQualificationId*: string
}



class ProductOfferingRef {

    href: string
    id*: string
}



class ProductOrder {

    cancellationDate: date-time
    cancellationReason: string
    completionDate: date-time
    href: string
    id*: string
    orderDate*: date-time
    state*: MEFProductOrderStateType
}
ProductOrder_Common <|-- ProductOrder

ProductOrder *-->"*" MEFProductOrderChargeRef : cancellationCharge
ProductOrder *-->"1..*" ProductOrderItem : productOrderItem
ProductOrder *-->"1..*" MEFProductOrderStateChange : stateChange


class ProductOrderItem {

    completionDate: date-time
    expectedCompletionDate: date-time
    expediteAcceptedIndicator: boolean
    state*: MEFProductOrderItemStateType
}
MEFProductOrderItem_Common <|-- ProductOrderItem

ProductOrderItem *-->"*" MEFProductOrderChargeRef : charge
ProductOrderItem *-->"0..1" MEFItemTerm : itemTerm
ProductOrderItem *-->"*" MEFMilestone : milestone
ProductOrderItem *-->"1..*" MEFProductOrderItemStateChange : stateChange
ProductOrderItem *-->"*" TerminationError : terminationError


class ProductOrder_Common {

    externalId: string
    projectId: string
}

ProductOrder_Common *-->"*" Note : note
ProductOrder_Common *-->"1..*" RelatedContactInformation : relatedContactInformation


class ProductOrder_Create {

}
ProductOrder_Common <|-- ProductOrder_Create

ProductOrder_Create *-->"1..*" MEFProductOrderItem_Create : productOrderItem


class ProductOrder_Find {

    cancellationDate: date-time
    completionDate: date-time
    externalId: string
    id*: string
    orderDate*: date-time
    projectId: string
    state*: MEFProductOrderStateType
}



class ProductOrder_Update {

    externalId: string
    projectId: string
}

ProductOrder_Update *-->"*" Note : note
ProductOrder_Update *-->"*" MEFProductOrderItem_Update : productOrderItem
ProductOrder_Update *-->"*" RelatedContactInformation : relatedContactInformation


class ProductRelationship {

    href: string
    id*: string
    relationshipType*: string
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress


class RelatedPlaceRefOrQueryWithSubUnit {

    role*: string
}

RelatedPlaceRefOrQueryWithSubUnit *-->"1" PlaceRefOrQuery : place
RelatedPlaceRefOrQueryWithSubUnit *-->"*" SubUnit : subUnit
RelatedPlaceRefOrQueryWithSubUnit *-->"*" ContactInformation : contact


class TerminationError {

    code: Error422Code
    propertyPath: string
    value: string
}


@enduml
