@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}


class Duration {

    amount*: integer
    units*: TimeUnit
}




class FieldedAddress {

    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    streetName*: string
    streetNr: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetNrSuffix: string
    streetSuffix: string
    streetType: string
}
RelatedPlaceRefOrValue <|-- FieldedAddress

FieldedAddress *--> GeographicSubAddress : geographicSubAddress


class FormattedAddress {

    addrLine1*: string
    addrLine2: string
    city*: string
    country*: string
    locality: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
}
RelatedPlaceRefOrValue <|-- FormattedAddress



class GeographicAddressLabel {

    externalReferenceId*: string
    externalReferenceType*: string
}
RelatedPlaceRefOrValue <|-- GeographicAddressLabel



class GeographicAddressRef {

    href: string
    id*: string
}
RelatedPlaceRefOrValue <|-- GeographicAddressRef



class GeographicSiteRef {

    href: string
    id*: string
}
RelatedPlaceRefOrValue <|-- GeographicSiteRef



class GeographicSubAddress {

    buildingName: string
    levelNumber: string
    levelType: string
    privateStreetName: string
    privateStreetNumber: string
}

GeographicSubAddress *-->"*" MEFSubUnit : subUnit


class MEFBillingAccountRef {

    id*: string
}


class MEFItemTerm {

    description: string
    endOfTermAction*: MEFEndOfTermAction
    name*: string
}

MEFItemTerm *--> Duration : duration*
MEFItemTerm *--> Duration : rollInterval


class MEFOrderItemCoordinatedAction {

    coordinationDependency*: MEFOrderItemCoordinationDependencyType
    itemId*: string
}

MEFOrderItemCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class MEFProductConfiguration {

    @type*: string
}


class MEFQuoteItemRef {

    id*: string
    quoteHref: string
    quoteId*: string
}



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}


class OrderItemRelationship {

    id*: string
    relationshipType*: string
}

class ProductOfferingRef {

    href: string
    id*: string
}


class MEFGeographicPoint {

    spatialRef*: string
    x*: string
    y*: string
    z: string
}
RelatedPlaceRefOrValue <|-- MEFGeographicPoint



class MEFProductOrderItem_Create {

}
MEFProductOrderItem_Common <|-- MEFProductOrderItem_Create


class MEFProductOrderItem_Common {

    action*: MEFProductActionType
    agreementName: string
    endCustomerName: string
    expediteIndicator: boolean
    id*: string
    relatedBuyerPON: string
    requestedCompletionDate: date-time
    tspRestorationPriority: string
}

MEFProductOrderItem_Common *--> MEFBillingAccountRef : billingAccount
MEFProductOrderItem_Common *-->"*" MEFOrderItemCoordinatedAction : coordinatedAction
MEFProductOrderItem_Common *-->"*" Note : note
MEFProductOrderItem_Common *--> MEFProductRefOrValueOrder : product
MEFProductOrderItem_Common *--> ProductOfferingQualificationItemRef : productOfferingQualificationItem
MEFProductOrderItem_Common *-->"*" OrderItemRelationship : productOrderItemRelationship
MEFProductOrderItem_Common *--> MEFQuoteItemRef : quoteItem
MEFProductOrderItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFProductOrderItem_Common *--> MEFItemTerm : requestedItemTerm


class MEFProductRefOrValueOrder {

    href: string
    id: string
}

MEFProductRefOrValueOrder *-->"*" RelatedPlaceRefOrValue : place
MEFProductRefOrValueOrder *--> MEFProductConfiguration : productConfiguration
MEFProductRefOrValueOrder *--> ProductOfferingRef : productOffering
MEFProductRefOrValueOrder *-->"*" ProductRelationship : productRelationship


class MEFSubUnit {

    subUnitNumber*: string
    subUnitType*: string
}



class ProductOrder_Common {

    externalId: string
    projectId: string
}

ProductOrder_Common *-->"*" Note : note
ProductOrder_Common *-->"1..*" RelatedContactInformation : relatedContactInformation


class ProductRelationship {

    href: string
    id*: string
    relationshipType*: string
}



class RelatedPlaceRefOrValue {

    @schemaLocation: uri
    @type*: string
    role*: string
}





class ProductOrder_Create {

}
ProductOrder_Common <|-- ProductOrder_Create

ProductOrder_Create *-->"1..*" MEFProductOrderItem_Create : productOrderItem


class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}


RelatedContactInformation *--> FieldedAddress : postalAddress

@enduml
