@startuml

' skinparam Linetype polyline
' skinparam Linetype ortho

hide empty description

state issues_detected <<choice>> 
note right of issues_detected : issues detected?

'''state rank'''
state "held.assessingCharge" as assessingCharge
state "pending.assessingModification" as assessingModification

inProgress -d[hidden]-> assessingCharge
assessingCharge -d[hidden]-> completed
assessingCharge -d[hidden]-> failed
assessingCharge -d[hidden]-> partial

''' diagram'''
[*] --> acknowledged 

acknowledged --> issues_detected

issues_detected -d-> inProgress : no
issues_detected -l-> rejected : yes

inProgress -l-> assessingModification
inProgress -d-> completed
inProgress -d-> failed
inProgress -d-> partial
inProgress --> assessingCharge
inProgress -r-> assessingCancellation
inProgress -r-> pendingCancellation

assessingModification -r-> inProgress

assessingCharge -l-> inProgress 

assessingCancellation -l-> inProgress
assessingCancellation -r-> pendingCancellation

pendingCancellation --> cancelled

completed --> [*]
failed --> [*]
partial --> [*]
cancelled --> [*]
rejected --> [*]

@enduml