@startuml

' skinparam Linetype polyline
' skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

state issues_detected <<choice>> 
note right of issues_detected : issues detected?

'''state rank'''
inProgress -d[hidden]-> held.assessingCharge
held.assessingCharge -d[hidden]-> completed
held.assessingCharge -d[hidden]-> failed
held.assessingCharge -d[hidden]-> partial

''' diagram'''
[*] --> acknowledged 

acknowledged --> issues_detected

issues_detected -d-> inProgress : no
issues_detected -l-> rejected : yes

inProgress -l-> pending.assessingModification
inProgress -d-> completed
inProgress -d-> failed
inProgress -d-> partial
inProgress --> held.assessingCharge
inProgress -r-> assessingCancellation
inProgress -r-> pendingCancellation

pending.assessingModification -r-> inProgress

held.assessingCharge -l-> inProgress 

assessingCancellation -l-> inProgress
assessingCancellation -r-> pendingCancellation

pendingCancellation --> cancelled

completed --> [*]
failed --> [*]
partial --> [*]
cancelled --> [*]
rejected --> [*]

@enduml