@startuml


class Duration {

    amount*: integer
    units*: TimeUnit
}


class MEFItemTerm {

    description: string
    endOfTermAction*: MEFEndOfTermAction
    name*: string
}

MEFItemTerm *--> Duration : duration*
MEFItemTerm *--> Duration : rollInterval


class MEFOrderItemCoordinatedAction {

    coordinationDependency*: MEFOrderItemCoordinationDependencyType
    itemId*: string
}

MEFOrderItemCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class MEFProductConfiguration {

    @type*: string
}


class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}

class MEFProductOrderItem_Create {

}
MEFProductOrderItem_Common <|-- MEFProductOrderItem_Create


class MEFProductOrderItem_Common {

    action*: MEFProductActionType
    agreementName: string
    billingAccount: MEFBillingAccountRef
    endCustomerName: string
    expediteIndicator: boolean
    id*: string
    productOfferingQualificationItem: ProductOfferingQualificationItemRef
    productOrderItemRelationship: OrderItemRelationship
    quoteItem: MEFQuoteItemRef
    relatedBuyerPON: string
    requestedCompletionDate: date-time
    tspRestorationPriority: string
}

MEFProductOrderItem_Common *-->"*" MEFOrderItemCoordinatedAction : coordinatedAction
MEFProductOrderItem_Common *-->"*" Note : note

MEFProductOrderItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFProductOrderItem_Common *--> MEFItemTerm : requestedItemTerm
MEFProductOrderItem_Common *--> MEFProductRefOrValueOrder : product

class MEFProductRefOrValueOrder {

    href: string
    id: string
    productOffering: ProductOfferingRef
    productRelationship: ProductRelationship
}

MEFProductRefOrValueOrder *-->"*" RelatedPlaceRefOrQueryWithSubUnit : place
MEFProductRefOrValueOrder *--> MEFProductConfiguration : productConfiguration


class ProductOrder_Common {

    externalId: string
    projectId: string
}

ProductOrder_Common *-->"*" Note : note
ProductOrder_Common *-->"1..*" RelatedContactInformation : relatedContactInformation

ProductOrder_Common *-r[hidden]-> MEFProductOrderItem_Common

class RelatedPlaceRefOrQueryWithSubUnit {

    role*: string
    place: PlaceRefOrQuery
    subUnit: SubUnit
    contact: ContactInformation
}



class ProductOrder_Create {

}
ProductOrder_Common <|-- ProductOrder_Create

ProductOrder_Create *-->"1..*" MEFProductOrderItem_Create : productOrderItem



class RelatedContactInformation {

    role*: string
    number*: string
    emailAddress*: string
    organization: string
    name*: string
    numberExtension: string
    postalAddress: FieldedAddressRepresentation
}


@enduml
