@startuml

class Duration {

    amount*: integer
    units*: TimeUnit
}



class MEFProductOrderItemStateChange {

    changeDate: date-time
    changeReason: string
    state: MEFProductOrderItemStateType
}



class MEFItemTerm {

    description: string
    endOfTermAction*: MEFEndOfTermAction
    name*: string
}

MEFItemTerm *--> Duration : duration*
MEFItemTerm *--> Duration : rollInterval


class MEFOrderItemCoordinatedAction {

    coordinationDependency*: MEFOrderItemCoordinationDependencyType
    itemId*: string
}

MEFOrderItemCoordinatedAction *-->"1" Duration : coordinatedActionDelay


class MEFProductConfiguration {

    @type*: string
}

class MEFProductOrderStateChange {

    changeDate: date-time
    changeReason: string
    state: MEFProductOrderStateType
}



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}




class ProductOrder {

    cancellationCharge: MEFProductOrderChargeRef
    cancellationDate: date-time
    cancellationReason: string
    completionDate: date-time
    href: string
    id*: string
    orderDate*: date-time
    state*: MEFProductOrderStateType
}
ProductOrder_Common <|-- ProductOrder

ProductOrder *-->"1..*" ProductOrderItem : productOrderItem
ProductOrder *-->"*" MEFProductOrderStateChange : stateChange


class TerminationError {

    code: Error422Code
    propertyPath: string
    value: string
}


class ProductOrderItem {

    charge: MEFProductOrderChargeRef
    completionDate: date-time
    expectedCompletionDate: date-time
    expediteAcceptedIndicator: boolean
    state*: MEFProductOrderItemStateType
}
MEFProductOrderItem_Common <|-- ProductOrderItem
ProductOrderItem *-->"*" MEFItemTerm : itemTerm
ProductOrderItem *-->"*" MEFMilestone : milestone
ProductOrderItem *-->"*" MEFProductOrderItemStateChange : stateChange
ProductOrderItem *-->"*" TerminationError : terminationError

class MEFMilestone {

    date*: date-time
    name*: string
    note: string
}


class MEFProductOrderItem_Common {

    action*: MEFProductActionType
    agreementName: string
    billingAccount: MEFBillingAccountRef
    endCustomerName: string
    expediteIndicator: boolean
    id*: string
    productOfferingQualificationItem: ProductOfferingQualificationItemRef
    productOrderItemRelationship: OrderItemRelationship
    quoteItem: MEFQuoteItemRef
    relatedBuyerPON: string
    requestedCompletionDate: date-time
    tspRestorationPriority: string
}

MEFProductOrderItem_Common *-->"*" MEFOrderItemCoordinatedAction : coordinatedAction
MEFProductOrderItem_Common *-->"*" Note : note

MEFProductOrderItem_Common *-->"*" RelatedContactInformation : relatedContactInformation
MEFProductOrderItem_Common *--> MEFItemTerm : requestedItemTerm
MEFProductOrderItem_Common *--> MEFProductRefOrValueOrder : product

class MEFProductRefOrValueOrder {

    href: string
    id: string
    productOffering: ProductOfferingRef
    productRelationship: ProductRelationship
}

MEFProductRefOrValueOrder *-->"*" RelatedPlaceRefOrQueryWithSubUnit : place
MEFProductRefOrValueOrder *--> MEFProductConfiguration : productConfiguration


class ProductOrder_Common {

    externalId: string
    projectId: string
}

ProductOrder_Common *-->"*" Note : note
ProductOrder_Common *-->"1..*" RelatedContactInformation : relatedContactInformation

ProductOrder_Common *-r[hidden]-> MEFProductOrderItem_Common

class RelatedPlaceRefOrQueryWithSubUnit {

    role*: string
    place: PlaceRefOrQuery
    subUnit: SubUnit
    contact: ContactInformation
}



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
    postalAddress: FieldedAddressRepresentation
}



@enduml
