@startuml

' skinparam Linetype polyline
' skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

''' diagram'''
[*] --> awaitingResponse

awaitingResponse --> completed
awaitingResponse --> withdrawnBySeller

completed --> [*]
withdrawnBySeller --> [*]

@enduml