@startuml

class MEFProductOrderChargeItem {

    acceptanceIndicator: MEFAcceptedRejectedType
    activityType*: MEFProductOrderChargeActivityType
    blocking*: boolean
    priceType*: MEFPriceType
    priceCategory*: MEFPriceCategory
    id*: string
    recurringChargePeriod: MEFChargePeriod
    state*: MEFProductOrderChargeItemStateType
    unitOfMeasure: string
}

MEFProductOrderChargeItem *-->"1" Price : price
MEFProductOrderChargeItem *-->"*" Note : note


class MEFCancelProductOrderRef {

    href: string
    id*: string
}



class MEFProductOrderCharge {

    creationDate*: date-time
    href: string
    id*: string
    responseDueDate*: date-time
    state*: MEFProductOrderChargeStateType
}

MEFProductOrderCharge *--> MEFCancelProductOrderRef : cancelProductOrder
MEFProductOrderCharge *-->"1..*" MEFProductOrderChargeItem : chargeItem
MEFProductOrderCharge *--> MEFModifyProductOrderItemRequestedDeliveryDateRef : modifyProductOrderItemRequestedDeliveryDate
MEFProductOrderCharge *--> MEFProductOrderRef : productOrder
MEFProductOrderCharge *--> MEFProductOrderItemRef : productOrderItem



MEFProductOrderChargeItem *--> Price : price


class MEFProductOrderChargeItem_Update {

    acceptanceIndicator*: MEFAcceptedRejectedType
    id*: string
}
MEFProductOrderChargeItem_Update *-->"*" Note : note


class MEFProductOrderCharge_Update {

}

MEFProductOrderCharge_Update *-->"1..*" MEFProductOrderChargeItem_Update : chargeItem

class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}


class MEFProductOrderItemRef {

    productOrderHref: string
    productOrderId*: string
    productOrderItemId*: string
}


class MEFModifyProductOrderItemRequestedDeliveryDateRef {

    href: string
    id*: string
}


class Price {

    taxRate: float
}

Price *--> Money : dutyFreeAmount
Price *--> Money : taxIncludedAmount


class Money {

    unit: string
    value: float
}



@enduml
