@startuml

'skinparam Linetype polyline
' skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

'''decisions'''
state business_validation_pass <<choice>> 
note right of business_validation_pass : business validation pass?

state charges_associated <<choice>> 
note right of charges_associated : charges associated?

state blocking_charges_accepted <<choice>> 
note right of blocking_charges_accepted : blocking charges accepted?

''' diagram'''
[*] --> acknowledged 

acknowledged --> business_validation_pass

business_validation_pass --> charges_associated : yes
business_validation_pass --> rejected : no

charges_associated --> done : no
charges_associated --> inProgress.assessingCharge : yes

inProgress.assessingCharge --> blocking_charges_accepted

blocking_charges_accepted --> done : yes
blocking_charges_accepted --> done.declined : no

done --> [*]
done.declined --> [*]
rejected --> [*]

@enduml