@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/productOrder (ProductOrder_Create)

Seller -> Seller : validate Request
Seller -> Seller : assign id
alt successful inquiry
    Buyer <-- Seller : 201 ProductOrder with {{id}} in acknowledged state
else validation or internal problem
    Buyer <-- Seller: 4xx/5xx : error response
end
@enduml