@startuml

' skinparam Linetype polyline
' skinparam Linetype ortho

hide empty description

''' diagram'''
[*] --> awaitingResponse

awaitingResponse --> completed
awaitingResponse --> withdrawnBySeller
awaitingResponse --> timeout

completed --> [*]
withdrawnBySeller --> [*]
timeout --> [*]
@enduml