@startuml

class CancelProductOrderStateChangeEvent {

    eventType*: string
}
Event <|-- CancelProductOrderStateChangeEvent

CancelProductOrderStateChangeEvent *-->"1" CancelProductOrderStateChangeEventPayload : event


class CancelProductOrderStateChangeEventPayload {

    id*: string
    href: string
    state*: MEFChargeableTaskStateType
}



class ChargeCreateEvent {

    eventType*: string
}
Event <|-- ChargeCreateEvent

ChargeCreateEvent *-->"1" ChargeEventPayload : event


class ChargeEventPayload {

    id*: string
    href: string
}



class ChargeStateChangeEvent {

    eventType*: string
}
Event <|-- ChargeStateChangeEvent

ChargeStateChangeEvent *-->"1" ChargeStateChangeEventPayload : event


class ChargeStateChangeEventPayload {

    id*: string
    href: string
    state*: MEFProductOrderChargeStateType
}



class ChargeTimeoutEvent {

    eventType*: string
}
Event <|-- ChargeTimeoutEvent

ChargeTimeoutEvent *-->"1" ChargeEventPayload : event


class Event {

    eventId*: string
    eventTime*: date-time
    eventType*: string
    event*: object
}


class ModifyProductOrderItemRequestedDeliveryDateStateChangeEvent {

    eventType*: string
}
Event <|-- ModifyProductOrderItemRequestedDeliveryDateStateChangeEvent

ModifyProductOrderItemRequestedDeliveryDateStateChangeEvent *-->"1" ModifyProductOrderItemRequestedDeliveryDateStateChangeEventPayload : event


class ModifyProductOrderItemRequestedDeliveryDateStateChangeEventPayload {

    id*: string
    href: string
    state*: MEFChargeableTaskStateType
}



class ProductOrderItemExpectedCompletionDateSetEvent {

    eventType*: string
}
Event <|-- ProductOrderItemExpectedCompletionDateSetEvent

ProductOrderItemExpectedCompletionDateSetEvent *-->"1" ProductOrderItemExpectedCompletionDateSetEventPayload : event


class ProductOrderItemExpectedCompletionDateSetEventPayload {

    id*: string
    href: string
    orderItemId*: string
}



class ProductOrderItemStateChangeEvent {

    eventType*: string
}
Event <|-- ProductOrderItemStateChangeEvent

ProductOrderItemStateChangeEvent *-->"1" ProductOrderItemStateChangeEventPayload : event


class ProductOrderItemStateChangeEventPayload {

    id*: string
    href: string
    orderItemId*: string
    state*: MEFProductOrderItemStateType
}



class ProductOrderStateChangeEvent {

    eventType*: string
}
Event <|-- ProductOrderStateChangeEvent

ProductOrderStateChangeEvent *-->"1" ProductOrderStateChangeEventPayload : event


class ProductOrderStateChangeEventPayload {

    id*: string
    href: string
    state*: MEFProductOrderStateType
}



class ProductSpecificProductOrderItemMilestoneEvent {

    eventType*: string
}
Event <|-- ProductSpecificProductOrderItemMilestoneEvent

ProductSpecificProductOrderItemMilestoneEvent *-->"1" ProductSpecificProductOrderItemMilestoneEventPayload : event


class ProductSpecificProductOrderItemMilestoneEventPayload {

    id*: string
    href: string
    orderItemId*: string
    milestoneName*: string
}



@enduml
