@startuml

'skinparam Linetype polyline
' skinparam Linetype ortho

hide empty description

''' diagram'''
[*] --> awaitingResponse

awaitingResponse --> acceptedByBuyer
awaitingResponse --> declinedByBuyer
awaitingResponse --> withdrawnBySeller

acceptedByBuyer --> [*]
declinedByBuyer --> [*]
withdrawnBySeller --> [*]

@enduml