@startuml

hide footbox

participant Buyer
entity "Cancel Product Order" as CPO
entity "Product Order" as PO

autonumber
activate PO
note over PO: Product Order in state: inProgress
Buyer -> CPO : POST cancelProductOrder request
activate CPO
CPO -> CPO: validation
CPO -> CPO: assign id
CPO -> CPO: state: acknowledged
CPO --> Buyer: POST cancelProductOrder response

CPO -> PO: (causes state change)
PO -> PO: state: assessingCancellation
PO -> Buyer: POST productOrderItemStateChangeEvent

CPO -> CPO: state: assessingCharge
CPO -> Buyer: POST cancelProductOrderStateChangeEvent

...
note over CPO, PO: The Seller finalizes Cancel request processing without identifying additional charges

CPO -> CPO: state: completed
CPO -> Buyer: POST cancelProductOrderStateChangeEvent
CPO -> PO: (causes state change)
deactivate CPO

PO -> PO: state: cancelling
PO -> Buyer: POST productOrderStateChangeEvent
PO -> PO: state: cancelled
PO -> Buyer: POST productOrderStateChangeEvent
deactivate PO

@enduml