@startuml



class Note {

    author*: string
    date*: date-time
    id*: string
    source*: MEFBuyerSellerType
    text*: string
}





class MEFProductOrderItem_Update {

    endCustomerName: string
    id*: string
    relatedBuyerPON: string
}

MEFProductOrderItem_Update *-->"*" Note : note
MEFProductOrderItem_Update *-->"*" RelatedContactInformation : relatedContactInformation



class SubUnit {

    subUnitNumber*: string
    subUnitType*: string
}


class ProductOrder_Update {

    externalId: string
    projectId: string
}

ProductOrder_Update *-->"*" Note : note
ProductOrder_Update *-->"*" MEFProductOrderItem_Update : productOrderItem
ProductOrder_Update *-->"*" RelatedContactInformation : relatedContactInformation



class RelatedContactInformation {

    emailAddress*: string
    name*: string
    number*: string
    numberExtension: string
    organization: string
    role*: string
}

RelatedContactInformation *--> FieldedAddressRepresentation : postalAddress
class FieldedAddressRepresentation {

    streetNr: string
    streetNrSuffix: string
    streetNrLast: string
    streetNrLastSuffix: string
    streetPreDirection: string
    streetName: string
    streetType: string
    streetPostDirection: string
    poBox: string
    locality: string
    city: string
    postcode: string
    postcodeExtension: string
    stateOrProvince: string
    countryCode: string
    buildingName: string
    privateStreetNumber: string
    privateStreetName: string
    language: string
}

FieldedAddressRepresentation *-->"*" SubUnit : subUnit


@enduml
