@startuml

'skinparam Linetype polyline
' skinparam Linetype ortho

hide empty description

state "inProgress.assessingCharge" as assessingCharge
state "done.declined" as declined

'''decisions'''
state business_validation_pass <<choice>> 
note right of business_validation_pass : business validation pass?

state charges_associated <<choice>> 
note right of charges_associated : charges associated?

state blocking_charges_accepted <<choice>> 
note right of blocking_charges_accepted : blocking charges accepted?

''' diagram'''
[*] --> acknowledged 

acknowledged --> business_validation_pass

business_validation_pass --> charges_associated : yes
business_validation_pass --> rejected : no

charges_associated --> done : no
charges_associated --> assessingCharge : yes

assessingCharge --> blocking_charges_accepted

blocking_charges_accepted --> done : yes
blocking_charges_accepted --> declined : no

done --> [*]
declined --> [*]
rejected --> [*]

@enduml