@startuml

'skinparam Linetype polyline
' skinparam Linetype ortho
skinparam state {
    BackgroundColor White
    BorderColor Black
}
hide empty description

''' diagram'''
[*] --> awaitingResponse

awaitingResponse --> acceptedByBuyer
awaitingResponse --> declinedByBuyer
awaitingResponse --> withdrawnBySeller

acceptedByBuyer --> [*]
declinedByBuyer --> [*]
withdrawnBySeller --> [*]

@enduml