@startjson
#highlight "productOrderItem" 
#highlight "productOrderItem" / "0" 
#highlight "productOrderItem" / "0" / "action"
#highlight "productOrderItem" / "0" / "product" / "id"
#highlight "productOrderItem" / "0" / "product"
#highlight "productOrderItem" / "0" / "product" / "productRelationship" 
#highlight "productOrderItem" / "0" / "product" / "productRelationship" / "0" 
#highlight "productOrderItem" / "0" / "product" / "productRelationship" / "0" / "id" 

{
  "externalId": "BuyerOrder-00007",
  "projectId": "BuyerProject3",
  "relatedContactInformation": [
  {
    "emailAddress": "john.example@buyer.mplify.com",
    "name": "John Example",
    "number": "12-345-6789",
    "numberExtension": "1234",
    "role": "productOrderContact",
    "organization": "Buyer Co."
  }
  ],
  "productOrderItem": [
  {
    "action": "modify",
    "id": "item-00001",
    "requestedItemTerm": {
      "duration": {
        "amount": 12,
        "units": "months"
      }
      ,
      "endOfTermAction": "autoRenew",
      "name": "Yearly subscription"
    }
    ,
    "relatedContactInformation": "<<skipped>>",
    "billingAccount": "<<skipped>>",
    "agreementName": "Buyer-Seller General Agreement 03/2023",
    "requestedCompletionDate": "2026-06-28T22:00:00Z",
    "product": {
      "id": "InternetAccess-BroadbandDedicatedWithoutRouter-00001",
      "productOffering": {
        "id": "BroadbandDedicatedWithoutRouterOffering-0001"
      }
      ,
      "productRelationship": [
      {
        "relationshipType": "CONNECTS_TO_SAI",
        "id": "SAI_ID-678"
      }
      ],
      "productConfiguration": "<<skipped>>"
    }
  }
  ]
}
@endjson