@startjson
#highlight "quoteItem"
#highlight "quoteItem" / "0"
#highlight "quoteItem" / "0" / "action"
#highlight "quoteItem" / "0" / "product"
#highlight "quoteItem" / "0" / "product" / "id"
{
  "requestedQuoteCompletionDate": "2026-06-12T22:00:00Z",
  "externalId": "BuyerQuote-00002",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProject4",
  "instantSyncQuote": true,
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.mplify.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "role": "buyerContactInformation",
      "organization": "Buyer Co."
    }
  ],
  "quoteItem": [
    {
      "action": "delete",
      "id": "item-00001",
      "product": {
        "id": "InternetAccess-BroadbandDedicatedWithRouter-00001"
      }
    }
  ]
}
@endjson