@startjson
#highlight "productOfferingQualificationItem"
#highlight "productOfferingQualificationItem" / "0" 
#highlight "productOfferingQualificationItem" / "0" / "product" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" / "0"
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" / "0" / "place"
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" / "0" / "place" / "@type"
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" / "0" / "place" / "id"
#highlight "productOfferingQualificationItem" / "0" / "product" / "place" / "0" / "role"

#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" 
#highlight "productOfferingQualificationItem" / "0" / "product" / "productConfiguration" / "@type"


{
  "externalId": "BuyerPoq-00001",
  "instantSyncQualification": false,
  "provideAlternative": true,
  "projectId": "BuyerProject1",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.mplify.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "role": "buyerContactInformation",
      "organization": "Buyer Co."
    }
  ],
  "productOfferingQualificationItem": [
    {
      "action": "add",
      "id": "item-00001",
      "product": {
        "productOffering": {
          "id": "BroadbandBasicOffering-0001"
        },
        "place": [
          {
            "place": {
              "@type": "GeographicAddressRef",
              "id": "Budapest-id-1"
            },
            "role": "INSTALL_LOCATION",
            "contact": [
              {
                "emailAddress": "LocationContact@buyer.mplify.com",
                "name": "Location Contact",
                "number": "+12-345-678-90",
                "organization": "Buyer Co."
              }
            ]
          }
        ],
        "productConfiguration": {
          "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
          "<<skipped>>": "<<skipped>>"
        }
      }
    }
  ]
}
@endjson