@startjson
#highlight "variant"
#highlight "bandwidth" / "downstream" /  "irValue"
#highlight "bandwidth" / "upstream" /  "irValue"
{
  "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
  "variant": "BROADBAND_BASIC",
  "deliveryMechanism": "DEMARCATION_ONLY",
  "serviceAccessInterfaceType": {
    "physicalInterface": [
    {
      "physicalLayer": "1000BASE-T",
      "connectorType": "RJ45"
    }
    ],
    "resiliency": "NONE"
  }
  ,
  "features": {},
  "bandwidth": {
    "downstream": {
      "irValue": 100,
      "irUnits": "MBPS"
    }
    ,
    "upstream": {
      "irValue": 20,
      "irUnits": "MBPS"
    }
  }
  ,
  "billingModel": {
    "billingModelType": "FLAT",
    "billingModelPlanName": "Broadband Basic Monthly"
  }
}
@endjson