@startjson

#highlight "quoteItem" 
#highlight "quoteItem" / "0" 
#highlight "quoteItem" / "0" / "id" 
#highlight "quoteItem" / "0" / "requestedQuoteItemTerm" 
#highlight "quoteItem" / "0" / "requestedQuoteItemTerm" / "duration"
#highlight "quoteItem" / "0" / "requestedQuoteItemTerm" / "endOfTermAction"
#highlight "quoteItem" / "0" / "requestedQuoteItemTerm" / "name"



{
  "requestedQuoteCompletionDate": "2026-06-12T22:00:00Z",
  "externalId": "BuyerQuote-00001",
  "buyerRequestedQuoteLevel": "firm",
  "projectId": "BuyerProject1",
  "instantSyncQuote": false,
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.mplify.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "role": "buyerContactInformation",
      "organization": "Buyer Co."
    }
  ],
  "quoteItem": [
    {
      "action": "add",
      "id": "item-00001",
      "requestedQuoteItemTerm": {
        "duration": {
          "amount": 12,
          "units": "months"
        },
        "endOfTermAction": "autoRenew",
        "name": "Yearly Subscription"
      },
      "relatedContactInformation": [
        {
          "emailAddress": "john.example@buyer.mplify.com",
          "name": "John Example",
          "number": "12-345-6789",
          "numberExtension": "1234",
          "role": "buyerAdministrativeContact",
          "organization": "Buyer Co."
        }
      ],
      "product": "<<skipped>>"
    }
  ]
}
@endjson