@startjson
#highlight "productOffering"

#highlight "productConfiguration"
#highlight "productConfiguration" / "variant"

#highlight "productConfiguration" / "demarcationPoint"
#highlight "productConfiguration" / "demarcationPoint" / "0"
#highlight "productConfiguration" / "demarcationPoint" / "0" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "0" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "1"
#highlight "productConfiguration" / "demarcationPoint" / "1" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "1" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "2"
#highlight "productConfiguration" / "demarcationPoint" / "2" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "2" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "3"
#highlight "productConfiguration" / "demarcationPoint" / "3" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "3" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "4"
#highlight "productConfiguration" / "demarcationPoint" / "4" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "4" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "5"
#highlight "productConfiguration" / "demarcationPoint" / "5" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "5" / "subUnitNumber"
#highlight "productConfiguration" / "demarcationPoint" / "6"
#highlight "productConfiguration" / "demarcationPoint" / "6" / "subUnitType"
#highlight "productConfiguration" / "demarcationPoint" / "6" / "subUnitNumber"

#highlight "productConfiguration" / "deliveryMechanism"
#highlight "productConfiguration" / "features"
#highlight "productConfiguration" / "features" / "assistance"
#highlight "productConfiguration" / "features" / "assistance" / "isSupported"
#highlight "productConfiguration" / "features" / "assistance" / "isEnabled"
#highlight "productConfiguration" / "features" / "assistance" / "assistanceLevel"
#highlight "productConfiguration" / "features" / "assistance" / "simpleRequestsPerMonth"
#highlight "productConfiguration" / "features" / "assistance" / "complexRequestsPerMonth" 
#highlight "productConfiguration" / "features" / "dns"
#highlight "productConfiguration" / "features" / "dns" / "isSupported"
#highlight "productConfiguration" / "features" / "dns" / "isEnabled"
#highlight "productConfiguration" / "features" / "dns" / "searchDomain"
#highlight "productConfiguration" / "features" / "dns" / "searchDomain" / "0"
#highlight "productConfiguration" / "features" / "dns" / "searchDomain" / "1"

#highlight "productConfiguration" / "features" / "monitoring"
#highlight "productConfiguration" / "features" / "monitoring" / "isSupported"
#highlight "productConfiguration" / "features" / "monitoring" / "isEnabled"
#highlight "productConfiguration" / "features" / "monitoring" / "monitoringType"
#highlight "productConfiguration" / "features" / "performanceReporting"
#highlight "productConfiguration" / "features" / "performanceReporting" / "isSupported"
#highlight "productConfiguration" / "features" / "performanceReporting" / "isEnabled"

#highlight "productConfiguration" / "guaranteedBandwidth"
#highlight "productConfiguration" / "guaranteedBandwidth" / "downstream"
#highlight "productConfiguration" / "guaranteedBandwidth" / "downstream" / "irValue"
#highlight "productConfiguration" / "guaranteedBandwidth" / "downstream" / "irUnits"
#highlight "productConfiguration" / "guaranteedBandwidth" / "upstream" 
#highlight "productConfiguration" / "guaranteedBandwidth" / "upstream" / "irValue"
#highlight "productConfiguration" / "guaranteedBandwidth" / "upstream" / "irUnits"

#highlight "productConfiguration" / "localNetworkAddresses"
#highlight "productConfiguration" / "localNetworkAddresses" / "lanAddressBlock" 
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStatus"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStart" 
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpEnd"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList"  
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0" / "staticMACAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0" / "staticIpAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1" / "staticMACAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1" / "staticIpAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "natStatus"
#highlight "productConfiguration" / "localNetworkAddresses" / "natAddress"
#highlight "productConfiguration" / "providerIndependentIpAddresses"  
#highlight "productConfiguration" / "ipAddressType"
#highlight "productConfiguration" / "publicAddressesPrefixLength" 
#highlight "productConfiguration" / "publicAddressesPrefixLength" / "ipv4"
#highlight "productConfiguration" / "publicAddressesPrefixLength" / "ipv6"  




{
  "productOffering": {
    "id": "BroadbandAdvancedOffering-0001"
  }
  ,
  "place": [
  {
    "place": {
      "@type": "GeographicAddressRef",
      "id": "Budapest-id-1"
    }
    ,
    "role": "INSTALL_LOCATION",
    "contact": [
    {
      "emailAddress": "LocationContact@buyer.mplify.com",
      "name": "Location Contact",
      "number": "+12-345-678-90",
      "organization": "Buyer Co."
    }
    ]
  }
  ],
  "productConfiguration": {
    "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
    "variant": "BROADBAND_ADVANCED",
    "demarcationPoint": [
    {
      "subUnitType": "FLOOR",
      "subUnitNumber": "3"
    }
    ,
    {
      "subUnitType": "ROOM",
      "subUnitNumber": "305"
    }
    ,
    {
      "subUnitType": "RACK",
      "subUnitNumber": "7"
    }
    ,
    {
      "subUnitType": "CHASSIS",
      "subUnitNumber": "2"
    }
    ,
    {
      "subUnitType": "SLOT",
      "subUnitNumber": "5"
    }
    ,
    {
      "subUnitType": "PORT",
      "subUnitNumber": "12"
    }
    ],
    "deliveryMechanism": "PHYSICAL_ROUTER",
    "serviceAccessInterfaceType": {
      "physicalInterface": [
      {
        "physicalLayer": "1000BASE-T",
        "connectorType": "RJ45"
      }
      ],
      "resiliency": "NONE"
    }
    ,
    "features": {
      "assistance": {
        "isSupported": true,
        "isEnabled": true,
        "assistanceLevel": "CO_MANAGED",
        "simpleRequestsPerMonth": 5,
        "complexRequestsPerMonth": 2
      }
      ,
      "dns": {
        "isSupported": true,
        "isEnabled": true,
        "searchDomain": [
        "example.com",
        "local.example.com"
        ]
      }
      ,
      "monitoring": {
        "isSupported": true,
        "isEnabled": true,
        "monitoringType": "REACTIVE"
      }
      ,
      "performanceReporting": {
        "isSupported": true,
        "isEnabled": true
      }
    }
    ,
    "bandwidth": {
      "downstream": {
        "irValue": 500,
        "irUnits": "MBPS"
      }
      ,
      "upstream": {
        "irValue": 100,
        "irUnits": "MBPS"
      }
    }
    ,
    "guaranteedBandwidth": {
      "downstream": {
        "irValue": 100,
        "irUnits": "MBPS"
      }
      ,
      "upstream": {
        "irValue": 20,
        "irUnits": "MBPS"
      }
    }
    ,
    "billingModel": {
      "billingModelType": "FLAT",
      "billingModelPlanName": "Broadband Advanced Premium"
    }
    ,
    "localNetworkAddresses": {
      "lanAddressBlock": "192.168.1.0/24",
      "dhcpStatus": "ENABLED",
      "dhcpStart": "192.168.1.100",
      "dhcpEnd": "192.168.1.200",
      "dhcpStaticList": [
      {
        "staticMACAddress": "00:1A:2B:3C:4D:5E",
        "staticIpAddress": "192.168.1.10"
      }
      ,
      {
        "staticMACAddress": "00:1A:2B:3C:4D:5F",
        "staticIpAddress": "192.168.1.11"
      }
      ],
      "natStatus": "ENABLED",
      "natAddress": "203.0.113.45"
    }
    ,
    "providerIndependentIpAddresses": "DISABLED",
    "ipAddressType": "DYNAMIC",
    "publicAddressesPrefixLength": {
      "ipv4": "/32",
      "ipv6": "NONE"
    }
  }
}


@endjson