@startjson
#highlight "productConfiguration" / "vlan"
#highlight "productConfiguration" / "features"
#highlight "productConfiguration" / "features" / "ddosMitigation"
#highlight "productConfiguration" / "features" / "ddosMitigation" / "isSupported"
#highlight "productConfiguration" / "features" / "ddosMitigation" / "isEnabled"
#highlight "productRelationship" 
#highlight "productRelationship" / "0"
#highlight "productRelationship" / "0" / "relationshipType"
#highlight "productRelationship" / "0" / "id" 
#highlight "productConfiguration" / "transitAddresses"
#highlight "productConfiguration" / "transitAddresses" / "requestedIpv4TransitAddressPrefixLength"
#highlight "productConfiguration" / "transitAddresses" / "requestedIpv6TransitAddressPrefixLength"
#highlight "productConfiguration" / "transitAddresses" / "serviceProviderIpv4TransitAddress"
#highlight "productConfiguration" / "transitAddresses" / "serviceProviderIpv6TransitAddress"


{

  "productOffering": {
    "id": "BroadbandDedicatedWithoutRouterOffering-0001"
  }
  ,
  "productRelationship": [
  {
    "relationshipType": "CONNECTS_TO_SAI",
    "id": "SAI_ID-001"
  }
  ],
  "productConfiguration": {
    "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
    "variant": "DEDICATED_WITHOUT_ROUTER",
    "deliveryMechanism": "DEMARCATION_ONLY",
    "vlan": 100,
    "features": {
      "assistance": {
        "isSupported": true,
        "isEnabled": true,
        "assistanceLevel": "SELF_MANAGED",
        "simpleRequestsPerMonth": 10,
        "complexRequestsPerMonth": 5
      }
      ,
      "ddosMitigation": {
        "isSupported": true,
        "isEnabled": true
      }
      ,
      "dns": {
        "isSupported": true,
        "isEnabled": true,
        "searchDomain": [
        "enterprise.example.com"
        ]
      }
      ,
      "monitoring": {
        "isSupported": true,
        "isEnabled": true,
        "monitoringType": "PROACTIVE"
      }
      ,
      "performanceReporting": {
        "isSupported": true,
        "isEnabled": true
      }
    }
    ,
    "bandwidth": {
      "downstream": {
        "irValue": 500,
        "irUnits": "MBPS"
      }
      ,
      "upstream": {
        "irValue": 500,
        "irUnits": "MBPS"
      }
    }
    ,
    "guaranteedBandwidth": {
      "downstream": {
        "irValue": 200,
        "irUnits": "MBPS"
      }
      ,
      "upstream": {
        "irValue": 200,
        "irUnits": "MBPS"
      }
    }
    ,
    "billingModel": {
      "billingModelType": "BURSTABLE_PERCENTILE",
      "billingModelPlanName": "DIA 95th Percentile Enterprise"
    }
    ,
    "providerIndependentIpAddresses": "DISABLED",
    "ipAddressType": "STATIC",
    "publicAddressesPrefixLength": {
      "ipv4": "/28",
      "ipv6": "/120"
    }
    ,
    "transitAddresses": {
      "requestedIpv4TransitAddressPrefixLength": "/30",
      "requestedIpv6TransitAddressPrefixLength": "/124",
      "serviceProviderIpv4TransitAddress": "198.51.100.3/30",
      "serviceProviderIpv6TransitAddress": "2001:db8:abcd:0012::0001/124"
    }
  }
}


@endjson