@startjson
#highlight "cloudPrioritization"
#highlight "cloudPrioritization" / "isSupported"
#highlight "cloudPrioritization" / "isEnabled"
#highlight "cloudPrioritization" / "cloudServiceProvider"
#highlight "cloudPrioritization" / "cloudServiceProvider" / "0"
#highlight "cloudPrioritization" / "cloudServiceProvider" / "1" 
#highlight "cloudPrioritization" / "cloudServiceProvider" / "2"

#highlight "dedicatedFirewall"
#highlight "dedicatedFirewall" / "isSupported"
#highlight "dedicatedFirewall" / "isEnabled"
#highlight "dedicatedFirewall" / "firewallCapability"
#highlight "facilityDiversity"
#highlight "facilityDiversity" / "isSupported"
#highlight "facilityDiversity" / "isEnabled"
#highlight "layer3Resiliency"
#highlight "layer3Resiliency" / "isSupported"
#highlight "layer3Resiliency" / "isEnabled"
#highlight "layer3Resiliency" / "layer3Resiliency"
#highlight "mobileBackup"
#highlight "mobileBackup" / "isSupported"
#highlight "mobileBackup" / "isEnabled"
#highlight "mobileBackup" / "minimumExpectedBandwidth"
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "downstream"
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "downstream" / "irValue"
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "downstream" / "irUnits"
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "upstream"
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "upstream" / "irValue"
		   
#highlight "mobileBackup" / "minimumExpectedBandwidth" / "upstream" / "irUnits"
#highlight "routing"
#highlight "routing" / "isSupported"
#highlight "routing" / "isEnabled"
#highlight "routing" / "routingType"
#highlight "routing" / "bgp"
#highlight "routing" / "bgp" / "subscriberAsNumber"
#highlight "routing" / "bgp" / "connectionAddressFamily"
#highlight "routing" / "bgp" / "peeringAddresses"
#highlight "routing" / "bgp" / "peeringAddresses" / "peeringAddressType"
#highlight "routing" / "bgp" / "authentication"
#highlight "routing" / "bgp" / "authentication" / "0"
#highlight "routing" / "bgp" / "bgpCommunityList"
#highlight "routing" / "bgp" / "bgpCommunityList" / "0"
#highlight "routing" / "bgp" / "bgpCommunityList" / "0" / "asNumber"
#highlight "routing" / "bgp" / "bgpCommunityList" / "0" / "communityValue"
#highlight "routing" / "bgp" / "holdTime"
#highlight "routing" / "bgp" / "asOverride"
#highlight "snmpRead"
#highlight "snmpRead" / "isSupported"
#highlight "snmpRead" / "isEnabled"


{
  
    "assistance": {
      "isSupported": true,
      "isEnabled": true,
      "assistanceLevel": "FULLY_MANAGED",
      "simpleRequestsPerMonth": 20,
      "complexRequestsPerMonth": 10
    }
    ,
    "cloudPrioritization": {
      "isSupported": true,
      "isEnabled": true,
      "cloudServiceProvider": [
      "Microsoft Azure",
      "Amazon Web Services",
      "Google Cloud Platform"
      ]
    }
    ,
    "ddosMitigation": {
      "isSupported": true,
      "isEnabled": true
    }
    ,
    "dedicatedFirewall": {
      "isSupported": true,
      "isEnabled": true,
      "firewallCapability": "ADVANCED"
    }
    ,
    "dns": {
      "isSupported": true,
      "isEnabled": true,
      "searchDomain": [
      "corp.enterprise.com",
      "internal.enterprise.com"
      ]
    }
    ,
    "facilityDiversity": {
      "isSupported": true,
      "isEnabled": true
    }
    ,
    "layer3Resiliency": {
      "isSupported": true,
      "isEnabled": true,
      "layer3Resiliency": "WIRELESS_BACKUP"
    }
    ,
    "mobileBackup": {
      "isSupported": true,
      "isEnabled": true,
      "minimumExpectedBandwidth": {
        "downstream": {
          "irValue": 100,
          "irUnits": "MBPS"
        }
        ,
        "upstream": {
          "irValue": 50,
          "irUnits": "MBPS"
        }
      }
    }
    ,
    "monitoring": {
      "isSupported": true,
      "isEnabled": true,
      "monitoringType": "PROACTIVE"
    }
    ,
    "performanceReporting": {
      "isSupported": true,
      "isEnabled": true
    }
    ,
    "routing": {
      "isSupported": true,
      "isEnabled": true,
      "routingType": "BGP",
      "bgp": {
        "subscriberAsNumber": 65001,
        "connectionAddressFamily": "IPV4",
        "peeringAddresses": {
          "peeringAddressType": "CONNECTION_ADDRESSES"
        }
        ,
        "authentication": [
        "bgp-secret-password"
        ],
        "bgpCommunityList": [
        {
          "asNumber": 65001,
          "communityValue": 100
        }
        ],
        "holdTime": 90,
        "asOverride": "DISABLED"
      }
    }
    ,
    "snmpRead": {
      "isSupported": true,
      "isEnabled": true
    }
  }

@endjson