@startjson
#highlight "productConfiguration" / "features"

#highlight "productRelationship"
#highlight "productRelationship" / "1"
#highlight "productRelationship" / "1" / "relationshipType"
#highlight "productRelationship" / "1" / "id"
#highlight "productConfiguration" / "localNetworkAddresses"
#highlight "productConfiguration" / "localNetworkAddresses" / "lanAddressBlock"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStatus"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStart"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpEnd"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0" / "staticMACAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "0" / "staticIpAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1" / "staticMACAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "1" / "staticIpAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "2"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "2" / "staticMACAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "dhcpStaticList" / "2" / "staticIpAddress"
#highlight "productConfiguration" / "localNetworkAddresses" / "natStatus"
#highlight "productConfiguration" / "localNetworkAddresses" / "natAddress"
#highlight "productConfiguration" / "autonomousSystemNumber"
#highlight "productConfiguration" / "publicAddressBlock"



{

  "productOffering": {
    "id": "BroadbandDedicatedWithRouterOffering-0001"
  }
  ,
  "productRelationship": [
  {
    "relationshipType": "CONNECTS_TO_SAI",
    "id": "SAI_ID-002"
  }
  ,
  {
    "relationshipType": "DIVERSE_FROM",
    "id": "InternetAccess-00001"
  }
  ],
  "productConfiguration": {
    "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
    "variant": "DEDICATED_WITH_ROUTER",
    "deliveryMechanism": "PHYSICAL_ROUTER",
    "vlan": 200,
    "features": "<<skipped>>",
    "bandwidth": {
      "downstream": {
        "irValue": 10,
        "irUnits": "GBPS"
      }
      ,
      "upstream": {
        "irValue": 10,
        "irUnits": "GBPS"
      }
    }
    ,
    "guaranteedBandwidth": {
      "downstream": {
        "irValue": 5,
        "irUnits": "GBPS"
      }
      ,
      "upstream": {
        "irValue": 5,
        "irUnits": "GBPS"
      }
    }
    ,
    "billingModel": {
      "billingModelType": "FLAT",
      "billingModelPlanName": "DIA Premium Data FLAT"
    }
    ,
    "localNetworkAddresses": {
      "lanAddressBlock": "10.100.0.0/16",
      "dhcpStatus": "ENABLED",
      "dhcpStart": "10.100.1.1",
      "dhcpEnd": "10.100.255.254",
      "dhcpStaticList": [
      {
        "staticMACAddress": "00:11:22:33:44:55",
        "staticIpAddress": "10.100.0.10"
      }
      ,
      {
        "staticMACAddress": "00:11:22:33:44:56",
        "staticIpAddress": "10.100.0.11"
      }
      ,
      {
        "staticMACAddress": "00:11:22:33:44:57",
        "staticIpAddress": "10.100.0.12"
      }
      ],
      "natStatus": "ENABLED",
      "natAddress": "203.0.113.100"
    }
    ,
    "providerIndependentIpAddresses": "ENABLED",
    "autonomousSystemNumber": {
      "asnType": "PUBLIC",
      "asnId": 65001
    }
    ,
    "ipAddressType": "STATIC",
    "publicAddressBlock": {
      "ipv4": "203.0.113.0/24",
      "ipv6": "2001:db8:1234::/48"
    }
    ,
    "transitAddresses": {
      "requestedIpv4TransitAddressPrefixLength": "/30",
      "requestedIpv6TransitAddressPrefixLength": "/124",
      "serviceProviderIpv4TransitAddress": "198.51.100.3/30",
      "serviceProviderIpv6TransitAddress": "2001:db8:abcd:0012::0001/124"
    }
  }
}
@endjson