@startjson

#highlight "id"


#highlight "productConfiguration" / "bandwidth"
#highlight "productConfiguration" / "bandwidth" / "downstream"
#highlight "productConfiguration" / "bandwidth" / "downstream" / "irValue"
#highlight "productConfiguration" / "bandwidth" / "downstream" / "irUnits"
#highlight "productConfiguration" / "bandwidth" / "upstream"
#highlight "productConfiguration" / "bandwidth" / "upstream" / "irValue"
#highlight "productConfiguration" / "bandwidth" / "upstream" / "irUnits"

#highlight "productConfiguration" / "guaranteedBandwidth"
#highlight "productConfiguration" / "guaranteedBandwidth" / "downstream"
#highlight "productConfiguration" / "guaranteedBandwidth" / "downstream" / "irValue"
#highlight "productConfiguration" / "guaranteedBandwidth" / "upstream"
#highlight "productConfiguration" / "guaranteedBandwidth" / "upstream" / "irValue"


{

  "id": "InternetAccess-BroadbandDedicatedWithoutRouter-00001",
  "productOffering": {
    "id": "BroadbandDedicatedWithoutRouterOffering-0001"
  }
  ,
  "productRelationship": [
  {
    "relationshipType": "CONNECTS_TO_SAI",
    "id": "SAI_ID-001"
  }
  ],
  "productConfiguration": {
    "@type": "urn:mef:lso:spec:cantata-sonata:internet-access:v1.0.0:all",
    "variant": "DEDICATED_WITHOUT_ROUTER",
    "deliveryMechanism": "DEMARCATION_ONLY",
    "vlan": 100,
    "features": "<<skipped>>" ,
    "bandwidth": {
      "downstream": {
        "irValue": 1,
        "irUnits": "GBPS"
      }
      ,
      "upstream": {
        "irValue": 1,
        "irUnits": "GBPS"
      }
    }
    ,
    "guaranteedBandwidth": {
      "downstream": {
        "irValue": 500,
        "irUnits": "MBPS"
      }
      ,
      "upstream": {
        "irValue": 500,
        "irUnits": "MBPS"
      }
    }
    ,
    "billingModel": {
      "billingModelType": "BURSTABLE_PERCENTILE",
      "billingModelPlanName": "DIA 95th Percentile Enterprise"
    }
    ,
    "providerIndependentIpAddresses": "DISABLED",
    "ipAddressType": "STATIC",
    "publicAddressesPrefixLength": {
      "ipv4": "/28",
      "ipv6": "/120"
    }
    ,
    "transitAddresses": {
      "requestedIpv4TransitAddressPrefixLength": "/30",
      "requestedIpv6TransitAddressPrefixLength": "/124",
      "serviceProviderIpv4TransitAddress": "198.51.100.3/30",
      "serviceProviderIpv6TransitAddress": "2001:db8:abcd:0012::0001/124"
    }
  }
}

@endjson