@startjson
#highlight "externalId"
#highlight "projectId"
#highlight "productOfferingQualificationItem" / "0" / "action"
#highlight "product"

{
  "externalId": "BuyerPoq-00002",
  "instantSyncQualification": false,
  "provideAlternative": false,
  "projectId": "BuyerProject5",
  "relatedContactInformation": [
    {
      "emailAddress": "john.example@buyer.mplify.com",
      "name": "John Example",
      "number": "12-345-6789",
      "numberExtension": "1234",
      "role": "buyerContactInformation",
      "organization": "Buyer Co."
    }
  ],
  "productOfferingQualificationItem": [
    {
      "action": "modify",
      "id": "item-00001",
      "product": "<<skipped>>"
    }
  ]
}
@endjson