@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
    ClassBorderColor<<ProductSpecification>> FireBrick
}
set namespaceSeparator none

class ProductOfferingConfiguration {
    installationInterval: Duration 
    productConfigurationIdentifier*: string
    productOffering: ProductOfferingRef
}

ProductOfferingConfiguration *-->"1" MEFProductConfiguration : productConfiguration


class MEFProductConfiguration {
    @type*: string <<discriminator>>
}


class urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all"



class urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v5.0.0:all <<ProductSpecification>> {

    <<... attributes are skipped ...>>
}
MEFProductConfiguration <|-- "urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v5.0.0:all"

@enduml
