@startjson
{
  "@type": "urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v5.0.0:all",
  "defaultCeVlanId": 4094,
  "maximumServiceFrameSize": 1522,
  "listOfPhysicalLinks": [
    {
      "physicalLink": "100BASE_T",
      "id": "01",
      "uniConnectorGender": "SOCKET",
      "synchronousEthernet": "ENABLED",
      "uniConnectorType": "RJ45",
      "precisionTiming": "DISABLED"
    }
  ],
  "envelopes": [
    {
      "couplingFlagForIndexZero": true,
      "envelopeID": "env1"
    }
  ]
}


@endjson