@startjson
{
  "@type": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all",
  "maximumFrameSize": 1526,
  "listOfClassOfServiceNames": ["low"],
  "enniEp": {
    "identifier": "UNI-ID-0001-EndPoint-0001"
  },
  "uniEp": {
    "identifier": "ENNI-ID-0001-EndPoint-0001",
    "ingressBandwidthProfilePerClassOfServiceName": [
      {
        "classOfServiceName": "low",
        "bwpFlow": {
          "eirMax": {
            "irValue": 70,
            "irUnits": "MBPS"
          },
          "envelopeRank": 1,
          "cirMax": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "cbs": {
            "dataSizeUnits": "KBYTES",
            "dataSizeValue": 40
          },
          "couplingFlag": true,
          "envelopeId": "env1",
          "tokenRequestOffset": 0,
          "ebs": {
            "dataSizeUnits": "KBYTES",
            "dataSizeValue": 40
          },
          "colorMode": "COLOR_BLIND",
          "cir": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "eir": {
            "irValue": 70,
            "irUnits": "MBPS"
          }
        }
      }
    ]
  }
}
@endjson