@startuml
skinparam {
    ClassBackgroundColor White
    ClassBorderColor Black
}

class Duration {

    amount*: integer
    units*: TimeUnit
}




class GeographicAddressRef {

    href: string
    id*: string
}
RelatedPlaceRef <|-- GeographicAddressRef



class GeographicSiteRef {

    href: string
    id*: string
}
RelatedPlaceRef <|-- GeographicSiteRef




class MEFProductConfiguration {

    @type*: string
}



enum ProductActionAddModifyType {

    add
    modify
}
class ProductOfferingAvailability {

}
ProductOfferingAvailability_Request <|-- ProductOfferingAvailability

ProductOfferingAvailability *-->"1..*" ProductOfferingConfiguration : availableProductOfferingConfigurations


class ProductOfferingAvailability_Request {

    action*: ProductActionAddModifyType
}

ProductOfferingAvailability_Request *--> ProductSpecificationRef : productSpecification
ProductOfferingAvailability_Request *--> ProductRef : productRef
ProductOfferingAvailability_Request *-->"*" ProductRelationship : productRelationship
ProductOfferingAvailability_Request *-->"*" RelatedPlaceRef : place


class ProductOfferingConfiguration {

    productConfigurationIdentifier*: string
}

ProductOfferingConfiguration *-->"1" ProductOfferingRef : productOffering
ProductOfferingConfiguration *-->"1" MEFProductConfiguration : productConfiguration
ProductOfferingConfiguration *-->"1" Duration : installationInterval


class ProductOfferingRef {

    href: string
    id*: string
}



class ProductRef {

    id*: string
    href: string
}



class ProductRelationship {

    href: string
    id*: string
    relationshipType*: string
}



class ProductSpecificationRef {

    href: string
    id*: string
}



class RelatedPlaceRef {

    role*: string
    @type*: string
}



enum TimeUnit {

    seconds
    minutes
    businessHours
    calendarHours
    businessDays
    calendarDays
    calendarMonths
    calendarYears
}
@enduml
