@startjson


#highlight "availableProductOfferingConfigurations"

#highlight "availableProductOfferingConfigurations" / "0" / "productOffering"
#highlight "availableProductOfferingConfigurations" / "0" / "productOffering" / "id"
#highlight "availableProductOfferingConfigurations" / "0" / "productConfigurationIdentifier"

#highlight "availableProductOfferingConfigurations" / "1" / "productOffering"
#highlight "availableProductOfferingConfigurations" / "1" / "productOffering" / "id"
#highlight "availableProductOfferingConfigurations" / "1" / "productConfigurationIdentifier"

#highlight "availableProductOfferingConfigurations" / "2" / "productOffering"
#highlight "availableProductOfferingConfigurations" / "2" / "productOffering" / "id"
#highlight "availableProductOfferingConfigurations" / "2" / "productConfigurationIdentifier"


{
  "action": "add",
  "productSpecification": {
    "id": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all"
  },
  "productRelationship": [
    {
      "id": "UNI-ID-0001",
      "relationshipType": "CONNECTS_TO_UNI"
    },
    {
      "id": "ENNI-ID-0001",
      "relationshipType": "CONNECTS_TO_ENNI"
    }
  ],
  "availableProductOfferingConfigurations": [
    {
      "productOffering": {
        "id": "Access E-Line OVC - Low Class of Service"
      },
      "productConfigurationIdentifier": "PC-ID-0001",
      "productConfiguration": "<<skipped>>",
      "installationInterval": {
        "amount": 0,
        "units": "minutes"
      }
    },
    {
      "productOffering": {
        "id": "Access E-Line OVC - High Class of Service"
      },
      "productConfigurationIdentifier": "PC-ID-0002",
      "productConfiguration": "<<skipped>>",
      "installationInterval": {
        "amount": 3,
        "units": "minutes"
      }
    },
    {
      "productOffering": {
        "id": "Access E-Line OVC - High Class of Service"
      },
      "productConfigurationIdentifier": "PC-ID-0003",
      "productConfiguration": "<<skipped>>",
      "installationInterval": {
        "amount": 3,
        "units": "minutes"
      }
    }
  ]
}

@endjson