@startjson

#highlight "listOfClassOfServiceNames"
#highlight "listOfClassOfServiceNames" / "0"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "classOfServiceName"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "cir"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "cir" / "irValue"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "cirMax"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "cirMax" / "irValue"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "eir"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "eir" / "irValue"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "eirMax"
#highlight "uniEp" / "ingressBandwidthProfilePerClassOfServiceName" / "0" / "bwpFlow" / "eirMax" / "irValue"

{
  "@type": "urn:mef:lso:spec:sonata:access-eline-ovc:v5.0.0:all",
  "maximumFrameSize": 1526,
  "listOfClassOfServiceNames": ["low"],
  "enniEp": {
    "identifier": "ENNI-ID-0001-EndPoint-0001"
  },
  "uniEp": {
    "identifier": "UNI-ID-0001-EndPoint-0001",
    "ingressBandwidthProfilePerClassOfServiceName": [
      {
        "classOfServiceName": "low",
        "bwpFlow": {
          "cir": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "cirMax": {
            "irValue": 0,
            "irUnits": "MBPS"
          },
          "eir": {
            "irValue": 70,
            "irUnits": "MBPS"
          },
          "eirMax": {
            "irValue": 70,
            "irUnits": "MBPS"
          }
        }
      }
    ]
  }
}

@endjson