@startuml

hide footbox

participant Buyer
participant Seller

Buyer -> Seller : POST {{baseUrl}}/pricingDiscovery\n(with PricingDiscovery_Request)

Seller -> Seller : validate Request
Seller -> Seller : validate productConfigurationIdentifier
Seller -> Seller : validate delivery context\nconformance with Product Specification
Seller -> Seller : generate applicable\nPricingAndTerms

alt success
    Buyer <-- Seller : 200 PricingDiscovery\n(with 0 or more PricingAndTerms)
else validation or internal problem
    Buyer <-- Seller: 4xx/5xx : error response
end
@enduml