@startuml

actor Seller

left to right direction
actor Buyer

rectangle {

Seller -[hidden]up-> (2. Retrieve Pricing for a Product Offering Configuration)
Seller -[hidden]up-> (1. Retrieve Product Offering Availability)

Buyer --> (1. Retrieve Product Offering Availability)
Buyer --> (2. Retrieve Pricing for a Product Offering Configuration)
}

@enduml